# -*- coding: utf-8 -*-
"""Per-article knowledge data, articles 157-162."""

DATA = {
    "157": {
        "topic_en": "tiebreaker tactical blueprint",
        "topic_vi": "bản đồ chiến thuật tiebreak",
        "mech_en": "A tiebreaker is a **seven-point sample drawn from a high-variance distribution**, so the correct strategy is not the strategy that maximizes expected value over a match but the one that minimizes variance while retaining a service advantage. That distinction explains why zero-risk opening balls beat aggressive ones at 4-4 and above.",
        "mech_vi": "Tiebreak là một **mẫu bảy điểm được rút từ một phân phối phương sai cao**, nên chiến lược đúng không phải là chiến lược tối đa hóa giá trị kỳ vọng trên cả trận mà là chiến lược giảm thiểu phương sai trong khi vẫn giữ lợi thế giao bóng. Sự khác biệt đó giải thích vì sao những quả bóng mở rủi ro bằng không lại tốt hơn những quả bóng hung hăng ở tỷ số 4-4 trở lên.",
        "vars": [
            ["First-Serve Percentage Floor", "Mức sàn tỷ lệ phát bóng một", "68-72%"],
            ["Unforced Error Budget", "Ngân sách lỗi tự đánh bại", "0-1 per tiebreak"],
            ["Mini-Break Conversion Target", "Mục tiêu chuyển đổi mini-break", "50-60%"],
        ],
        "subs": [
            ["Variance Mathematics of the Seven-Point Sample", "Toán Học Phương Sai Của Mẫu Bảy Điểm",
             "Over seven points, a single unforced error changes the outcome probability by 8-14 percentage points, roughly triple its effect across a full set. This is why the tiebreak rewards error avoidance over winner production, and why a 2% improvement in first-serve percentage is worth more than a 5% improvement in winner rate.",
             "Trong bảy điểm, một lỗi tự đánh bại duy nhất làm thay đổi xác suất kết quả 8-14 điểm phần trăm, gấp khoảng ba lần hiệu ứng của nó trên cả một set. Đây là lý do tiebreak thưởng cho việc tránh lỗi hơn là tạo winner, và vì sao cải thiện 2% tỷ lệ phát bóng một có giá trị hơn cải thiện 5% tỷ lệ winner."],
            ["Service Rotation and Mini-Break Windows", "Vòng Xoay Giao Bóng & Cửa Sổ Mini-Break",
             "The serving pattern in a tiebreak concentrates pressure at specific points: the sixth and eighth points are the highest-leverage serves in the sequence. Blueprints should therefore pre-declare which serve pattern is used at 3-2, at 4-3, and at 5-4, because improvisation at those points is what produces double faults.",
             "Mẫu giao bóng trong tiebreak tập trung áp lực vào những điểm cụ thể: điểm thứ sáu và thứ tám là những cú phát có đòn bẩy cao nhất trong trình tự. Do đó bản đồ cần tuyên bố trước mẫu phát bóng nào được dùng ở 3-2, ở 4-3, và ở 5-4, vì ứng biến ở những điểm đó chính là thứ tạo ra lỗi phát bóng kép."],
        ],
        "steps": [
            ["Pre-Declare the Opening Pattern", "Before the tiebreak starts, name the serve location and the +1 pattern used on the first two service points; executing a prepared pattern removes decision latency."],
            ["Freeze Escalation Until 5-5", "Until 5-5, every ball must land beyond 6.0 m with a minimum net clearance of 0.8 m; escalation is only permitted after the mini-break has been secured."],
            ["Tuyên Bố Trước Mẫu Mở Đầu", "Trước khi tiebreak bắt đầu, gọi tên vị trí phát bóng và mẫu +1 dùng cho hai điểm giao đầu tiên; thực thi một mẫu đã chuẩn bị sẽ loại bỏ độ trễ quyết định."],
            ["Đóng Băng Việc Nâng Mức Cho Tới 5-5", "Cho tới 5-5, mọi quả bóng phải rơi xa hơn 6,0 m với chiều cao vượt lưới tối thiểu 0,8 m; chỉ được phép nâng mức sau khi mini-break đã được giành."],
        ],
        "errs": [
            ["Attempting a big second serve at 4-4", "Pressure is managed by aggression instead of by margin", "Double fault converts a neutral tiebreak into a lost tiebreak", "At 4-4 and beyond, serve second serves with 10-15% more spin and target the body; never chase a free point",
             "Thử cú phát bóng hai lớn ở 4-4", "Áp lực được quản lý bằng sự hung hăng thay vì bằng biên an toàn", "Lỗi phát bóng kép biến một tiebreak trung hòa thành tiebreak đã thua", "Ở 4-4 trở lên, phát bóng hai với 10-15% xoáy nhiều hơn và nhắm vào người; không bao giờ đuổi theo một điểm miễn phí"],
            ["Trading winners early in the tiebreak", "The tiebreak is treated as a normal game", "The unforced error budget is exhausted before the mini-break window", "Cap the error budget at one until 5-5; log every escalation attempt and review it afterwards",
             "Đổi winner sớm trong tiebreak", "Tiebreak bị coi như một game bình thường", "Ngân sách lỗi tự đánh bại bị tiêu hết trước cửa sổ mini-break", "Giới hạn ngân sách lỗi ở một cho tới 5-5; ghi lại mọi lần thử nâng mức và xem lại sau đó"],
        ],
        "drills": [
            ["Tiebreak Blueprint Reps", "Play five tiebreaks starting at 4-4 with the error budget enforced", "Hiệp Bản Đồ Tiebreak", "Chơi năm tiebreak bắt đầu từ 4-4 với ngân sách lỗi được ép buộc"],
            ["Serve Pattern Recall", "Declare serve location and +1 aloud before each service point in a tiebreak", "Nhớ Mẫu Phát Bóng", "Tuyên bố vị trí phát bóng và mẫu +1 thành lời trước mỗi điểm giao trong tiebreak"],
        ],
    },
    "158": {
        "topic_en": "first-strike versus grinding analytics",
        "topic_vi": "phân tích đánh thẳng so với chiến tranh thể lực",
        "mech_en": "First-strike tennis and grinding are not philosophies but **resource allocations**. First-strike spends energy in short, high-intensity bursts and accepts a higher error rate; grinding spends energy across a longer duration and accepts a lower point-conversion rate. The correct allocation is determined by rally-length distributions, not by identity.",
        "mech_vi": "Tennis đánh thẳng và lối bám trụ không phải là triết lý mà là **phân bổ nguồn lực**. Đánh thẳng tiêu hao năng lượng trong những đợt ngắn cường độ cao và chấp nhận tỷ lệ lỗi cao hơn; bám trụ tiêu hao năng lượng qua thời lượng dài hơn và chấp nhận tỷ lệ chuyển đổi điểm thấp hơn. Phân bổ đúng được xác định bởi phân phối độ dài pha bóng, không bởi bản sắc.",
        "vars": [
            ["Mean Rally Length Target", "Độ dài pha bóng trung bình mục tiêu", "3.5-5.5 shots"],
            ["Energy Cost per Point", "Chi phí năng lượng mỗi điểm", "0.9-1.4 kJ"],
            ["Point Conversion at Short Rallies", "Chuyển đổi điểm ở pha bóng ngắn", "58-66%"],
        ],
        "subs": [
            ["Rally-Length Distribution as the Decision Variable", "Phân Phối Độ Dài Pha Bóng Như Biến Quyết Định",
             "Matches are won by whichever style produces a more favourable conversion rate inside the observed rally-length distribution. If 60% of points end inside four shots, first-strike allocation is efficient; if 55% exceed seven shots, the same allocation produces an unsustainable error rate and a loss of aerobic reserve.",
             "Các trận đấu được thắng bởi phong cách nào tạo ra tỷ lệ chuyển đổi thuận lợi hơn trong phân phối độ dài pha bóng quan sát được. Nếu 60% số điểm kết thúc trong bốn cú, phân bổ đánh thẳng là hiệu quả; nếu 55% vượt bảy cú, cùng phân bổ đó tạo ra tỷ lệ lỗi không bền vững và mất dự trữ ưa khí."],
            ["Energy Accounting Across a Three-Set Match", "Hạch Toán Năng Lượng Qua Trận Ba Set",
             "A three-set match at competitive intensity costs 1.200-1.800 kJ of above-resting energy expenditure, with roughly 60% attributable to movement and 40% to stroke production. First-strike reduces stroke cost per point by 15-25% while raising restart costs, which is why it works best on fast surfaces with short recovery windows.",
             "Một trận ba set ở cường độ thi đấu tiêu hao 1.200-1.800 kJ năng lượng tiêu hao trên mức nghỉ, với khoảng 60% thuộc về di chuyển và 40% thuộc về sản xuất cú đánh. Đánh thẳng giảm chi phí cú đánh mỗi điểm 15-25% trong khi tăng chi phí tái khởi động, đó là lý do nó hiệu quả nhất trên mặt sân nhanh với cửa sổ phục hồi ngắn."],
        ],
        "steps": [
            ["Measure the Distribution Before Choosing a Style", "Count rally lengths in the first two games; commit to an allocation only after the distribution is observed, not before."],
            ["Set the Conversion Floor", "Declare the minimum conversion rate that makes the chosen allocation viable (58-66% inside four shots, or 45-52% beyond seven); abandon the allocation if the floor is missed for two consecutive games."],
            ["Đo Phân Phối Trước Khi Chọn Phong Cách", "Đếm độ dài pha bóng trong hai game đầu; chỉ cam kết một phân bổ sau khi phân phối được quan sát, không cam kết trước."],
            ["Đặt Mức Sàn Chuyển Đổi", "Tuyên bố tỷ lệ chuyển đổi tối thiểu làm cho phân bổ đã chọn khả thi (58-66% trong bốn cú, hoặc 45-52% trên bảy cú); từ bỏ phân bổ nếu mức sàn bị bỏ lỡ trong hai game liên tiếp."],
        ],
        "errs": [
            ["Committing to first-strike on a slow surface", "Style is chosen by preference rather than by surface and distribution", "Energy reserve is exhausted by the third set while conversion stays flat", "Re-measure rally length on the actual surface before the match; if 55% of points exceed seven shots, shift allocation toward grinding",
             "Cam kết đánh thẳng trên mặt sân chậm", "Phong cách được chọn theo sở thích thay vì theo mặt sân và phân phối", "Dự trữ năng lượng cạn kiệt từ set thứ ba trong khi tỷ lệ chuyển đổi không tăng", "Đo lại độ dài pha bóng trên mặt sân thực tế trước trận; nếu 55% số điểm vượt bảy cú, chuyển phân bổ về phía bám trụ"],
            ["Alternating styles without a declared trigger", "Tactical identity is unstable under pressure", "Neither allocation reaches its conversion floor and errors rise in both", "Declare the switch trigger explicitly: a switch occurs only after two consecutive games below the conversion floor",
             "Luân phiên phong cách không có tín hiệu tuyên bố", "Bản sắc chiến thuật không ổn định dưới áp lực", "Không phân bổ nào đạt mức sàn chuyển đổi và lỗi tăng ở cả hai", "Tuyên bố tín hiệu chuyển đổi một cách tường minh: chỉ chuyển sau hai game liên tiếp dưới mức sàn chuyển đổi"],
        ],
        "drills": [
            ["Rally-Length Logging", "Partner logs rally length and conversion for two practice sets", "Ghi Nhận Độ Dài Pha Bóng", "Đồng đội ghi độ dài pha bóng và tỷ lệ chuyển đổi trong hai set tập"],
            ["Allocation Switch Set", "Play a set with a declared allocation and switch only on the trigger", "Set Chuyển Phân Bổ", "Chơi một set với phân bổ đã tuyên bố và chỉ chuyển khi có tín hiệu"],
        ],
    },
    "159": {
        "topic_en": "shot-tree decision modeling for in-match autopilot",
        "topic_vi": "mô hình cây quyết định cú đánh cho chế độ tự động trong trận",
        "mech_en": "A shot tree is a **pre-computed decision structure** that maps a small number of situational inputs onto a single shot selection, so that in-match decisions consume recognition rather than deliberation. Its purpose is to remove choice fatigue from high-leverage moments, not to eliminate adaptability.",
        "mech_vi": "Cây quyết định cú đánh là một **cấu trúc quyết định được tính trước** ánh xạ một số ít đầu vào tình huống vào một lựa chọn cú đánh duy nhất, để các quyết định trong trận tiêu tốn năng lực nhận diện thay vì năng lực cân nhắc. Mục đích của nó là loại bỏ sự mệt mỏi vì lựa chọn khỏi những thời điểm đòn bẩy cao, không phải để loại bỏ khả năng thích nghi.",
        "vars": [
            ["Tree Depth", "Độ sâu của cây", "3 levels maximum"],
            ["Input Variables per Node", "Số biến đầu vào mỗi nút", "2 maximum"],
            ["Decision Latency Target", "Mục tiêu độ trễ quyết định", "under 400 ms"],
        ],
        "subs": [
            ["Construction Rules for a Usable Tree", "Quy Tắc Xây Dựng Một Cây Dùng Được",
             "A usable tree has at most three levels and two input variables per node: ball depth, ball height, and score-state leverage. Deeper trees exceed working memory under fatigue, and trees with more inputs are abandoned precisely when they are most needed.",
             "Một cây dùng được có tối đa ba tầng và hai biến đầu vào mỗi nút: chiều sâu bóng, độ cao bóng, và đòn bẩy trạng thái tỷ số. Cây sâu hơn vượt quá trí nhớ làm việc khi mệt, và cây có nhiều đầu vào hơn sẽ bị bỏ rơi đúng vào lúc cần nhất."],
            ["From Tree to Autopilot: Repetition Requirements", "Từ Cây Đến Tự Động: Yêu Cầu Lặp Lại",
             "A tree becomes automatic only after roughly 300-500 repetitions per branch under scored conditions. Below that threshold the player still deliberates, which is slower than intuition and produces hesitation at exactly the moments the tree was designed to simplify.",
             "Cây chỉ trở nên tự động sau khoảng 300-500 lần lặp mỗi nhánh trong điều kiện tính điểm. Dưới ngưỡng đó người chơi vẫn cân nhắc, chậm hơn trực giác và tạo ra sự do dự đúng vào những thời điểm mà cây được thiết kế để đơn giản hóa."],
        ],
        "steps": [
            ["Draw the Tree on One Page", "If the tree does not fit on one page, it is too large; reduce the branch count until it does."],
            ["Rehearse Under Scored Conditions", "Each branch requires scored repetitions; unscored rehearsal produces recognition without commitment."],
            ["Vẽ Cây Trên Một Trang", "Nếu cây không vừa một trang, nó quá lớn; giảm số nhánh cho tới khi vừa."],
            ["Tập Luyện Trong Điều Kiện Tính Điểm", "Mỗi nhánh cần số lần lặp có tính điểm; tập không tính điểm tạo ra nhận diện mà không có cam kết."],
        ],
        "errs": [
            ["Building a tree with more than three levels", "Completeness is prioritized over usability", "The tree is abandoned after the second set of a long match", "Cap the tree at three levels and two inputs per node; verify recall under fatigue before trusting it",
             "Xây cây có hơn ba tầng", "Tính đầy đủ được ưu tiên hơn tính khả dụng", "Cây bị bỏ rơi sau set thứ hai của một trận dài", "Giới hạn cây ở ba tầng và hai đầu vào mỗi nút; kiểm chứng khả năng nhớ lại khi mệt trước khi tin dùng"],
            ["Treating the tree as a substitute for adaptability", "Autopilot is applied regardless of opponent adjustment", "Opponent counters are never answered and the tree becomes exploitable", "Reserve one branch as an override triggered by two consecutive lost patterns",
             "Coi cây như thay thế cho khả năng thích nghi", "Chế độ tự động được áp dụng bất kể đối thủ điều chỉnh", "Các phương án đối phó không bao giờ được trả lời và cây trở nên bị khai thác", "Dành một nhánh làm quyền ghi đè, kích hoạt khi hai mẫu liên tiếp bị thua"],
        ],
        "drills": [
            ["Branch Repetition Block", "One branch, 40 scored repetitions, tracked for adherence", "Khối Lặp Nhánh", "Một nhánh, 40 lần lặp có tính điểm, theo dõi mức tuân thủ"],
            ["Fatigue Recall Test", "State the tree aloud after 90 minutes of hitting", "Kiểm Tra Nhớ Khi Mệt", "Đọc cây thành lời sau 90 phút đánh bóng"],
        ],
    },
    "160": {
        "topic_en": "strategic match audit and post-game analytics",
        "topic_vi": "kiểm toán chiến lược trận đấu và phân tích sau trận",
        "mech_en": "A match audit converts a chaotic narrative into a **small set of countable outcomes indexed by score state**. Its purpose is not analysis for its own sake but the production of one or two explicit, testable changes for the next match; anything beyond that is not retained or applied.",
        "mech_vi": "Kiểm toán trận đấu chuyển một câu chuyện hỗn loạn thành một **tập nhỏ các kết quả đếm được, được đánh chỉ mục theo trạng thái tỷ số**. Mục đích của nó không phải là phân tích vì chính nó mà là tạo ra một hoặc hai thay đổi tường minh, có thể kiểm chứng cho trận kế tiếp; mọi thứ vượt quá đó sẽ không được ghi nhớ và không được áp dụng.",
        "vars": [
            ["Countable Pattern Outcomes", "Số kết quả mẫu đếm được", "4-6 categories"],
            ["Audit Completion Window", "Cửa sổ hoàn thành kiểm toán", "within 24 h"],
            ["Actionable Changes per Match", "Số thay đổi khả thi mỗi trận", "1-2 maximum"],
        ],
        "subs": [
            ["Audit Categories and Countable Metrics", "Các Hạng Mục Kiểm Toán & Chỉ Số Đếm Được",
             "Six categories cover nearly all decision quality: pattern adherence, error type distribution, conversion by score state, serve-location distribution under pressure, recovery-position accuracy, and net-approach outcomes. Each category requires a count, not an impression.",
             "Sáu hạng mục bao quát gần như toàn bộ chất lượng quyết định: mức tuân thủ mẫu, phân phối loại lỗi, tỷ lệ chuyển đổi theo trạng thái tỷ số, phân phối vị trí phát bóng dưới áp lực, độ chính xác vị trí hồi vị, và kết quả lên lưới. Mỗi hạng mục cần một con số đếm, không cần một ấn tượng."],
            ["From Audit to Next-Match Adjustment", "Từ Kiểm Toán Đến Điều Chỉnh Trận Kế Tiếp",
             "The audit produces one or two changes with an explicit measurement rule: for example, raise first-serve percentage at break points by 6 points, or reduce escalations on balls landing beyond 6 m to zero. Changes without a measurement rule are not implemented in practice.",
             "Kiểm toán tạo ra một hoặc hai thay đổi với quy tắc đo lường tường minh: ví dụ nâng tỷ lệ phát bóng một ở điểm break thêm 6 điểm, hoặc giảm số lần nâng mức trên bóng rơi xa hơn 6 m xuống bằng không. Những thay đổi không có quy tắc đo lường sẽ không được thực hiện trên thực tế."],
        ],
        "steps": [
            ["Count Before Interpreting", "Record raw counts for all six categories before offering any interpretation; interpretation contaminates counting."],
            ["Convert to Two Changes Maximum", "Reduce the audit to at most two changes, each with a numeric target and a verification date."],
            ["Đếm Trước Khi Diễn Giải", "Ghi lại số đếm thô cho cả sáu hạng mục trước khi đưa ra bất kỳ diễn giải nào; diễn giải sẽ làm nhiễm bẩn việc đếm."],
            ["Chuyển Thành Tối Đa Hai Thay Đổi", "Rút gọn kiểm toán thành tối đa hai thay đổi, mỗi thay đổi có mục tiêu bằng số và ngày kiểm chứng."],
        ],
        "errs": [
            ["Auditing without counts", "The audit relies on memory and emotional salience", "The most memorable point is treated as the most important point", "Require a numeric count for each of the six categories before any conclusion is written",
             "Kiểm toán không có số đếm", "Kiểm toán dựa vào ký ức và mức độ nổi bật cảm xúc", "Điểm đáng nhớ nhất được coi là điểm quan trọng nhất", "Yêu cầu một con số đếm cho mỗi hạng mục trong sáu hạng mục trước khi viết bất kỳ kết luận nào"],
            ["Producing a long list of improvements", "The audit is written as a report rather than as an instruction", "Nothing from the list is applied in the next match", "Cap the output at two changes with numeric targets and a verification date",
             "Tạo ra một danh sách dài các cải thiện", "Kiểm toán được viết như một báo cáo thay vì như một chỉ thị", "Không có gì trong danh sách được áp dụng ở trận kế tiếp", "Giới hạn đầu ra ở hai thay đổi với mục tiêu bằng số và một ngày kiểm chứng"],
        ],
        "drills": [
            ["Six-Category Count", "Count all six categories from a recorded set", "Đếm Sáu Hạng Mục", "Đếm cả sáu hạng mục từ một set đã ghi hình"],
            ["Two-Change Commitment", "Write exactly two changes with numeric targets before the next session", "Cam Kết Hai Thay Đổi", "Viết đúng hai thay đổi với mục tiêu bằng số trước buổi tập kế tiếp"],
        ],
    },
    "161": {
        "topic_en": "long-term periodization and bio-agentic conditioning",
        "topic_vi": "chu kỳ hóa dài hạn và huấn luyện thể lực theo phản hồi sinh học",
        "mech_en": "Long-term periodization distributes adaptation across **months and years** rather than sessions, which is the only structure capable of developing qualities whose timescales differ by an order of magnitude - tendon capacity in months, aerobic base in weeks, neural skill in days. Bio-agentic conditioning adds continuous individual feedback so that the plan is a hypothesis revised by data rather than a calendar.",
        "mech_vi": "Chu kỳ hóa dài hạn phân bổ thích nghi qua **nhiều tháng và nhiều năm** thay vì qua từng buổi tập, và đây là cấu trúc duy nhất có khả năng phát triển những phẩm chất có thời gian thích nghi khác nhau một bậc độ lớn - năng lực gân tính bằng tháng, nền ưa khí tính bằng tuần, kỹ năng thần kinh tính bằng ngày. Huấn luyện thể lực theo phản hồi sinh học bổ sung phản hồi cá nhân liên tục để kế hoạch là một giả thuyết được chỉnh sửa bằng dữ liệu thay vì một lịch trình.",
        "vars": [
            ["Macrocycle Length", "Độ dài chu kỳ lớn", "16-24 weeks"],
            ["Tendon Adaptation Timescale", "Thời gian thích nghi của gân", "10-14 weeks"],
            ["Autonomic Review Cadence", "Nhịp xem lại tự chủ", "every 7 days"],
        ],
        "subs": [
            ["Timescale Mismatch and Its Consequences", "Sự Lệch Thang Thời Gian & Hệ Quả",
             "Neural adaptations appear in 2-4 weeks, muscle architecture in 6-10 weeks, tendon stiffness in 10-14 weeks, and bone density in 6-12 months. Programming that progresses at the fastest timescale systematically outruns the slowest tissue, which is the mechanism behind most overuse injuries in competitive players.",
             "Thích nghi thần kinh xuất hiện trong 2-4 tuần, kiến trúc cơ trong 6-10 tuần, độ cứng gân trong 10-14 tuần, và mật độ xương trong 6-12 tháng. Việc lập trình tiến triển theo thang thời gian nhanh nhất sẽ vượt qua mô chậm nhất một cách hệ thống, và đây chính là cơ chế đằng sau phần lớn chấn thương do quá tải ở vận động viên thi đấu."],
            ["Bio-Agentic Feedback Loop", "Vòng Phản Hồi Sinh Học",
             "The loop is deliberately minimal: measure, compare against a 7-day rolling baseline, select one of three pre-planned session variants, and record the outcome. Automation reduces compliance cost, and compliance - not sophistication - is the limiting factor in long-term programming.",
             "Vòng lặp được giữ cố ý tối giản: đo, so với nền trượt 7 ngày, chọn một trong ba biến thể buổi tập đã lên kế hoạch trước, và ghi lại kết quả. Tự động hóa làm giảm chi phí tuân thủ, và tuân thủ - không phải sự tinh vi - mới là yếu tố giới hạn trong lập trình dài hạn."],
        ],
        "steps": [
            ["Set the Macrocycle Before the Microcycle", "Define the 16-24 week arc and its two or three priority qualities before writing any weekly plan; weekly plans without a macrocycle optimize locally and fail globally."],
            ["Schedule Deloads in Advance", "Place deload weeks in the calendar at the start of the macrocycle; deloads chosen reactively are skipped under competitive pressure."],
            ["Đặt Chu Kỳ Lớn Trước Chu Kỳ Nhỏ", "Xác định vòng cung 16-24 tuần và hai hoặc ba phẩm chất ưu tiên trước khi viết bất kỳ kế hoạch tuần nào; kế hoạch tuần không có chu kỳ lớn sẽ tối ưu cục bộ và thất bại toàn cục."],
            ["Sắp Lịch Giảm Tải Trước", "Đặt các tuần giảm tải vào lịch ngay từ đầu chu kỳ lớn; giảm tải được chọn phản ứng sẽ bị bỏ qua dưới áp lực thi đấu."],
        ],
        "errs": [
            ["Progressing load at the neural timescale", "Improvement in skill and strength tests is read as readiness for more load", "Tendon and bone lag behind and overuse injury appears at week 8-14", "Cap load progression at 10-15% weekly and hold the slowest tissue's timescale as the ceiling",
             "Tăng tải theo thang thời gian thần kinh", "Cải thiện ở các bài kiểm tra kỹ năng và sức mạnh bị hiểu là sẵn sàng cho tải cao hơn", "Gân và xương chậm hơn và chấn thương do quá tải xuất hiện ở tuần 8-14", "Giới hạn tăng tải ở 10-15% mỗi tuần và lấy thang thời gian của mô chậm nhất làm trần"],
            ["Skipping deloads during the competitive season", "The calendar is treated as fixed and the body as adjustable", "Accumulated fatigue flattens performance exactly when it matters", "Pre-schedule deloads and protect them as non-negotiable; reduce volume 30-40% while holding intensity",
             "Bỏ qua giảm tải trong mùa thi đấu", "Lịch được coi là cố định và cơ thể được coi là điều chỉnh được", "Mệt mỏi tích lũy làm phẳng hiệu suất đúng vào lúc quan trọng", "Sắp lịch giảm tải trước và bảo vệ chúng như điều không thương lượng; giảm khối lượng 30-40% trong khi giữ nguyên cường độ"],
        ],
        "drills": [
            ["Macrocycle Mapping", "Draw the 20-week arc with priority qualities and deloads marked", "Vẽ Bản Đồ Chu Kỳ Lớn", "Vẽ vòng cung 20 tuần với các phẩm chất ưu tiên và các tuần giảm tải được đánh dấu"],
            ["Weekly Variant Selection", "Choose one of three session variants from rolling readiness markers", "Chọn Biến Thể Mỗi Tuần", "Chọn một trong ba biến thể buổi tập từ các dấu hiệu sẵn sàng trượt"],
        ],
    },
    "162": {
        "topic_en": "tennis elbow eccentric wrist extensor protocols",
        "topic_vi": "phác đồ lệch tâm cho cơ duỗi cổ tay trong viêm gân khuỷu",
        "mech_en": "Lateral elbow tendinopathy is a **load-tolerance failure of the common extensor tendon**, not an inflammatory condition requiring rest. The therapeutic mechanism is progressive mechanical loading, primarily eccentric and isometric, which restores tendon stiffness and collagen organization; rest alone reliably produces recurrence within 8-12 weeks.",
        "mech_vi": "Bệnh lý gân khuỷu ngoài là một **thất bại về ngưỡng chịu tải của gân duỗi chung**, không phải một tình trạng viêm cần nghỉ ngơi. Cơ chế trị liệu là tải cơ học tiến triển, chủ yếu là lệch tâm và đẳng trường, giúp phục hồi độ cứng gân và tổ chức collagen; chỉ nghỉ ngơi mà thôi sẽ tái phát một cách đáng tin trong vòng 8-12 tuần.",
        "vars": [
            ["Eccentric Load Progression", "Tiến triển tải lệch tâm", "0.5 to 3.0 kg over 12 weeks"],
            ["Tempo Requirement", "Yêu cầu nhịp", "3 s eccentric / 1 s concentric"],
            ["Pain Ceiling During Exercise", "Ngưỡng đau khi tập", "3/10 maximum"],
        ],
        "subs": [
            ["Tendon Pathology and the Load-Tolerance Model", "Bệnh Lý Gân & Mô Hình Ngưỡng Chịu Tải",
             "Histologically, tendinopathy shows collagen disorganization, increased ground substance, and neovascularization rather than inflammatory infiltrate. Mechanical loading restores matrix organization and raises the tendon's tolerated load; the adaptation requires 10-14 weeks, which is why protocols shorter than eight weeks routinely fail.",
             "Về mô học, bệnh lý gân cho thấy collagen mất tổ chức, tăng chất nền, và tân mạch hóa thay vì thâm nhiễm viêm. Tải cơ học phục hồi tổ chức chất nền và nâng mức tải mà gân chịu được; thích nghi cần 10-14 tuần, đó là lý do các phác đồ ngắn hơn tám tuần thường thất bại."],
            ["Isometric Analgesia and Its Limits", "Giảm Đau Bằng Đẳng Trường & Giới Hạn Của Nó",
             "Isometric contractions at 70% of maximum voluntary contraction held for 30-45 s produce short-term analgesia that can last 45 minutes, which is useful before competition but must not be mistaken for healing. Repeated analgesia without progressive loading delays structural recovery.",
             "Các co đẳng trường ở 70% lực co tối đa tự nguyện giữ 30-45 giây tạo ra hiệu ứng giảm đau ngắn hạn có thể kéo dài 45 phút, hữu ích trước thi đấu nhưng không được nhầm với việc chữa lành. Giảm đau lặp lại mà không có tải tiến triển sẽ làm chậm phục hồi cấu trúc."],
        ],
        "steps": [
            ["Establish the Pain and Load Baseline", "Record pain at rest, during grip, and during the protocol on a 0-10 scale before the first session; every progression decision is made against this baseline."],
            ["Progress Load Only When Pain Stays Below 3/10", "The 24-hour pain response governs progression; if pain exceeds 3/10 or lasts beyond 24 h, hold the load for another week."],
            ["Thiết Lập Nền Đau Và Nền Tải", "Ghi lại mức đau khi nghỉ, khi nắm chặt, và khi thực hiện phác đồ theo thang 0-10 trước buổi đầu tiên; mọi quyết định tiến triển đều dựa trên nền này."],
            ["Chỉ Tăng Tải Khi Đau Dưới 3/10", "Phản ứng đau trong 24 giờ chi phối việc tiến triển; nếu đau vượt 3/10 hoặc kéo dài quá 24 giờ, giữ nguyên tải thêm một tuần."],
        ],
        "errs": [
            ["Complete rest until pain resolves", "Pain is treated as a signal to unload rather than to load progressively", "The tendon loses further capacity and symptoms return within 8-12 weeks", "Replace rest with progressive eccentric and isometric loading at a pain ceiling of 3/10",
             "Nghỉ hoàn toàn cho tới khi hết đau", "Đau được coi là tín hiệu để giảm tải thay vì để tăng tải tiến triển", "Gân mất thêm năng lực và triệu chứng tái phát trong vòng 8-12 tuần", "Thay nghỉ ngơi bằng tải lệch tâm và đẳng trường tiến triển với ngưỡng đau 3/10"],
            ["Progressing too quickly after analgesia", "Pain relief is interpreted as tissue recovery", "A new flare-up occurs and the protocol is abandoned at week 4-6", "Hold each load level for a minimum of 10-14 days regardless of how comfortable it feels",
             "Tiến triển quá nhanh sau khi giảm đau", "Giảm đau được hiểu là mô đã phục hồi", "Một đợt bùng phát mới xảy ra và phác đồ bị bỏ ở tuần 4-6", "Giữ mỗi mức tải tối thiểu 10-14 ngày bất kể cảm giác thoải mái đến đâu"],
        ],
        "drills": [
            ["Eccentric Wrist Extension", "3 s lowering phase with a 0.5-3.0 kg load, 3 x 15", "Duỗi Cổ Tay Lệch Tâm", "Pha hạ 3 giây với tải 0,5-3,0 kg, 3 x 15"],
            ["Isometric Hold", "70% maximum grip-related isometric for 30-45 s, 5 holds", "Giữ Đẳng Trường", "Giữ đẳng trường 70% tối đa liên quan tới nắm chặt trong 30-45 giây, 5 lần"],
        ],
    },
}
