# -*- coding: utf-8 -*-
"""Per-article knowledge data, articles 181-186."""

DATA = {
    "181": {
        "topic_en": "patellar tendinopathy prevention in high acceleration and braking",
        "topic_vi": "phòng ngừa bệnh gân bánh chè trong tăng tốc và hãm tốc cao",
        "mech_en": "Patellar tendon load is the product of **knee flexion angle, braking impulse, and repetition count**, and hard-court tennis supplies all three at high values. Prevention therefore depends on raising the tendon's load tolerance through slow heavy loading rather than on reducing play alone.",
        "mech_vi": "Tải lên gân bánh chè là tích của **góc gập gối, xung lực hãm và số lần lặp lại**, và tennis trên sân cứng cung cấp cả ba ở mức cao. Do đó phòng ngừa phụ thuộc vào việc nâng ngưỡng chịu tải của gân thông qua nạp tải chậm và nặng thay vì chỉ giảm thời gian thi đấu.",
        "vars": [
            ["Decline Squat Load", "Tải bài squat dốc", "progressive to 1.2-1.6 x body mass"],
            ["Pain Ceiling", "Ngưỡng đau", "3/10 during loading"],
            ["Weekly Jump Load", "Tải nhảy mỗi tuần", "cap at 140-180 contacts"],
        ],
        "subs": [
            ["Load Determinants at the Patellar Tendon", "Các Yếu Tố Quyết Định Tải Ở Gân Bánh Chè",
             "Tendon force rises steeply with knee flexion beyond 60 degrees and with braking impulse. Tennis produces repeated entries into that range during defensive slides, split steps, and change-of-direction plants, which is why volume management alone rarely resolves symptoms without a concurrent loading programme.",
             "Lực gân tăng dốc khi gối gập quá 60 độ và khi xung lực hãm tăng. Tennis tạo ra sự lặp lại việc đi vào dải đó trong các pha trượt phòng thủ, bước tách, và đặt chân đổi hướng, đó là lý do quản lý khối lượng đơn thuần hiếm khi giải quyết được triệu chứng nếu không có một chương trình nạp tải song song."],
            ["Heavy Slow Resistance and Its Timeline", "Kháng Lực Chậm Nặng & Lộ Trình Của Nó",
             "Heavy slow resistance at 3-4 s per repetition produces both mechanical loading and analgesic effects, with measurable improvement in pain and function across 12 weeks. The critical adherence rule is that load is progressed only when the 24-hour pain response remains below 3 of 10.",
             "Kháng lực chậm nặng ở 3-4 giây mỗi lần lặp tạo ra cả tải cơ học lẫn hiệu ứng giảm đau, với cải thiện đo được về đau và chức năng trong 12 tuần. Quy tắc tuân thủ then chốt là tải chỉ được tăng khi phản ứng đau trong 24 giờ vẫn dưới 3 trên 10."],
        ],
        "steps": [
            ["Establish the Pain Baseline", "Record pain during play, after play, and the next morning before starting any loading programme."],
            ["Load at Slow Tempo, Not High Volume", "Use 3-4 s repetitions at moderate load rather than high repetitions; tempo determines the mechanical stimulus."],
            ["Thiết Lập Nền Đau", "Ghi lại mức đau khi chơi, sau khi chơi, và sáng hôm sau trước khi bắt đầu bất kỳ chương trình nạp tải nào."],
            ["Nạp Tải Với Nhịp Chậm, Không Khối Lượng Lớn", "Dùng nhịp 3-4 giây ở tải vừa thay vì số lần lặp cao; nhịp quyết định kích thích cơ học."],
        ],
        "errs": [
            ["Resting until pain disappears", "Pain is treated as a signal to unload", "Tendon capacity falls further and symptoms return on return to play", "Replace rest with heavy slow resistance and cap pain at 3/10 during loading",
             "Nghỉ cho tới khi đau biến mất", "Đau được coi là tín hiệu để giảm tải", "Năng lực gân giảm thêm và triệu chứng tái phát khi quay lại thi đấu", "Thay nghỉ ngơi bằng kháng lực chậm nặng và giới hạn đau ở 3/10 trong khi nạp tải"],
            ["Ignoring jump-load accumulation", "Jump training is counted separately from court work", "Total impact load exceeds tendon tolerance silently", "Count all ground contacts weekly and cap the total at 140-180 during a symptomatic period",
             "Bỏ qua tích lũy tải nhảy", "Tập nhảy được đếm tách biệt khỏi tập trên sân", "Tổng tải va đập vượt dung nạp của gân một cách âm thầm", "Đếm toàn bộ số lần tiếp đất mỗi tuần và giới hạn tổng ở 140-180 trong giai đoạn có triệu chứng"],
        ],
        "drills": [
            ["Decline Squat Slow Tempo", "3 x 15 at 3 s down and 3 s up, load progressed weekly", "Squat Dốc Nhịp Chậm", "3 x 15 với 3 giây xuống và 3 giây lên, tải tăng mỗi tuần"],
            ["Isometric Wall Sit", "5 x 45 s at 70% effort for analgesia before play", "Ngồi Tựa Tường Đẳng Trường", "5 x 45 giây ở 70% nỗ lực để giảm đau trước khi thi đấu"],
        ],
    },
    "182": {
        "topic_en": "adductor strain mitigation in extreme open-stance slides",
        "topic_vi": "giảm thiểu chấn thương cơ khép trong trượt tư thế mở cực đoan",
        "mech_en": "Extreme open-stance sliding places the adductor complex under **high eccentric load at long muscle lengths**, the position where strain injuries occur. Mitigation requires both eccentric adductor strength and control of the hip's abduction angle rather than flexibility alone.",
        "mech_vi": "Trượt ở tư thế mở cực đoan đặt phức hợp cơ khép dưới **tải lệch tâm cao ở độ dài cơ lớn**, đúng vị trí mà chấn thương căng cơ xảy ra. Giảm thiểu đòi hỏi cả sức mạnh lệch tâm của cơ khép lẫn kiểm soát góc dạng hông, chứ không chỉ cần tính dẻo dai.",
        "vars": [
            ["Copenhagen Adductor Strength", "Sức mạnh cơ khép bài Copenhagen", "hold 30-45 s per side"],
            ["Maximum Slide Abduction Angle", "Góc dạng tối đa khi trượt", "42-52 degrees"],
            ["Adductor Eccentric Capacity", "Năng lực lệch tâm cơ khép", "over 3.0 Nm/kg"],
        ],
        "subs": [
            ["Injury Mechanism at Long Muscle Length", "Cơ Chế Chấn Thương Ở Độ Dài Cơ Lớn",
             "Adductor strain typically occurs during rapid abduction with an external force, precisely the situation created by an extreme open-stance slide. Strength measured at short lengths does not predict this risk; eccentric capacity at long lengths does, which is why the Copenhagen protocol is the standard assessment.",
             "Căng cơ khép thường xảy ra trong pha dạng nhanh kèm lực bên ngoài, đúng tình huống mà một cú trượt tư thế mở cực đoan tạo ra. Sức mạnh đo ở độ dài ngắn không dự báo được nguy cơ này; năng lực lệch tâm ở độ dài lớn thì dự báo được, đó là lý do bài Copenhagen là phép đánh giá chuẩn."],
            ["Progressive Adductor Loading", "Nạp Tải Cơ Khép Tiến Triển",
             "The Copenhagen adductor exercise progresses from a short-lever knee-supported version to a long-lever unsupported version over 8-12 weeks, reducing adductor injury rates substantially in sport populations. Progression is governed by the ability to hold the top position without pelvic drop.",
             "Bài tập cơ khép Copenhagen tiến triển từ phiên bản đòn ngắn có gối tựa sang phiên bản đòn dài không tựa trong 8-12 tuần, làm giảm đáng kể tỷ lệ chấn thương cơ khép ở các nhóm vận động viên. Tiến triển được điều khiển bởi khả năng giữ vị trí cao nhất mà không để khung chậu sụp."],
        ],
        "steps": [
            ["Assess Before Loading", "Test a 30-45 s Copenhagen hold per side; if the pelvis drops, the athlete is not ready for the long-lever version."],
            ["Load the Adductors Twice Weekly Year-Round", "Adductor capacity decays quickly without maintenance; two short exposures per week preserve it during competition blocks."],
            ["Đánh Giá Trước Khi Nạp Tải", "Kiểm tra giữ tư thế Copenhagen 30-45 giây mỗi bên; nếu khung chậu sụp, vận động viên chưa sẵn sàng cho phiên bản đòn dài."],
            ["Nạp Tải Cơ Khép Hai Lần Mỗi Tuần Quanh Năm", "Năng lực cơ khép suy giảm nhanh nếu không duy trì; hai lần ngắn mỗi tuần bảo tồn nó trong các khối thi đấu."],
        ],
        "errs": [
            ["Relying on static stretching for adductor protection", "Flexibility is assumed to equal injury resilience", "Strain risk is unchanged because eccentric capacity is not addressed", "Add twice-weekly Copenhagen progressions and track hold time rather than stretch range",
             "Chỉ dựa vào giãn tĩnh để bảo vệ cơ khép", "Tính dẻo dai được giả định tương đương khả năng chống chấn thương", "Nguy cơ căng cơ không đổi vì năng lực lệch tâm không được giải quyết", "Thêm các bước tiến triển Copenhagen hai lần mỗi tuần và theo dõi thời gian giữ thay vì biên độ giãn"],
            ["Sliding at maximal abduction throughout a match", "Court coverage is prioritised over hip position control", "Adductor load accumulates at long lengths and fails late in the match", "Cap slide abduction at 42-52 degrees and rehearse controlled deceleration after the slide",
             "Trượt ở mức dạng tối đa suốt trận", "Khả năng bao quát sân được ưu tiên hơn kiểm soát vị thế hông", "Tải cơ khép tích lũy ở độ dài lớn và đổ vỡ vào cuối trận", "Giới hạn góc dạng khi trượt ở 42-52 độ và tập kiểm soát giảm tốc sau khi trượt"],
        ],
        "drills": [
            ["Copenhagen Progression", "Short-lever to long-lever holds, 3 x 20-45 s per side", "Tiến Triển Copenhagen", "Giữ từ đòn ngắn tới đòn dài, 3 x 20-45 giây mỗi bên"],
            ["Slide Deceleration Control", "Slide then recover to a balanced stance within 0.8 s", "Kiểm Soát Giảm Tốc Sau Trượt", "Trượt rồi hồi phục về tư thế thăng bằng trong 0,8 giây"],
        ],
    },
    "183": {
        "topic_en": "wrist flexor-pronator tendinopathy rehabilitation",
        "topic_vi": "phục hồi bệnh gân cơ gấp - sấp cổ tay",
        "mech_en": "The flexor-pronator mass absorbs the **whip deceleration of the serve and the eccentric load of the forehand**, which is why medial wrist and elbow symptoms appear in players who serve or hit heavy topspin at high volume. Rehabilitation requires progressive eccentric loading of pronation and wrist flexion, not immobilisation.",
        "mech_vi": "Khối cơ gấp - sấp hấp thụ **pha giảm tốc của động tác vung giao bóng và tải lệch tâm của cú forehand**, đó là lý do các triệu chứng ở phía trong cổ tay và khuỷu xuất hiện ở những người giao bóng hoặc đánh topspin nặng với khối lượng lớn. Phục hồi đòi hỏi nạp tải lệch tâm tiến triển cho động tác sấp và gập cổ tay, không phải bất động.",
        "vars": [
            ["Eccentric Pronation Load", "Tải sấp lệch tâm", "progressive 0.5-2.0 kg"],
            ["Grip Strength Symmetry", "Đối xứng sức mạnh nắm", "within 10% of contralateral"],
            ["Serve Volume Ceiling", "Trần khối lượng giao bóng", "cap at 200 serves/week while symptomatic"],
        ],
        "subs": [
            ["Anatomy of the Flexor-Pronator Origin", "Giải Phẫu Nguyên Ủy Cơ Gấp - Sấp",
             "The flexor carpi ulnaris and pronator teres share a common origin at the medial epicondyle and are the primary decelerators of the whip phase. Their eccentric load during a serve is estimated at 1.5-2.5 times the load carried during acceleration, which explains why symptoms appear during follow-through rather than during the swing itself.",
             "Cơ gấp cổ tay trụ và cơ sấp tròn có nguyên ủy chung tại mỏm trên lồi cầu trong và là những cơ giảm tốc chính trong pha vung. Tải lệch tâm của chúng trong động tác giao bóng ước tính 1,5-2,5 lần tải trong pha tăng tốc, điều này giải thích vì sao triệu chứng xuất hiện trong pha theo đà thay vì trong chính động tác vung."],
            ["Rehabilitation Progression", "Tiến Trình Phục Hồi",
             "The progression runs from isometric holds, to slow eccentric pronation, to controlled concentric-eccentric pairs, and finally to integrative serve repetitions at reduced volume. Each stage requires 24-hour symptom stability before the next is introduced.",
             "Tiến trình đi từ giữ đẳng trường, tới sấp lệch tâm chậm, tới các cặp đồng tâm - lệch tâm có kiểm soát, và cuối cùng là các lần lặp giao bóng tích hợp ở khối lượng giảm. Mỗi giai đoạn đòi hỏi triệu chứng ổn định trong 24 giờ trước khi đưa giai đoạn kế tiếp vào."],
        ],
        "steps": [
            ["Establish 24-Hour Symptom Stability", "No stage progresses unless symptoms are stable within 24 hours of the previous session."],
            ["Cap Serve Volume During Rehabilitation", "Hold serve volume at or below 200 per week until grip strength symmetry returns within 10%."],
            ["Thiết Lập Ổn Định Triệu Chứng Trong 24 Giờ", "Không giai đoạn nào tiến triển trừ khi triệu chứng ổn định trong 24 giờ sau buổi trước."],
            ["Giới Hạn Khối Lượng Giao Bóng Trong Phục Hồi", "Giữ khối lượng giao bóng ở mức 200 cú mỗi tuần hoặc thấp hơn cho tới khi đối xứng sức mạnh nắm trở lại trong 10%."],
        ],
        "errs": [
            ["Immobilising the wrist until pain resolves", "Pain is treated as a signal for complete rest", "Flexor-pronator capacity falls and symptoms return within weeks of resuming play", "Replace immobilisation with progressive isometric and eccentric loading while capping serve volume",
             "Bất động cổ tay cho tới khi hết đau", "Đau được coi là tín hiệu cần nghỉ hoàn toàn", "Năng lực cơ gấp - sấp giảm và triệu chứng tái phát trong vài tuần sau khi trở lại thi đấu", "Thay bất động bằng nạp tải đẳng trường và lệch tâm tiến triển, đồng thời giới hạn khối lượng giao bóng"],
            ["Returning to full serve volume after symptom relief", "Absence of pain is treated as readiness", "Symptoms recur with a heavier load than the first episode", "Hold serve volume at 50-60% for one week after symptoms resolve and verify grip symmetry",
             "Trở lại khối lượng giao bóng đầy đủ sau khi hết triệu chứng", "Việc hết đau được coi là sẵn sàng", "Triệu chứng tái phát với tải nặng hơn đợt đầu", "Giữ khối lượng giao bóng ở 50-60% trong một tuần sau khi triệu chứng hết và kiểm chứng đối xứng sức mạnh nắm"],
        ],
        "drills": [
            ["Eccentric Pronation", "3 x 12 with a 0.5-2.0 kg hammer, 3 s lowering phase", "Sấp Lệch Tâm", "3 x 12 với búa 0,5-2,0 kg, pha hạ 3 giây"],
            ["Wrist Flexion Isometric", "5 x 30 s at 60% effort", "Gập Cổ Tay Đẳng Trường", "5 x 30 giây ở 60% nỗ lực"],
        ],
    },
    "184": {
        "topic_en": "diaphragmatic breathing and parasympathetic reset protocols",
        "topic_vi": "thở cơ hoành và phác đồ khôi phục phó giao cảm",
        "mech_en": "Slow diaphragmatic breathing at **six breaths per minute** maximises respiratory sinus arrhythmia and shifts autonomic balance toward parasympathetic dominance within 2-5 minutes. The practical value is a measurable reduction in heart rate and an increase in heart-rate variability that can be used immediately before serving.",
        "mech_vi": "Thở cơ hoành chậm ở **sáu nhịp mỗi phút** tối đa hóa loạn nhịp xoang hô hấp và dịch chuyển cân bằng tự chủ về phía phó giao cảm trong vòng 2-5 phút. Giá trị thực tiễn là mức giảm nhịp tim đo được và mức tăng biến thiên nhịp tim có thể được dùng ngay trước khi giao bóng.",
        "vars": [
            ["Breathing Rate", "Nhịp thở", "6 breaths per minute"],
            ["Inhale to Exhale Ratio", "Tỷ lệ hít vào trên thở ra", "1:1.5 to 1:2"],
            ["Heart Rate Reduction", "Mức giảm nhịp tim", "8-15 bpm within 3 min"],
        ],
        "subs": [
            ["Respiratory Sinus Arrhythmia and Vagal Tone", "Loạn Nhịp Xoang Hô Hấp & Trương Lực Phế Vị",
             "Heart rate oscillates with respiration, accelerating on inhalation and decelerating on exhalation. Breathing at the individual resonance frequency - typically 5.5-6.5 breaths per minute - maximises that oscillation and produces the largest short-term increase in vagal tone measurable without equipment.",
             "Nhịp tim dao động theo hô hấp, tăng khi hít vào và giảm khi thở ra. Thở ở tần số cộng hưởng của từng cá nhân - thường 5,5-6,5 nhịp mỗi phút - tối đa hóa dao động đó và tạo ra mức tăng trương lực phế vị ngắn hạn lớn nhất có thể đo mà không cần thiết bị."],
            ["Application Windows in Competition", "Các Cửa Sổ Ứng Dụng Trong Thi Đấu",
             "Three windows matter: the 60-90 s changeover, the 20-25 s between points, and the 60 s before a service game. Using the protocol in all three windows reduces accumulated sympathetic load without any cost to activation, provided the exhale is longer than the inhale.",
             "Ba cửa sổ quan trọng: khoảng đổi sân 60-90 giây, 20-25 giây giữa các điểm, và 60 giây trước một game giao bóng. Dùng phác đồ ở cả ba cửa sổ làm giảm tải giao cảm tích lũy mà không mất chi phí hoạt hóa, miễn là pha thở ra dài hơn pha hít vào."],
        ],
        "steps": [
            ["Find the Resonance Rate", "Test 5.0-6.5 breaths per minute and select the rate that produces the largest heart-rate oscillation."],
            ["Extend the Exhale, Not the Inhale", "Emphasise a longer exhale; inhale-driven breathing increases arousal rather than reducing it."],
            ["Tìm Tần Số Cộng Hưởng", "Thử từ 5,0-6,5 nhịp mỗi phút và chọn tần số tạo ra dao động nhịp tim lớn nhất."],
            ["Kéo Dài Pha Thở Ra, Không Kéo Dài Pha Hít Vào", "Nhấn mạnh pha thở ra dài hơn; kiểu thở do hít vào làm tăng kích thích thay vì giảm nó."],
        ],
        "errs": [
            ["Breathing fast and deep to relax", "Depth is confused with slowness", "Sympathetic arousal increases and heart rate rises", "Target six breaths per minute with an exhale longer than the inhale and verify the heart-rate response",
             "Thở nhanh và sâu để thư giãn", "Độ sâu bị nhầm với độ chậm", "Kích thích giao cảm tăng và nhịp tim tăng", "Nhắm sáu nhịp mỗi phút với pha thở ra dài hơn pha hít vào và kiểm chứng đáp ứng nhịp tim"],
            ["Using the protocol only after the match", "Recovery is scheduled after rather than during competition", "Sympathetic load accumulates across the match and cannot be discharged afterwards", "Apply the protocol at changeovers, between points, and before service games",
             "Chỉ dùng phác đồ sau trận", "Phục hồi được sắp sau thay vì trong khi thi đấu", "Tải giao cảm tích lũy suốt trận và không thể xả hết sau đó", "Áp dụng phác đồ ở lần đổi sân, giữa các điểm, và trước các game giao bóng"],
        ],
        "drills": [
            ["Resonance Breathing", "10 min at 6 breaths per minute with a 4 s in and 6 s out pattern", "Thở Cộng Hưởng", "10 phút ở 6 nhịp mỗi phút với nhịp 4 giây vào và 6 giây ra"],
            ["Changeover Reset", "90 s applied breathing protocol at every changeover", "Khôi Phục Ở Đổi Sân", "Phác đồ thở 90 giây ở mọi lần đổi sân"],
        ],
    },
    "185": {
        "topic_en": "pre-match dynamic mobility priming",
        "topic_vi": "chuẩn bị di động động trước trận",
        "mech_en": "Pre-match priming must raise **muscle temperature, joint range, and neural activation** simultaneously, which static stretching cannot do. The practical structure is progressive, movement-specific, and completed within 20-25 minutes so that the athlete arrives at the first point warm rather than fatigued.",
        "mech_vi": "Chuẩn bị trước trận phải đồng thời nâng **nhiệt độ cơ, biên độ khớp và hoạt hóa thần kinh**, điều mà giãn tĩnh không làm được. Cấu trúc thực tiễn là tiến triển, đặc thù theo động tác, và hoàn thành trong 20-25 phút để vận động viên bước vào điểm đầu tiên ở trạng thái đã ấm thay vì đã mệt.",
        "vars": [
            ["Priming Duration", "Thời lượng chuẩn bị", "20-25 min"],
            ["Muscle Temperature Rise", "Mức tăng nhiệt độ cơ", "2-3 degrees Celsius"],
            ["Neural Priming Volume", "Khối lượng mồi thần kinh", "12-20 high-quality reps"],
        ],
        "subs": [
            ["Three-Phase Structure", "Cấu Trúc Ba Pha",
             "The structure is general elevation, specific mobilisation, and neural priming. Skipping the elevation phase produces mobilisation on cold tissue; skipping priming produces a slow first three games. The phases are sequential and none is optional.",
             "Cấu trúc gồm nâng nhiệt tổng quát, di động đặc thù, và mồi thần kinh. Bỏ pha nâng nhiệt sẽ di động trên mô lạnh; bỏ pha mồi sẽ tạo ra ba game đầu chậm. Các pha diễn ra tuần tự và không pha nào là tùy chọn."],
            ["Movement-Specific Mobilisation", "Di Động Đặc Thù Theo Động Tác",
             "Mobilisation targets the ranges the match will demand: thoracic rotation for the serve, hip internal and external rotation for the split step, and ankle dorsiflexion for braking. Generic mobility sequences miss the ranges that actually limit tennis performance.",
             "Di động nhắm vào các biên độ mà trận đấu sẽ đòi hỏi: xoay lồng ngực cho động tác giao bóng, xoay trong và xoay ngoài hông cho bước tách, và gập mu chân cho việc hãm. Các chuỗi di động tổng quát bỏ sót đúng những biên độ thực sự giới hạn hiệu suất tennis."],
        ],
        "steps": [
            ["Elevate Before You Mobilise", "Complete 7-9 minutes of progressive general activity before any joint-specific range work."],
            ["Finish With Neural Priming, Not Stretching", "End the routine with 12-20 fast, high-quality reps of a tennis-specific pattern; static stretching at the end of a warm-up measurably reduces power."],
            ["Nâng Nhiệt Trước Khi Di Động", "Hoàn thành 7-9 phút hoạt động tổng quát tiến triển trước mọi bài biên độ theo khớp."],
            ["Kết Thúc Bằng Mồi Thần Kinh, Không Bằng Giãn Cơ", "Kết thúc quy trình bằng 12-20 lần lặp nhanh, chất lượng cao của một mẫu đặc thù tennis; giãn tĩnh ở cuối khởi động làm giảm công suất một cách đo được."],
        ],
        "errs": [
            ["Static stretching as the main warm-up", "Traditional practice is retained without regard to its acute effects", "Power output is reduced 4-8% for up to 60 minutes", "Replace static work with dynamic mobilisation and finish with neural priming",
             "Dùng giãn tĩnh làm khởi động chính", "Thực hành truyền thống được giữ lại mà không xét tới hiệu ứng cấp của nó", "Công suất đầu ra giảm 4-8% trong tới 60 phút", "Thay giãn tĩnh bằng di động động và kết thúc bằng mồi thần kinh"],
            ["Warming up for more than 30 minutes", "The warm-up is treated as a training session", "Glycogen and arousal are spent before the first point", "Cap the routine at 20-25 minutes and keep intensity low until the priming phase",
             "Khởi động hơn 30 phút", "Khởi động được coi như một buổi tập", "Glycogen và mức hoạt hóa bị tiêu hao trước điểm đầu tiên", "Giới hạn quy trình ở 20-25 phút và giữ cường độ thấp cho tới pha mồi"],
        ],
        "drills": [
            ["Three-Phase Priming", "Full 20-25 min routine before every match", "Chuẩn Bị Ba Pha", "Toàn bộ quy trình 20-25 phút trước mỗi trận"],
            ["Neural Priming Block", "15 fast shadow swings and 10 split-step reactions", "Khối Mồi Thần Kinh", "15 lần vung bóng mô phỏng nhanh và 10 phản ứng bước tách"],
        ],
    },
    "186": {
        "topic_en": "post-match metabolic waste flushing protocols",
        "topic_vi": "phác đồ xả chất thải chuyển hóa sau trận",
        "mech_en": "Post-match flushing combines **low-intensity movement, rehydration, and nutritional timing** to accelerate the return to baseline. The window is short: the first 60-90 minutes determine how quickly the next session can be productive, and passive recovery in that window has a measurable cost.",
        "mech_vi": "Xả chất thải sau trận kết hợp **vận động cường độ thấp, bù nước và định thời dinh dưỡng** để tăng tốc trở về mức nền. Cửa sổ rất ngắn: 60-90 phút đầu quyết định buổi tập kế tiếp có thể hiệu quả nhanh tới đâu, và phục hồi thụ động trong cửa sổ đó có một chi phí đo được.",
        "vars": [
            ["Flush Movement Duration", "Thời lượng vận động xả", "10-15 min"],
            ["Fluid Replacement Target", "Mục tiêu bù dịch", "125-150% of loss"],
            ["Protein Dose", "Liều protein", "0.3 g/kg"],
        ],
        "subs": [
            ["The Post-Exercise Window", "Cửa sổ sau vận động",
             "Glycogen resynthesis, muscle protein synthesis, and plasma volume restoration all proceed fastest in the first 60-90 minutes. The window does not close abruptly, but the rate of recovery declines, so delaying intake beyond two hours meaningfully extends the time to full readiness.",
             "Tái tổng hợp glycogen, tổng hợp protein cơ và phục hồi thể tích huyết tương đều diễn ra nhanh nhất trong 60-90 phút đầu. Cửa sổ không đóng đột ngột, nhưng tốc độ phục hồi giảm xuống, nên trì hoãn nạp quá hai giờ sẽ kéo dài đáng kể thời gian tới trạng thái sẵn sàng đầy đủ."],
            ["Composition of the Flush Protocol", "Thành Phần Của Phác Đồ Xả",
             "The protocol combines 10-15 minutes of conversational-pace movement, fluid replacement at 125-150% of measured loss with sodium, 0.3 g per kilogram of protein, and 1.0-1.2 g per kilogram of carbohydrate for sessions above 90 minutes.",
             "Phác đồ kết hợp 10-15 phút vận động ở mức nói chuyện được, bù dịch ở 125-150% lượng mất đo được kèm natri, 0,3 g protein mỗi kilôgam, và 1,0-1,2 g carbohydrate mỗi kilôgam cho các buổi trên 90 phút."],
        ],
        "steps": [
            ["Move First, Then Drink", "Begin low-intensity movement before fluid intake; movement restores circulation and improves absorption."],
            ["Replace 125-150% of Fluid Loss", "Replace more than was lost because ongoing urine output continues; include sodium to retain the volume."],
            ["Vận Động Trước, Uống Sau", "Bắt đầu vận động cường độ thấp trước khi nạp dịch; vận động phục hồi tuần hoàn và cải thiện hấp thụ."],
            ["Bù 125-150% Lượng Dịch Đã Mất", "Bù nhiều hơn lượng đã mất vì quá trình bài tiết nước tiểu vẫn tiếp diễn; bao gồm natri để giữ thể tích."],
        ],
        "errs": [
            ["Sitting passively for two hours after a match", "Recovery is deferred until after travel and meals", "The next session begins from a partially recovered state", "Complete the flush protocol within 60 minutes of the final point and log compliance",
             "Ngồi thụ động hai giờ sau trận", "Phục hồi bị hoãn cho tới sau khi di chuyển và ăn uống", "Buổi tập kế tiếp bắt đầu từ trạng thái phục hồi một phần", "Hoàn thành phác đồ xả trong vòng 60 phút sau điểm cuối và ghi lại mức tuân thủ"],
            ["Replacing fluid with water only", "Sodium losses are not replaced", "Plasma volume restoration is incomplete and symptoms of light-headedness persist", "Include 500-1,000 mg of sodium per litre in post-match fluids",
             "Chỉ bù dịch bằng nước lọc", "Lượng natri mất đi không được bù", "Phục hồi thể tích huyết tương không đầy đủ và triệu chứng chóng mặt kéo dài", "Bổ sung 500-1.000 mg natri mỗi lít trong dịch uống sau trận"],
        ],
        "drills": [
            ["Post-Match Flush", "12 min easy movement, then fluid and protein within 60 min", "Xả Sau Trận", "12 phút vận động nhẹ, rồi nạp dịch và protein trong vòng 60 phút"],
            ["Rehydration Log", "Track body mass before and after and match 125-150%", "Nhật Ký Bù Nước", "Theo dõi khối lượng cơ thể trước và sau và bù 125-150%"],
        ],
    },
}
