# -*- coding: utf-8 -*-
"""Per-article knowledge data, articles 151-156."""

DATA = {
    "151": {
        "topic_en": "heavy slice as a temporal anchor",
        "topic_vi": "slice nặng như một neo thời gian",
        "mech_en": "A heavy slice is not a defensive ball; it is a **clock manipulator**. Backspin lowers the ball's trajectory, reduces its post-bounce velocity by 25-40% compared with topspin of the same initial speed, and forces the opponent to generate their own pace from a low contact point. The result is a shortening of the opponent's usable preparation window and a lengthening of their recovery time.",
        "mech_vi": "Slice nặng không phải một quả bóng phòng thủ; nó là một **công cụ điều khiển đồng hồ**. Xoáy ngược làm hạ quỹ đạo bóng, giảm tốc độ sau khi nảy 25-40% so với topspin có cùng tốc độ ban đầu, và buộc đối thủ phải tự tạo lực từ một điểm tiếp xúc thấp. Kết quả là cửa sổ chuẩn bị khả dụng của đối thủ bị rút ngắn và thời gian hồi vị của họ bị kéo dài.",
        "vars": [
            ["Post-Bounce Velocity Retention", "Mức giữ tốc độ sau khi nảy", "58-72%"],
            ["Bounce Height Suppression", "Mức hạ độ cao nảy", "0.25-0.45 m below topspin"],
            ["Opponent Preparation Time Added", "Thời gian chuẩn bị cộng thêm cho đối thủ", "60-120 ms"],
        ],
        "subs": [
            ["Backspin Aerodynamics and the Low Contact Problem", "Khí Động Học Xoáy Ngược & Bài Toán Tiếp Xúc Thấp",
             "Backspin generates a downward Magnus component, so the ball descends earlier and stays lower after the bounce. The opponent must then flex the knees 10-20 degrees more than usual and lift the ball with a steeper racket path, which costs both preparation time and, under fatigue, technical consistency.",
             "Xoáy ngược tạo thành phần Magnus hướng xuống, nên bóng rơi xuống sớm hơn và giữ độ cao thấp hơn sau khi nảy. Đối thủ sau đó phải gập gối thêm 10-20 độ so với bình thường và nâng bóng bằng đường vợt dốc hơn, điều này làm mất cả thời gian chuẩn bị lẫn, khi mệt, tính nhất quán kỹ thuật."],
            ["Temporal Anchoring: Slowing the Exchange Without Losing It", "Neo Thời Gian: Làm Chậm Pha Bóng Mà Không Thua Nó",
             "The slice's tactical purpose is to reset a rally the opponent is winning without conceding court position. Used as every third or fourth ball, it breaks the opponent's aggressive cadence, buys 0.4-0.8 s of recovery, and creates the height and time needed to re-establish an offensive position.",
             "Mục đích chiến thuật của slice là đặt lại một pha bóng mà đối thủ đang thắng mà không nhường vị trí trên sân. Được dùng như quả bóng thứ ba hoặc thứ tư, nó phá nhịp tấn công của đối thủ, mua 0,4-0,8 giây hồi phục, và tạo độ cao cùng thời gian cần thiết để tái lập thế tấn công."],
        ],
        "steps": [
            ["Commit the Slice Before the Ball Arrives", "The slice decision must be made at the opponent's contact; a slice improvised at the last moment becomes a floating ball with no penetration."],
            ["Drive Through, Do Not Chop Down", "Racket path travels forward 60-70% and downward 30-40%; a purely downward path produces backspin without forward penetration and the ball sits up."],
            ["Cam Kết Cú Slice Trước Khi Bóng Tới", "Quyết định slice phải được đưa ra ngay lúc đối thủ tiếp xúc; một cú slice ứng biến ở phút cuối sẽ trở thành bóng bổng không có độ xuyên."],
            ["Đẩy Xuyên Tới, Không Chặt Xuống", "Đường vợt đi tới 60-70% và đi xuống 30-40%; đường chỉ đi xuống tạo xoáy ngược mà không có độ xuyên tới và bóng sẽ nằm chờ."],
        ],
        "errs": [
            ["Using the slice as a default rather than a tool", "Comfort with the low-risk shot replaces tactical intention", "The opponent learns the pattern, steps in, and attacks the short ball", "Limit the slice to one ball in three or four, and always pair it with a declared follow-up pattern",
             "Dùng slice như mặc định thay vì như công cụ", "Sự thoải mái với cú đánh ít rủi ro thay thế ý định chiến thuật", "Đối thủ học được mẫu, bước vào trong và tấn công bóng ngắn", "Giới hạn slice ở một trong ba hoặc bốn quả bóng, và luôn ghép nó với một mẫu tiếp theo đã tuyên bố"],
            ["Chopping down instead of driving through", "The intention is to maximize spin rather than to control the ball's forward travel", "The ball lands short, sits up, and invites an immediate attack", "Maintain 60-70% forward racket travel at contact; depth beyond 5.5 m is the pass criterion for every slice",
             "Chặt xuống thay vì đẩy xuyên tới", "Ý định là tối đa hóa xoáy thay vì kiểm soát chiều đi của bóng", "Bóng rơi ngắn, nằm chờ, và mời một cú tấn công tức thời", "Giữ 60-70% quãng đường vợt đi tới ở điểm tiếp xúc; chiều sâu vượt 5,5 m là tiêu chí đạt cho mọi cú slice"],
        ],
        "drills": [
            ["Slice Depth Ladder", "20 consecutive slices; every ball must land beyond 5.5 m", "Thang Chiều Sâu Slice", "20 cú slice liên tiếp; mọi quả phải rơi xa hơn 5,5 m"],
            ["Anchor Pattern Set", "Rally with a rule: every third ball must be a slice followed by an approach", "Set Mẫu Neo", "Đánh qua lại với luật: mỗi quả thứ ba phải là slice kèm một pha lên lưới"],
        ],
    },
    "152": {
        "topic_en": "I-formation mechanics in elite doubles",
        "topic_vi": "cơ học đội hình chữ I trong đôi cao cấp",
        "mech_en": "The I-formation removes the server's most predictable information leak - the partner's starting position - by placing both players on the center line before the serve. The returner must then read a **two-body problem** instead of a single cue, which raises their decision latency by 40-90 ms and makes the poach unpredictable.",
        "mech_vi": "Đội hình chữ I loại bỏ rò rỉ thông tin dễ đoán nhất của người phát bóng - vị trí xuất phát của đồng đội - bằng cách đặt cả hai người trên đường giữa trước khi phát. Người đỡ bóng sau đó phải đọc một **bài toán hai thân người** thay vì một tín hiệu duy nhất, điều này làm tăng độ trễ quyết định của họ 40-90 mili giây và làm cho pha cắt bóng trở nên không thể đoán trước.",
        "vars": [
            ["Server-Partner Lateral Separation", "Khoảng cách ngang giữa người phát và đồng đội", "1.0-1.6 m"],
            ["Poach Decision Deadline", "Hạn chót quyết định cắt bóng", "before returner contact +80 ms"],
            ["Returner Decision Latency Increase", "Mức tăng độ trễ quyết định của người đỡ", "40-90 ms"],
        ],
        "subs": [
            ["Information Suppression in the I-Formation", "Triệt Tiêu Thông Tin Trong Đội Hình Chữ I",
             "In conventional formations the net player's crouch direction telegraphs the poach. The I-formation removes that cue entirely: both players begin on the center line, and the poaching player's first movement occurs after the serve is struck, leaving the returner only 180-240 ms of usable decision time.",
             "Ở các đội hình thông thường, hướng hạ thấp người của người chơi lưới báo trước pha cắt bóng. Đội hình chữ I loại bỏ hoàn toàn tín hiệu đó: cả hai người bắt đầu trên đường giữa, và động tác đầu tiên của người cắt bóng diễn ra sau khi phát bóng được thực hiện, chỉ để lại cho người đỡ 180-240 mili giây thời gian quyết định khả dụng."],
            ["Serve Target Selection Inside the I", "Chọn Vị Trí Phát Bóng Trong Đội Hình Chữ I",
             "Because both players occupy the middle, wide serves expose the server's own court. The correct target distribution shifts toward the body and the T: 45-55% body, 30-40% T, and under 20% wide, unless the poach is deliberately used as the primary weapon.",
             "Vì cả hai người đều chiếm vị trí giữa sân, những cú phát rộng sẽ để lộ phần sân của chính người phát. Phân bổ mục tiêu đúng dịch chuyển về phía người và điểm T: 45-55% vào người, 30-40% vào T, và dưới 20% ra rộng, trừ khi pha cắt bóng được dùng có chủ đích như vũ khí chính."],
        ],
        "steps": [
            ["Signal Before the Toss", "The poach or hold decision must be signalled before the toss; signalling after the toss gives the returner a free read."],
            ["Split the Court Into Two Responsibilities", "Server covers the sideline-to-center channel after the serve; the poacher covers the cross-court channel and the middle second."],
            ["Ra Tín Hiệu Trước Khi Tung Bóng", "Quyết định cắt bóng hay giữ vị trí phải được ra tín hiệu trước khi tung bóng; ra tín hiệu sau khi tung sẽ cho người đỡ một lần đọc miễn phí."],
            ["Chia Sân Thành Hai Trách Nhiệm", "Người phát bóng phụ trách hành lang từ vạch biên tới giữa sau khi phát; người cắt bóng phụ trách hành lang chéo sân và khoảng giữa thứ hai."],
        ],
        "errs": [
            ["Signalling the poach too late", "The signal habit was built in conventional formations", "The returner reads the movement and passes down the open line", "Move the signal earlier until it occurs before the toss in 90% of points; verify with video",
             "Ra tín hiệu cắt bóng quá muộn", "Thói quen ra tín hiệu được hình thành ở đội hình thông thường", "Người đỡ đọc được động tác và đánh xuyên xuống đường biên trống", "Dịch tín hiệu sớm hơn cho tới khi nó xuất hiện trước khi tung bóng trong 90% số điểm; kiểm chứng bằng video"],
            ["Both players covering the same channel", "Responsibilities are assumed rather than declared", "The middle is left open and a routine return becomes a winner", "Declare channel responsibility out loud before every point for one full set",
             "Cả hai người cùng che một hành lang", "Trách nhiệm được giả định thay vì được tuyên bố", "Khoảng giữa bị bỏ trống và một cú đỡ bình thường trở thành winner", "Tuyên bố trách nhiệm hành lang thành lời trước mỗi điểm trong một set đầy đủ"],
        ],
        "drills": [
            ["I-Formation Poach Reps", "20 serves with alternating poach and hold signals; count returner errors induced", "Hiệp Cắt Bóng Đội Hình Chữ I", "20 cú phát với tín hiệu cắt và giữ luân phiên; đếm số lỗi gây ra cho người đỡ"],
            ["Channel Declaration Set", "Play a 4-game set declaring channel responsibility aloud each point", "Set Tuyên Bố Hành Lang", "Chơi set 4 game, tuyên bố trách nhiệm hành lang thành lời mỗi điểm"],
        ],
    },
    "153": {
        "topic_en": "Australian formation strategy and serve placement",
        "topic_vi": "chiến thuật đội hình Australian và vị trí phát bóng",
        "mech_en": "The Australian formation places the net player on the same side as the server, which eliminates the cross-court return as a safe option and pushes the returner into a **low-percentage down-the-line channel**. It converts the return from a neutral rally starter into a decision under constraint, and the constraint is geometric rather than psychological.",
        "mech_vi": "Đội hình Australian đặt người chơi lưới cùng phía với người phát bóng, điều này loại bỏ cú đỡ chéo sân như một phương án an toàn và đẩy người đỡ vào một **hành lang dọc biên có tỷ lệ thấp**. Nó chuyển cú đỡ từ một pha khởi đầu trung hòa thành một quyết định dưới ràng buộc, và ràng buộc đó mang tính hình học chứ không phải tâm lý.",
        "vars": [
            ["Net Player Lateral Position", "Vị trí ngang của người chơi lưới", "0.4-0.8 m from center, server's side"],
            ["Available Return Channel", "Hành lang đỡ bóng khả dụng", "1.6-2.2 m width"],
            ["Return Error Rate Increase", "Mức tăng tỷ lệ lỗi đỡ bóng", "12-22%"],
        ],
        "subs": [
            ["Geometric Constraint of the Down-the-Line Channel", "Ràng Buộc Hình Học Của Hành Lang Dọc Biên",
             "With the net player positioned on the server's side, the cross-court return passes directly through the poacher's zone. The remaining down-the-line channel is 1.6-2.2 m wide, requires the returner to hit over the highest part of the net, and lands into the longest recovery distance on the court.",
             "Với người chơi lưới đặt ở phía của người phát bóng, cú đỡ chéo sân đi thẳng qua vùng của người cắt bóng. Hành lang dọc biên còn lại rộng 1,6-2,2 m, buộc người đỡ phải đánh qua phần cao nhất của lưới, và rơi vào khoảng cách hồi vị dài nhất trên sân."],
            ["Serve Placement That Makes the Formation Work", "Vị Trí Phát Bóng Làm Cho Đội Hình Vận Hành",
             "The formation only functions when the serve is placed to reduce the returner's angle: 55-65% of serves should go to the T or the body, because a wide serve re-opens the cross-court channel that the formation was designed to close.",
             "Đội hình chỉ vận hành khi cú phát được đặt để giảm góc của người đỡ: 55-65% số cú phát nên đi vào điểm T hoặc vào người, vì một cú phát rộng sẽ mở lại hành lang chéo sân mà đội hình được thiết kế để đóng."],
        ],
        "steps": [
            ["Confirm the Formation Before the First Serve", "The formation must be declared before the first serve of the game, not switched mid-game as a surprise; predictability of role is what makes the poach decisive."],
            ["Serve to the T or Body", "At least six of every ten serves in this formation target the T or body; wide serves are the exception and must be followed by a declared cover pattern."],
            ["Xác Nhận Đội Hình Trước Cú Phát Đầu", "Đội hình phải được tuyên bố trước cú phát đầu của game, không đổi giữa game như một bất ngờ; tính dự đoán được của vai trò chính là thứ làm pha cắt bóng mang tính quyết định."],
            ["Phát Vào Điểm T Hoặc Vào Người", "Ít nhất sáu trong mười cú phát ở đội hình này nhắm vào T hoặc vào người; phát rộng là ngoại lệ và phải kèm một mẫu che chắn đã tuyên bố."],
        ],
        "errs": [
            ["Using the Australian formation with wide serves", "Placement habits are unchanged when the formation changes", "The cross-court channel reopens and the net player is passed at will", "Restrict wide serves to under 20% in this formation and pre-declare the cover pattern for each one",
             "Dùng đội hình Australian với những cú phát rộng", "Thói quen đặt bóng không thay đổi khi đội hình thay đổi", "Hành lang chéo sân mở lại và người chơi lưới bị đánh xuyên tùy ý", "Giới hạn phát rộng dưới 20% ở đội hình này và tuyên bố trước mẫu che chắn cho mỗi cú"],
            ["Net player drifting back to the conventional position", "Comfort and habit pull the player toward a familiar starting point", "The formation silently reverts and the constraint disappears", "Mark the Australian starting position on the court with tape during practice until it becomes automatic",
             "Người chơi lưới trôi về vị trí thông thường", "Sự thoải mái và thói quen kéo người chơi về điểm xuất phát quen thuộc", "Đội hình âm thầm trở lại ban đầu và ràng buộc biến mất", "Đánh dấu vị trí xuất phát Australian trên sân bằng băng dính khi tập cho tới khi nó trở thành tự động"],
        ],
        "drills": [
            ["Australian Serve-and-Cover", "Serve to the T 10 times with the declared cover pattern; log returner outcomes", "Phát Và Che Chắn Australian", "Phát vào T 10 lần với mẫu che chắn đã tuyên bố; ghi lại kết quả của người đỡ"],
            ["Down-the-Line Discipline", "Returner must play down-the-line only; count errors induced over 20 returns", "Kỷ Luật Dọc Biên", "Người đỡ chỉ được đánh dọc biên; đếm số lỗi gây ra qua 20 cú đỡ"],
        ],
    },
    "154": {
        "topic_en": "target scouting and mechanical weakness identification",
        "topic_vi": "trinh sát mục tiêu và nhận diện điểm yếu cơ học",
        "mech_en": "Scouting is the conversion of observation into a **short list of mechanical liabilities**. The objective is not to describe the opponent but to identify the two or three movements where their kinetic chain breaks down, because those are the only targets that remain exploitable under pressure and fatigue.",
        "mech_vi": "Trinh sát là việc chuyển quan sát thành một **danh sách ngắn các điểm yếu cơ học**. Mục tiêu không phải là mô tả đối thủ mà là nhận diện hai hoặc ba động tác nơi chuỗi động lực học của họ đổ vỡ, vì đó là những mục tiêu duy nhất còn khai thác được dưới áp lực và mệt mỏi.",
        "vars": [
            ["Observation Sample Required", "Số điểm quan sát cần thiết", "20-30 points"],
            ["Profitable Target Count", "Số mục tiêu khai thác được", "2-3 maximum"],
            ["Prediction Accuracy Threshold", "Ngưỡng độ chính xác dự đoán", "65-75%"],
        ],
        "subs": [
            ["Reading the Kinetic Chain for Breaks", "Đọc Chuỗi Động Lực Học Để Tìm Điểm Đổ Vỡ",
             "A kinetic chain break is visible as a segment that fails to transfer position: the hips stop rotating before the shoulders, the elbow stalls, or the front foot plants with the knee collapsing inward. Each break produces a characteristic ball: short, high, or directionally unpredictable, and the ball type identifies which target is profitable.",
             "Một điểm đổ vỡ trong chuỗi động lực học hiện ra như một phân đoạn không truyền được vị thế: hông ngừng xoay trước vai, khuỷu tay khựng lại, hoặc bàn chân trước đặt xuống với đầu gối sụp vào trong. Mỗi điểm đổ vỡ tạo ra một kiểu bóng đặc trưng: ngắn, cao, hoặc không dự đoán được về hướng, và kiểu bóng đó chỉ ra mục tiêu nào khai thác được."],
            ["Scouting Protocol Under Limited Observation", "Phác Đồ Trinh Sát Khi Ít Cơ Hội Quan Sát",
             "When only a warm-up is available, three probes deliver most of the information: a high heavy ball to the backhand, a short ball to the forehand, and a wide serve to the ad court. Each probe tests a different link, and the responses reveal the weakest one within four to six balls.",
             "Khi chỉ có phần khởi động, ba phép thử mang lại phần lớn thông tin: một bóng cao nặng vào trái tay, một bóng ngắn vào forehand, và một cú phát rộng vào ô ad. Mỗi phép thử kiểm tra một mắt xích khác nhau, và các phản hồi sẽ chỉ ra mắt xích yếu nhất trong vòng bốn tới sáu quả bóng."],
        ],
        "steps": [
            ["Probe Before Committing to a Target", "Test each candidate weakness twice before building the game plan around it; one failure may be luck, two starts to be information."],
            ["Record in Four Items Maximum", "The final profile must contain no more than four items; longer profiles are not recalled at 4-4 in the third set."],
            ["Thử Nghiệm Trước Khi Cam Kết Mục Tiêu", "Kiểm tra mỗi điểm yếu tiềm năng hai lần trước khi xây kế hoạch trận quanh nó; một lần thất bại có thể là may mắn, hai lần bắt đầu là thông tin."],
            ["Ghi Nhận Tối Đa Bốn Mục", "Hồ sơ cuối cùng không được vượt quá bốn mục; hồ sơ dài hơn sẽ không được nhớ lại ở tỷ số 4-4 set thứ ba."],
        ],
        "errs": [
            ["Confusing a technical quirk with a mechanical liability", "Observation focuses on style rather than on chain breaks", "The game plan attacks a shot that is actually reliable under pressure", "Only count a weakness as exploitable if it produces a short, high, or directionally unpredictable ball twice in a row",
             "Nhầm một nét kỹ thuật riêng với một điểm yếu cơ học", "Quan sát tập trung vào phong cách thay vì vào điểm đổ vỡ chuỗi", "Kế hoạch trận tấn công vào một cú đánh thực ra rất đáng tin dưới áp lực", "Chỉ tính một điểm yếu là khai thác được nếu nó tạo ra bóng ngắn, cao, hoặc không dự đoán được về hướng hai lần liên tiếp"],
            ["Over-writing the scouting report", "The report is built for the analyst rather than for the player", "Nothing from the report is recalled during the match", "Cap the profile at four items and rehearse them aloud before the match",
             "Viết báo cáo trinh sát quá dài", "Báo cáo được viết cho chuyên viên phân tích thay vì cho vận động viên", "Không có gì trong báo cáo được nhớ lại trong trận", "Giới hạn hồ sơ ở bốn mục và đọc lại thành lời trước trận"],
        ],
        "drills": [
            ["Three-Probe Scouting", "Probe a partner with three standardized balls and write a four-item profile", "Trinh Sát Ba Phép Thử", "Thử đồng đội bằng ba quả bóng chuẩn hóa và viết hồ sơ bốn mục"],
            ["Profile Recall Drill", "State the four profile items aloud at every changeover for one set", "Bài Nhớ Hồ Sơ", "Đọc bốn mục hồ sơ thành lời ở mỗi lần đổi sân trong một set"],
        ],
    },
    "155": {
        "topic_en": "defending against heavy topspin bullying",
        "topic_vi": "phòng thủ trước lối đánh topspin nặng áp đặt",
        "mech_en": "Heavy topspin bullying works by pushing the contact point above shoulder height, where the returner's available racket path becomes vertical rather than horizontal. Defence therefore requires **reclaiming contact height** - through depth, through early contact, or through a step-back-and-forward rhythm - rather than attempting to out-hit the ball.",
        "mech_vi": "Lối đánh topspin nặng áp đặt hoạt động bằng cách đẩy điểm tiếp xúc lên trên độ cao vai, nơi đường vợt khả dụng của người đỡ trở nên thẳng đứng thay vì nằm ngang. Do đó phòng thủ đòi hỏi **giành lại độ cao tiếp xúc** - thông qua chiều sâu, thông qua tiếp xúc sớm, hoặc thông qua nhịp lùi rồi tiến - thay vì cố đánh mạnh hơn bóng.",
        "vars": [
            ["Contact Height Threshold", "Ngưỡng độ cao tiếp xúc", "below 1.35 m preferred"],
            ["Step-Back Depth", "Độ sâu lùi bước", "0.8-1.4 m behind baseline"],
            ["High-Ball Neutralization Rate", "Tỷ lệ trung hòa bóng cao", "55-65%"],
        ],
        "subs": [
            ["The Shoulder-Height Contact Problem", "Bài Toán Tiếp Xúc Ở Độ Cao Vai",
             "Above 1.35 m the forehand and backhand must be struck with a shortened, more vertical swing, which reduces both available topspin and directional control by 15-30%. Recognising the threshold early allows the defender to choose between stepping back to let the ball descend or stepping in to take it before the rise peaks.",
             "Trên 1,35 m, forehand và backhand phải được đánh bằng động tác thu ngắn và thẳng đứng hơn, điều này làm giảm cả topspin khả dụng lẫn kiểm soát hướng từ 15-30%. Nhận diện sớm ngưỡng này cho phép người phòng thủ chọn giữa lùi lại để bóng hạ xuống hoặc bước vào để đón bóng trước khi độ cao lên đỉnh."],
            ["Height Reclamation Protocols", "Các Phác Đồ Giành Lại Độ Cao",
             "Three legitimate protocols exist: the deep defensive lob to reset the height baseline, the on-the-rise drive that neutralizes before the ball climbs, and the step-back topspin that trades 0.4 s of time for a contact point 0.3-0.5 m lower. The choice depends on the available time, not on preference.",
             "Có ba phác đồ chính đáng: cú lob phòng thủ sâu để đặt lại nền độ cao, cú đánh khi bóng đang lên để trung hòa trước khi bóng leo cao, và cú topspin lùi bước đánh đổi 0,4 giây thời gian lấy điểm tiếp xúc thấp hơn 0,3-0,5 m. Lựa chọn phụ thuộc vào thời gian khả dụng, không phụ thuộc sở thích."],
        ],
        "steps": [
            ["Classify the Ball Before the Bounce", "Decide between taking it on the rise and stepping back at the opponent's contact; deciding after the bounce guarantees a shoulder-height contact."],
            ["Reclaim Depth Before Pace", "The first defensive priority is landing the ball beyond 6.0 m; pace is added only after depth is re-established."],
            ["Phân Loại Bóng Trước Khi Bóng Nảy", "Quyết định giữa đón bóng đang lên và lùi bước ngay lúc đối thủ tiếp xúc; quyết định sau khi bóng nảy đảm bảo một lần tiếp xúc ở độ cao vai."],
            ["Giành Lại Chiều Sâu Trước Tốc Độ", "Ưu tiên phòng thủ đầu tiên là đưa bóng rơi xa hơn 6,0 m; tốc độ chỉ được thêm vào sau khi chiều sâu đã được tái lập."],
        ],
        "errs": [
            ["Trying to out-hit heavy topspin from shoulder height", "Ego response; the defender attempts to match power at an unfavourable contact height", "Error rate doubles and the rally is lost in two shots", "Never attempt an offensive ball above 1.35 m; choose lob, on-the-rise drive, or step-back topspin",
             "Cố đánh mạnh hơn trước topspin nặng từ độ cao vai", "Phản ứng cái tôi; người phòng thủ cố sánh lực ở độ cao tiếp xúc bất lợi", "Tỷ lệ lỗi tăng gấp đôi và pha bóng thua trong hai cú", "Không bao giờ thử cú tấn công ở độ cao trên 1,35 m; chọn lob, đánh khi bóng đang lên, hoặc topspin lùi bước"],
            ["Standing too close to the baseline against heavy spin", "The position was set for a flat-hitting opponent", "Every ball arrives at increasing height and the contact point climbs steadily", "Adopt a step-back depth of 0.8-1.4 m and step forward on the ball to meet it at a controlled height",
             "Đứng quá sát vạch cuối sân trước xoáy nặng", "Vị trí được thiết lập cho một đối thủ đánh phẳng", "Mỗi quả bóng tới ở độ cao tăng dần và điểm tiếp xúc leo lên đều đặn", "Áp dụng độ sâu lùi bước 0,8-1,4 m và tiến vào khi bóng tới để gặp bóng ở độ cao được kiểm soát"],
        ],
        "drills": [
            ["Height Reclamation Set", "Partner feeds heavy topspin; defender must alternate lob, rise, and step-back responses", "Set Giành Lại Độ Cao", "Đồng đội tung topspin nặng; người phòng thủ phải luân phiên phản hồi bằng lob, đánh khi bóng lên, và lùi bước"],
            ["On-the-Rise Neutralization", "20 balls taken before the apex, scored on depth beyond 6 m", "Trung Hòa Khi Bóng Đang Lên", "20 quả bóng đón trước đỉnh, tính điểm theo chiều sâu vượt 6 m"],
        ],
    },
    "156": {
        "topic_en": "counter-strategies against unorthodox players",
        "topic_vi": "chiến lược đối phó với lối chơi phi truyền thống",
        "mech_en": "Unorthodox players - pushers, moonballers, and extreme retrievers - win by **removing the rally structure** that conventional training depends on. Their balls carry no pace to redirect and no rhythm to entrain, so the counter-strategy cannot be technical; it must be an explicit plan that converts their consistency into a liability by changing what consistency costs them.",
        "mech_vi": "Những người chơi phi truyền thống - người đẩy bóng, người đánh bóng trăng, và những tay bám trụ cực đoan - thắng bằng cách **loại bỏ cấu trúc pha bóng** mà huấn luyện thông thường dựa vào. Bóng của họ không mang tốc độ để tái định hướng và không có nhịp để cuốn theo, nên chiến lược đối phó không thể là kỹ thuật; nó phải là một kế hoạch tường minh chuyển sự ổn định của họ thành gánh nặng bằng cách thay đổi cái giá của sự ổn định.",
        "vars": [
            ["Rally Length Ceiling", "Giới hạn độ dài pha bóng", "under 7 shots"],
            ["Net Approach Frequency Target", "Tần suất lên lưới mục tiêu", "1 in 3 points"],
            ["Patience Tolerance Window", "Cửa sổ chịu đựng kiên nhẫn", "9-12 shots before escalation"],
        ],
        "subs": [
            ["Why Conventional Patterns Fail Against Retrievers", "Vì Sao Các Mẫu Thông Thường Thất Bại Trước Tay Bám Trụ",
             "Conventional patterns assume the opponent's ball carries enough pace to be redirected. Against a pusher the incoming ball may arrive at 45-60 km/h with heavy backspin, which means the attacking player must generate 100% of the pace from a low contact point and a 1.2-1.8 m deep position - a structurally low-percentage situation.",
             "Các mẫu thông thường giả định bóng của đối thủ mang đủ tốc độ để tái định hướng. Trước một tay đẩy bóng, bóng tới có thể chỉ 45-60 km/h với xoáy ngược nặng, nghĩa là người tấn công phải tạo 100% tốc độ từ điểm tiếp xúc thấp và vị trí sâu 1,2-1,8 m - một tình huống có tỷ lệ thấp về mặt cấu trúc."],
            ["The Three Counter-Levers", "Ba Đòn Bẩy Đối Phó",
             "Three levers work reliably: **net approach** (converting a rally problem into a volley problem), **height variation** (alternating heavy topspin with a short slice to force movement), and **scoreboard patience** (accepting 9-12 shot rallies and attacking only the 4th or 6th ball that lands short).",
             "Ba đòn bẩy vận hành đáng tin: **lên lưới** (chuyển bài toán pha bóng thành bài toán vô lê), **biến thiên độ cao** (luân phiên topspin nặng với slice ngắn để buộc di chuyển), và **kiên nhẫn theo bảng điểm** (chấp nhận pha bóng 9-12 cú và chỉ tấn công quả thứ tư hoặc thứ sáu rơi ngắn)."],
        ],
        "steps": [
            ["Accept the Rally Length Without Emotional Cost", "Decide before the match that rallies will last 9-12 shots; treating length as failure is the mechanism by which pushers win."],
            ["Attack the Short Ball, Not the Slow Ball", "A slow ball that lands deep is not an attackable ball; the trigger for escalation is landing depth under 5.0 m."],
            ["Chấp Nhận Độ Dài Pha Bóng Không Kèm Chi Phí Cảm Xúc", "Quyết định trước trận rằng các pha bóng sẽ kéo dài 9-12 cú; coi độ dài là thất bại chính là cơ chế mà tay đẩy bóng thắng."],
            ["Tấn Công Bóng Ngắn, Không Tấn Công Bóng Chậm", "Một quả bóng chậm rơi sâu không phải bóng tấn công được; tín hiệu để nâng mức là chiều sâu điểm rơi dưới 5,0 m."],
        ],
        "errs": [
            ["Escalating power against a deep slow ball", "Frustration is interpreted as a tactical signal", "Unforced errors accumulate while the opponent's consistency is untouched", "Set a hard rule: no escalation unless the ball lands inside 5.0 m; log every violation after the set",
             "Tăng lực trước một bóng chậm rơi sâu", "Sự bực bội bị hiểu như một tín hiệu chiến thuật", "Lỗi tự đánh bại tích lũy trong khi sự ổn định của đối thủ không bị ảnh hưởng", "Đặt quy tắc cứng: không nâng mức trừ khi bóng rơi trong vòng 5,0 m; ghi lại mọi vi phạm sau set"],
            ["Avoiding the net because volleys feel uncomfortable", "Technical discomfort is allowed to dictate tactics", "The single most reliable counter-lever is never used", "Commit to one net approach in every three points for two full sets, regardless of outcome",
             "Tránh lên lưới vì vô lê không thoải mái", "Sự không thoải mái kỹ thuật được để chi phối chiến thuật", "Đòn bẩy đối phó đáng tin nhất không bao giờ được dùng", "Cam kết lên lưới một lần trong mỗi ba điểm trong hai set đầy đủ, bất kể kết quả"],
        ],
        "drills": [
            ["Patience Rally Protocol", "Rally to 12 shots with no escalation allowed before shot 9", "Phác Đồ Pha Bóng Kiên Nhẫn", "Đánh qua lại tới 12 cú, không được nâng mức trước cú thứ 9"],
            ["Short-Ball Attack Trigger", "Partner alternates deep slow balls and short balls; attack only the short ones", "Tín Hiệu Tấn Công Bóng Ngắn", "Đồng đội luân phiên bóng chậm sâu và bóng ngắn; chỉ tấn công bóng ngắn"],
        ],
    },
}
