# -*- coding: utf-8 -*-
"""Per-article knowledge data, articles 175-180."""

DATA = {
    "175": {
        "topic_en": "cold-water immersion versus contrast therapy",
        "topic_vi": "ngâm nước lạnh so với liệu pháp đối trạch",
        "mech_en": "Cold-water immersion reduces perceived soreness and inflammatory signalling but **blunts strength and hypertrophy adaptation** if applied within hours of a strength session. Contrast therapy produces smaller physiological effects but avoids that interference, which makes the choice a decision about the session's purpose rather than about comfort.",
        "mech_vi": "Ngâm nước lạnh làm giảm cảm giác đau nhức và tín hiệu viêm nhưng **làm mờ thích nghi sức mạnh và phì đại** nếu được áp dụng trong vài giờ sau buổi tập sức mạnh. Liệu pháp đối trạch tạo ra hiệu ứng sinh lý nhỏ hơn nhưng tránh được sự giao thoa đó, điều này khiến lựa chọn trở thành quyết định về mục đích của buổi tập thay vì về sự thoải mái.",
        "vars": [
            ["Cold Immersion Temperature", "Nhiệt độ ngâm lạnh", "10-15 degrees Celsius"],
            ["Immersion Duration", "Thời lượng ngâm", "8-12 min"],
            ["Contrast Cycle Ratio", "Tỷ lệ chu kỳ đối trạch", "1 min hot : 1 min cold"],
        ],
        "subs": [
            ["Physiological Effects and the Interference Problem", "Hiệu Ứng Sinh Lý & Vấn Đề Giao Thoa",
             "Cold exposure constricts vessels, reduces oedema, and lowers nerve conduction velocity, producing reliable analgesia for 1-3 hours. The same vasoconstriction reduces the delivery of signalling molecules associated with hypertrophy, and studies consistently show attenuated strength gains when immersion follows resistance training.",
             "Tiếp xúc lạnh làm co mạch, giảm phù nề và giảm tốc độ dẫn truyền thần kinh, tạo ra hiệu ứng giảm đau đáng tin trong 1-3 giờ. Cùng sự co mạch đó làm giảm việc cung cấp các phân tử tín hiệu liên quan tới phì đại, và các nghiên cứu cho thấy một cách nhất quán rằng lợi ích sức mạnh bị suy giảm khi ngâm lạnh sau tập kháng lực."],
            ["Selecting the Modality by Session Purpose", "Chọn Phương Thức Theo Mục Đích Buổi Tập",
             "The decision rule is explicit: after a competition or a technical session, cold immersion is appropriate because adaptation to strength is not the target; after a strength or power session, contrast therapy or active recovery preserves the anabolic signal. Applying one modality universally guarantees that half the sessions are treated incorrectly.",
             "Quy tắc quyết định rất tường minh: sau một trận thi đấu hoặc một buổi kỹ thuật, ngâm lạnh là phù hợp vì thích nghi sức mạnh không phải mục tiêu; sau một buổi sức mạnh hoặc công suất, liệu pháp đối trạch hoặc phục hồi chủ động bảo tồn tín hiệu đồng hóa. Áp dụng một phương thức cho mọi trường hợp đảm bảo rằng một nửa số buổi tập bị xử lý sai."],
        ],
        "steps": [
            ["Classify the Session Before Choosing", "Determine whether the session's purpose was adaptation or performance; the modality follows from that classification."],
            ["Keep Immersion Short and Cool, Not Cold and Long", "8-12 minutes at 10-15 degrees Celsius is sufficient; longer or colder exposure adds discomfort without additional benefit."],
            ["Phân Loại Buổi Tập Trước Khi Chọn", "Xác định mục đích buổi tập là thích nghi hay hiệu suất; phương thức được suy ra từ việc phân loại đó."],
            ["Giữ Ngâm Ngắn Và Mát, Không Lạnh Và Dài", "8-12 phút ở 10-15 độ C là đủ; tiếp xúc lâu hơn hoặc lạnh hơn chỉ thêm khó chịu mà không thêm lợi ích."],
        ],
        "errs": [
            ["Using cold immersion after every session", "Recovery is applied as a ritual rather than as a targeted intervention", "Strength and hypertrophy adaptations are chronically blunted", "Reserve cold immersion for competition and technical days; use contrast or active recovery after strength work",
             "Dùng ngâm nước lạnh sau mọi buổi tập", "Phục hồi được áp dụng như một nghi thức thay vì một can thiệp có mục tiêu", "Thích nghi sức mạnh và phì đại bị làm mờ một cách mạn tính", "Dành ngâm lạnh cho ngày thi đấu và ngày kỹ thuật; dùng đối trạch hoặc phục hồi chủ động sau buổi sức mạnh"],
            ["Prolonging immersion to increase the effect", "Dose is assumed to scale linearly with discomfort", "Additional discomfort without additional benefit, plus reduced tissue temperature for hours", "Cap immersion at 12 minutes and 10-15 degrees Celsius",
             "Kéo dài thời gian ngâm để tăng hiệu quả", "Liều được giả định tăng tuyến tính theo mức khó chịu", "Thêm khó chịu mà không thêm lợi ích, kèm nhiệt độ mô giảm trong nhiều giờ", "Giới hạn ngâm ở 12 phút và 10-15 độ C"],
        ],
        "drills": [
            ["Post-Competition Immersion", "10 min at 12 degrees Celsius within 30 min of finishing", "Ngâm Sau Thi Đấu", "10 phút ở 12 độ C trong vòng 30 phút sau khi kết thúc"],
            ["Contrast Shower Cycle", "4 cycles of 1 min hot and 1 min cold", "Chu Kỳ Tắm Đối Trạch", "4 chu kỳ 1 phút nóng và 1 phút lạnh"],
        ],
    },
    "176": {
        "topic_en": "circadian rhythm adjustment for international tournaments",
        "topic_vi": "điều chỉnh nhịp sinh học cho các giải quốc tế",
        "mech_en": "Jet lag is a **phase-shift problem**, and the practical rate of adjustment is roughly one time zone per day when light exposure is scheduled correctly. Athletes who fail to align light, meals, and training with the destination clock require 7-10 days for a six-hour shift, by which time the tournament is often over.",
        "mech_vi": "Lệch múi giờ là một **bài toán dịch pha**, và tốc độ điều chỉnh thực tiễn là khoảng một múi giờ mỗi ngày khi lịch tiếp xúc ánh sáng được sắp xếp đúng. Vận động viên không căn chỉnh được ánh sáng, bữa ăn và tập luyện theo đồng hồ nơi đến cần 7-10 ngày cho một dịch chuyển sáu giờ, và tới lúc đó giải đấu thường đã kết thúc.",
        "vars": [
            ["Adjustment Rate", "Tốc độ điều chỉnh", "0.8-1.0 time zone per day"],
            ["Morning Light Exposure", "Tiếp xúc ánh sáng buổi sáng", "30-45 min within 1 h of waking"],
            ["Pre-Departure Shift", "Dịch chuyển trước khi khởi hành", "2-3 days at 50% shift"],
        ],
        "subs": [
            ["Phase Response Curves and Light Timing", "Đường Cong Đáp Ứng Pha & Định Thời Ánh Sáng",
             "The circadian system advances when bright light is received in the biological morning and delays when it is received in the biological evening. Correct timing therefore requires knowing the destination clock and the traveller's current phase, because light at the wrong hour shifts the rhythm in the wrong direction and can double the adjustment period.",
             "Hệ nhịp sinh học tiến lên khi ánh sáng mạnh được nhận vào buổi sáng sinh học và lùi lại khi được nhận vào buổi tối sinh học. Do đó định thời đúng đòi hỏi phải biết đồng hồ nơi đến và pha hiện tại của người đi, vì ánh sáng sai giờ sẽ dịch chuyển nhịp theo hướng sai và có thể làm gấp đôi thời gian điều chỉnh."],
            ["Anchoring Meals and Training to Local Time", "Neo Bữa Ăn & Tập Luyện Theo Giờ Địa Phương",
             "Meal timing is a strong secondary zeitgeber: eating on the destination schedule from the first day accelerates re-entrainment, while eating on the origin schedule maintains the old phase. Training at the destination's competition hour provides an additional signal and simultaneously tests performance at the correct time of day.",
             "Định thời bữa ăn là một tín hiệu đồng bộ thứ cấp mạnh: ăn theo lịch nơi đến ngay từ ngày đầu sẽ tăng tốc tái đồng bộ, trong khi ăn theo lịch nơi đi sẽ duy trì pha cũ. Tập luyện vào giờ thi đấu của nơi đến tạo thêm một tín hiệu và đồng thời kiểm tra hiệu suất vào đúng thời điểm trong ngày."],
        ],
        "steps": [
            ["Shift Two to Three Days Before Departure", "Begin a partial shift at home by moving sleep and meals 50% toward the destination schedule; the remaining shift is easier on arrival."],
            ["Fix Morning Light on Arrival", "Get 30-45 minutes of outdoor light within an hour of waking on the first two days; this single behaviour drives most of the adaptation."],
            ["Dịch Chuyển Hai Tới Ba Ngày Trước Khi Khởi Hành", "Bắt đầu dịch chuyển một phần tại nhà bằng cách đưa giấc ngủ và bữa ăn 50% về phía lịch nơi đến; phần dịch chuyển còn lại sẽ dễ hơn khi tới nơi."],
            ["Cố Định Ánh Sáng Buổi Sáng Khi Tới Nơi", "Nhận 30-45 phút ánh sáng ngoài trời trong vòng một giờ sau khi thức trong hai ngày đầu; riêng hành vi này thúc đẩy phần lớn quá trình thích nghi."],
        ],
        "errs": [
            ["Arriving at the last possible moment", "Travel is scheduled to minimise accommodation cost", "Adjustment is incomplete when the first match is played", "Arrive 5-7 days early for shifts above four hours, or begin a pre-departure shift at home",
             "Tới nơi vào phút cuối cùng", "Lịch di chuyển được sắp xếp để giảm chi phí lưu trú", "Quá trình điều chỉnh chưa hoàn tất khi trận đầu được chơi", "Tới sớm 5-7 ngày với dịch chuyển trên bốn giờ, hoặc bắt đầu dịch chuyển trước tại nhà"],
            ["Staying on the home schedule for meals", "Comfort eating is prioritised over re-entrainment", "The old phase is maintained and adaptation stalls", "Eat on the destination schedule from the first day, regardless of appetite",
             "Giữ lịch bữa ăn theo giờ nhà", "Ăn uống theo sở thích được ưu tiên hơn tái đồng bộ", "Pha cũ được duy trì và thích nghi bị đình trệ", "Ăn theo lịch nơi đến ngay từ ngày đầu, bất kể cảm giác thèm ăn"],
        ],
        "drills": [
            ["Morning Light Walk", "30-45 min outdoors within an hour of waking for the first three days", "Đi Bộ Dưới Ánh Sáng Buổi Sáng", "30-45 phút ngoài trời trong vòng một giờ sau khi thức trong ba ngày đầu"],
            ["Competition-Hour Training", "Schedule one session at the exact local match time on days 2-3", "Tập Vào Giờ Thi Đấu", "Sắp một buổi tập vào đúng giờ thi đấu địa phương trong ngày thứ 2-3"],
        ],
    },
    "177": {
        "topic_en": "intra-match carbohydrate and amino acid dosing",
        "topic_vi": "liều carbohydrate và axit amin trong trận",
        "mech_en": "Intra-match nutrition is a **dose-timing problem**: carbohydrate oxidation peaks at 1.0-1.2 g per minute when multiple transportable sugars are used, and amino acid co-ingestion reduces central fatigue signalling. Doses that are too large produce gastrointestinal distress; doses that are too small arrive after the deficit has already formed.",
        "mech_vi": "Dinh dưỡng trong trận là một **bài toán liều - định thời**: quá trình oxy hóa carbohydrate đạt đỉnh ở 1,0-1,2 g mỗi phút khi dùng nhiều loại đường có thể vận chuyển, và việc dùng kèm axit amin làm giảm tín hiệu mệt mỏi trung ương. Liều quá lớn gây rối loạn tiêu hóa; liều quá nhỏ sẽ tới sau khi mức thiếu hụt đã hình thành.",
        "vars": [
            ["Carbohydrate Oxidation Rate", "Tốc độ oxy hóa carbohydrate", "1.0-1.2 g/min"],
            ["Dose per Intake", "Liều mỗi lần nạp", "20-30 g"],
            ["Intake Interval", "Khoảng cách giữa các lần nạp", "20-30 min"],
        ],
        "subs": [
            ["Multiple Transportable Sugars and Oxidation Ceiling", "Nhiều Loại Đường Vận Chuyển Được & Trần Oxy Hóa",
             "Glucose alone saturates its intestinal transporter at roughly 1.0 g per minute. Adding fructose in a 2:1 ratio recruits a second transporter and raises the ceiling to 1.2-1.4 g per minute, which is the physiological basis for dual-sugar formulations in endurance and long-match sports.",
             "Glucose một mình làm bão hòa chất vận chuyển ở ruột ở mức khoảng 1,0 g mỗi phút. Thêm fructose theo tỷ lệ 2:1 sẽ huy động chất vận chuyển thứ hai và nâng trần lên 1,2-1,4 g mỗi phút, đây là cơ sở sinh lý cho các công thức đường kép trong các môn sức bền và các trận đấu dài."],
            ["Amino Acid Co-Ingestion and Central Fatigue", "Dùng Kèm Axit Amin & Mệt Mỏi Trung Ương",
             "Branched-chain amino acid ingestion during prolonged exercise reduces the ratio of free tryptophan to branched-chain amino acids in plasma, which is associated with lower central fatigue perception. The practical dose is small - 5-10 g per hour - and larger doses provide no additional benefit.",
             "Việc nạp axit amin chuỗi nhánh trong vận động kéo dài làm giảm tỷ lệ tryptophan tự do trên axit amin chuỗi nhánh trong huyết tương, và tỷ lệ này có liên quan tới cảm nhận mệt mỏi trung ương thấp hơn. Liều thực tiễn nhỏ - 5-10 g mỗi giờ - và liều lớn hơn không mang lại lợi ích thêm."],
        ],
        "steps": [
            ["Start Before the First Game", "Begin intake in the warm-up period; the first dose should be absorbed before the deficit begins, not after."],
            ["Divide Into 20-30 g Units", "Deliver carbohydrate in units of 20-30 g every 20-30 minutes; single large doses slow gastric emptying."],
            ["Bắt Đầu Trước Game Đầu Tiên", "Bắt đầu nạp trong giai đoạn khởi động; liều đầu tiên nên được hấp thụ trước khi mức thiếu hụt bắt đầu, không phải sau đó."],
            ["Chia Thành Các Đơn Vị 20-30 g", "Cung cấp carbohydrate theo đơn vị 20-30 g mỗi 20-30 phút; những liều lớn đơn lẻ làm chậm tốc độ làm rỗng dạ dày."],
        ],
        "errs": [
            ["Waiting until fatigue is perceived", "Nutrition is treated as a response rather than as prevention", "The deficit is established and performance is already declining before intake begins", "Begin intake during the warm-up and maintain 20-30 g every 20-30 minutes regardless of perceived energy",
             "Chờ tới khi cảm nhận được mệt mỏi", "Dinh dưỡng được coi là phản ứng thay vì phòng ngừa", "Mức thiếu hụt đã hình thành và hiệu suất đã giảm trước khi bắt đầu nạp", "Bắt đầu nạp trong khởi động và duy trì 20-30 g mỗi 20-30 phút bất kể cảm nhận năng lượng"],
            ["Using a single large dose at the changeover", "Convenience determines dose size", "Gastrointestinal distress and delayed absorption during the following games", "Cap each unit at 30 g and never exceed 60 g within 20 minutes",
             "Dùng một liều lớn duy nhất ở lần đổi sân", "Sự tiện lợi quyết định kích thước liều", "Rối loạn tiêu hóa và hấp thụ chậm trong các game tiếp theo", "Giới hạn mỗi đơn vị ở 30 g và không bao giờ vượt 60 g trong 20 phút"],
        ],
        "drills": [
            ["Timed Fueling Simulation", "Practise 25 g every 25 min across a three-set practice match", "Mô Phỏng Nạp Năng Lượng Theo Thời Gian", "Tập nạp 25 g mỗi 25 phút trong một trận tập ba set"],
            ["Gut Tolerance Progression", "Increase hourly carbohydrate by 10 g per week to the target rate", "Tiến Triển Dung Nạp Đường Ruột", "Tăng carbohydrate mỗi giờ thêm 10 g mỗi tuần tới mức mục tiêu"],
        ],
    },
    "178": {
        "topic_en": "lumbar spine decompression for high-volume servers",
        "topic_vi": "giải áp cột sống thắt lưng cho người giao bóng khối lượng lớn",
        "mech_en": "The serve imposes repeated **extension, rotation, and lateral flexion** on the lumbar spine, and high-volume serving produces cumulative compression that presents as stiffness before it presents as pain. Decompression and flexion-based recovery restore disc hydration and reduce paraspinal tone between sessions.",
        "mech_vi": "Động tác giao bóng áp lên cột sống thắt lưng sự lặp lại của **duỗi, xoay và gập ngang**, và giao bóng khối lượng lớn tạo ra nén tích lũy biểu hiện như sự cứng trước khi biểu hiện như đau. Giải áp và phục hồi dựa trên gập giúp phục hồi nước cho đĩa đệm và giảm trương lực cạnh cột sống giữa các buổi tập.",
        "vars": [
            ["Serve Volume Threshold", "Ngưỡng khối lượng giao bóng", "over 300 serves per week"],
            ["Decompression Duration", "Thời lượng giải áp", "2-5 min per session"],
            ["Extension Range After Recovery", "Biên độ duỗi sau phục hồi", "within 10 degrees of baseline"],
        ],
        "subs": [
            ["Load Profile of the Service Action", "Hồ Sơ Tải Của Động Tác Giao Bóng",
             "A kick serve produces 20-35% more lumbar extension and rotation than a flat serve, and each service motion generates compressive loads estimated at 3-6 times body mass in the lumbar region. Weekly volumes above 300 serves therefore represent a substantial cumulative exposure that requires active management.",
             "Giao bóng xoáy kick tạo ra mức duỗi và xoay thắt lưng nhiều hơn 20-35% so với giao bóng phẳng, và mỗi động tác giao bóng tạo ra tải nén ước tính 3-6 lần khối lượng cơ thể ở vùng thắt lưng. Do đó khối lượng trên 300 cú mỗi tuần đại diện cho một mức phơi nhiễm tích lũy đáng kể cần được quản lý chủ động."],
            ["Decompression and Flexion-Based Recovery", "Giải Áp & Phục Hồi Dựa Trên Gập",
             "Passive decompression through hanging or traction reduces paraspinal tone temporarily, while flexion-based movement restores disc nutrition through cyclical loading and unloading. The effective sequence couples both within the same 5-10 minute block rather than relying on either alone.",
             "Giải áp thụ động bằng treo hoặc kéo giãn làm giảm trương lực cạnh cột sống một cách tạm thời, trong khi vận động dựa trên gập phục hồi dưỡng chất cho đĩa đệm thông qua nạp và xả tải có chu kỳ. Trình tự hiệu quả ghép cả hai trong cùng một khối 5-10 phút thay vì chỉ dựa vào một biện pháp."],
        ],
        "steps": [
            ["Track Weekly Serve Volume", "Log serve volume weekly; above 300 serves, add decompression to every post-session routine."],
            ["Restore Flexion Before Extension", "Perform flexion-based recovery before returning to extension-heavy serving; loading extension on a stiff spine reinforces the compression pattern."],
            ["Theo Dõi Khối Lượng Giao Bóng Mỗi Tuần", "Ghi lại khối lượng giao bóng hằng tuần; trên 300 cú, thêm giải áp vào mọi quy trình sau buổi tập."],
            ["Phục Hồi Gập Trước Khi Duỗi", "Thực hiện phục hồi dựa trên gập trước khi quay lại giao bóng nhiều duỗi; nạp tải duỗi lên một cột sống cứng sẽ củng cố mẫu nén."],
        ],
        "errs": [
            ["Ignoring volume accumulation until pain appears", "Only pain is treated as a signal, not stiffness", "Symptoms appear suddenly after several weeks of silent accumulation", "Track weekly serve volume and add decompression whenever the count exceeds 300",
             "Bỏ qua tích lũy khối lượng cho tới khi đau xuất hiện", "Chỉ đau được coi là tín hiệu, không phải sự cứng", "Triệu chứng xuất hiện đột ngột sau nhiều tuần tích lũy âm thầm", "Theo dõi khối lượng giao bóng hằng tuần và thêm giải áp mỗi khi con số vượt 300"],
            ["Returning to full serve volume immediately after recovery", "Symptom relief is interpreted as tissue readiness", "The compression pattern returns within two sessions", "Rebuild serve volume at 50-60% for one week and verify extension range before full volume",
             "Quay lại khối lượng giao bóng đầy đủ ngay sau khi phục hồi", "Giảm triệu chứng được hiểu là mô đã sẵn sàng", "Mẫu nén quay lại trong vòng hai buổi tập", "Xây lại khối lượng giao bóng ở 50-60% trong một tuần và kiểm chứng biên độ duỗi trước khi trở lại khối lượng đầy đủ"],
        ],
        "drills": [
            ["Hanging Decompression", "3 x 30 s passive hang with relaxed breathing", "Treo Giải Áp", "3 x 30 giây treo thụ động với thở thư giãn"],
            ["Flexion-Based Flow", "Cat-camel and knee-to-chest cycles for 3-5 min", "Chuỗi Vận Động Gập", "Chu kỳ mèo-lạc đà và gối vào ngực trong 3-5 phút"],
        ],
    },
    "179": {
        "topic_en": "foot rigidity and plantar fascia health on hard courts",
        "topic_vi": "độ cứng bàn chân và sức khỏe cân gan chân trên sân cứng",
        "mech_en": "The plantar fascia functions as a **spring that stores and returns elastic energy** during the stance phase, and hard courts remove much of the surface compliance that would otherwise absorb impact. Foot intrinsic strength and graded stiffness therefore determine both movement economy and injury exposure.",
        "mech_vi": "Cân gan chân hoạt động như một **lò xo tích trữ và trả lại năng lượng đàn hồi** trong pha trụ, và sân cứng loại bỏ phần lớn độ mềm của bề mặt vốn sẽ hấp thụ va đập. Do đó sức mạnh cơ nội tại bàn chân và độ cứng được phân bậc quyết định cả tính kinh tế trong di chuyển lẫn mức phơi nhiễm chấn thương.",
        "vars": [
            ["Arch Stiffness Index", "Chỉ số độ cứng vòm bàn chân", "normalized 0.8-1.2"],
            ["Foot Intrinsic Endurance", "Sức bền cơ nội tại bàn chân", "25-35 reps short-foot hold"],
            ["Impact Attenuation Deficit", "Mức thiếu hụt hấp thụ va đập", "under 12%"],
        ],
        "subs": [
            ["Windlass Mechanics and Energy Return", "Cơ Chế Tời Quấn & Trả Lại Năng Lượng",
             "During toe extension the plantar fascia winds around the metatarsal heads and raises the arch, storing elastic energy that is returned during push-off. An overly stiff or overly compliant arch both reduce the efficiency of that mechanism, which is why arch stiffness is assessed as a normalized index rather than as a binary.",
             "Trong pha duỗi ngón chân, cân gan chân quấn quanh chỏm xương bàn và nâng vòm bàn chân, tích trữ năng lượng đàn hồi được trả lại trong pha đẩy. Một vòm quá cứng hoặc quá mềm đều làm giảm hiệu suất của cơ chế đó, đó là lý do độ cứng vòm được đánh giá như một chỉ số chuẩn hóa thay vì một giá trị nhị phân."],
            ["Graded Loading for Plantar Tissue", "Nạp Tải Phân Bậc Cho Mô Gan Chân",
             "Plantar tissue responds to progressive loading with improved stiffness and thickness over 8-12 weeks, but responds poorly to sudden increases in court time. The practical rule is a weekly increase in hard-court hours of no more than 15-20% alongside a consistent intrinsic strengthening block.",
             "Mô gan chân đáp ứng với tải tiến triển bằng độ cứng và độ dày được cải thiện trong 8-12 tuần, nhưng đáp ứng kém với việc tăng đột ngột thời gian trên sân. Quy tắc thực tiễn là mức tăng số giờ trên sân cứng hằng tuần không vượt quá 15-20%, kèm một khối tăng cường cơ nội tại nhất quán."],
        ],
        "steps": [
            ["Build Intrinsic Strength Before Volume", "Establish 25-35 short-foot holds before increasing hard-court hours; strength without volume tolerance is not protective."],
            ["Progress Court Hours by 15-20% Weekly", "Cap weekly increases in hard-court exposure and hold one week in four at a reduced volume."],
            ["Xây Sức Mạnh Nội Tại Trước Khối Lượng", "Đạt 25-35 lần giữ tư thế bàn chân ngắn trước khi tăng số giờ trên sân cứng; sức mạnh mà không có dung nạp khối lượng thì không bảo vệ được."],
            ["Tăng Số Giờ Trên Sân 15-20% Mỗi Tuần", "Giới hạn mức tăng phơi nhiễm sân cứng hằng tuần và giữ một tuần trong bốn ở khối lượng giảm."],
        ],
        "errs": [
            ["Jumping into a hard-court tournament block", "Court time is scheduled by competition calendar rather than by tissue tolerance", "Plantar heel pain appears within two to three weeks", "Cap weekly hard-court hour increases at 15-20% and maintain intrinsic foot work throughout",
             "Nhảy vào một khối giải đấu trên sân cứng", "Thời gian trên sân được sắp theo lịch thi đấu thay vì theo dung nạp của mô", "Đau gót chân do cân gan chân xuất hiện trong vòng hai tới ba tuần", "Giới hạn mức tăng số giờ sân cứng hằng tuần ở 15-20% và duy trì bài tập cơ nội tại bàn chân trong suốt thời gian đó"],
            ["Relying on footwear alone", "Shoe cushioning is treated as a substitute for tissue capacity", "Symptoms recur when shoe wear or surface changes", "Combine footwear selection with progressive intrinsic strengthening and graded court exposure",
             "Chỉ dựa vào giày", "Độ đệm của giày được coi là thay thế cho năng lực của mô", "Triệu chứng tái phát khi độ mòn giày hoặc bề mặt sân thay đổi", "Kết hợp chọn giày với tăng cường cơ nội tại tiến triển và phơi nhiễm sân có phân bậc"],
        ],
        "drills": [
            ["Short-Foot Hold", "3 x 25-35 reps of arch elevation without toe curling", "Giữ Tư Thế Bàn Chân Ngắn", "3 x 25-35 lần nâng vòm bàn chân mà không cuộn ngón"],
            ["Calf and Plantar Loading", "Slow heel raises with a towel-scrunch finish, 4 x 12", "Nạp Cẳng Chân Và Gan Chân", "Nhón gót chậm kết thúc bằng động tác cuộn khăn, 4 x 12"],
        ],
    },
    "180": {
        "topic_en": "plyometric shock training for ground force reaction",
        "topic_vi": "huấn luyện bùng nổ va đập cho phản lực mặt sân",
        "mech_en": "Plyometric training improves the **stretch-shortening cycle's ability to return elastic energy**, which shortens ground contact time and raises the force delivered into the next movement. It is also the highest-impact modality available, so progression is governed by contact counts rather than by session duration.",
        "mech_vi": "Huấn luyện bùng nổ cải thiện **khả năng trả lại năng lượng đàn hồi của chu trình căng - ngắn**, điều này rút ngắn thời gian tiếp đất và nâng lực truyền vào động tác kế tiếp. Đây cũng là phương thức va đập cao nhất hiện có, nên tiến triển được điều khiển bằng số lần tiếp đất thay vì bằng thời lượng buổi tập.",
        "vars": [
            ["Weekly Ground Contacts", "Số lần tiếp đất mỗi tuần", "80-140 (novice) to 200-260 (advanced)"],
            ["Ground Contact Time", "Thời gian tiếp đất", "under 0.25 s"],
            ["Reactive Strength Index", "Chỉ số sức mạnh phản ứng", "2.0-3.0"],
        ],
        "subs": [
            ["Stretch-Shortening Cycle Mechanics", "Cơ Học Chu Trình Căng - Ngắn",
             "A rapid eccentric phase followed by a short amortization phase and an immediate concentric phase produces greater force than a concentric action alone. Contact times above 0.25 s shift the action toward a slow stretch-shortening cycle and reduce the transfer to tennis's short ground contacts.",
             "Một pha lệch tâm nhanh tiếp theo bởi pha trung gian ngắn và một pha đồng tâm tức thời tạo ra lực lớn hơn so với chỉ hành động đồng tâm. Thời gian tiếp đất trên 0,25 giây chuyển hành động về phía chu trình căng - ngắn chậm và làm giảm khả năng truyền sang những lần tiếp đất ngắn trong tennis."],
            ["Contact Counting and Progression", "Đếm Số Lần Tiếp Đất & Tiến Triển",
             "Volume is prescribed in ground contacts, and novice athletes begin at 80-140 per week, progressing by no more than 10-15% weekly. Plyometrics are placed early in a session after a full warm-up and never on consecutive days.",
             "Khối lượng được chỉ định bằng số lần tiếp đất, và vận động viên mới bắt đầu ở 80-140 lần mỗi tuần, tiến triển không quá 10-15% mỗi tuần. Bài bùng nổ được đặt ở phần đầu buổi tập sau khởi động đầy đủ và không bao giờ vào hai ngày liên tiếp."],
        ],
        "steps": [
            ["Count Contacts, Not Minutes", "Prescribe volume in contacts; timing a plyometric session is meaningless because rest intervals dominate the duration."],
            ["Require Full Recovery Between Sets", "Rest 90-180 s between sets to preserve contact quality; a degrading contact time indicates the set must end."],
            ["Đếm Số Lần Tiếp Đất, Không Đếm Phút", "Chỉ định khối lượng bằng số lần tiếp đất; việc bấm thời gian một buổi bùng nổ là vô nghĩa vì khoảng nghỉ chi phối thời lượng."],
            ["Yêu Cầu Phục Hồi Đầy Đủ Giữa Các Loạt", "Nghỉ 90-180 giây giữa các loạt để giữ chất lượng tiếp đất; thời gian tiếp đất suy giảm cho thấy loạt phải kết thúc."],
        ],
        "errs": [
            ["Adding plyometrics on top of an unchanged court schedule", "The modality is added rather than substituted", "Cumulative impact load exceeds tissue tolerance and tendon pain appears", "Count total weekly contacts including court work, and reduce court volume when plyometrics are introduced",
             "Thêm bài bùng nổ lên trên một lịch sân không thay đổi", "Phương thức được thêm vào thay vì được thay thế", "Tải va đập tích lũy vượt dung nạp của mô và đau gân xuất hiện", "Đếm tổng số lần tiếp đất mỗi tuần bao gồm cả tập trên sân, và giảm khối lượng sân khi đưa bài bùng nổ vào"],
            ["Training plyometrics on consecutive days", "Sessions are scheduled by convenience", "Elastic energy return degrades and injury risk rises sharply", "Separate plyometric sessions by at least 48 h and never schedule them after a long match",
             "Tập bùng nổ vào hai ngày liên tiếp", "Các buổi tập được sắp theo sự tiện lợi", "Khả năng trả lại năng lượng đàn hồi suy giảm và nguy cơ chấn thương tăng mạnh", "Tách các buổi bùng nổ ít nhất 48 giờ và không bao giờ sắp chúng sau một trận dài"],
        ],
        "drills": [
            ["Pogo Series", "3 x 15 contacts with stiff ankles, contact time under 0.25 s", "Chuỗi Nhảy Pogo", "3 x 15 lần tiếp đất với cổ chân cứng, thời gian tiếp đất dưới 0,25 giây"],
            ["Lateral Bound", "4 x 6 per side for distance with controlled landings", "Nhảy Ngang", "4 x 6 mỗi bên theo quãng đường với tiếp đất có kiểm soát"],
        ],
    },
}
