# -*- coding: utf-8 -*-
"""Per-article knowledge data, articles 187-192."""

DATA = {
    "187": {
        "topic_en": "VO2 max and anaerobic threshold training ratios",
        "topic_vi": "tỷ lệ huấn luyện VO2 max và ngưỡng yếm khí",
        "mech_en": "Tennis performance depends more on the **speed of recovery between efforts** than on maximal aerobic power, which means threshold work transfers better than VO2 max intervals for most players. The practical ratio is roughly 70% threshold work to 30% maximal aerobic intervals across a conditioning block.",
        "mech_vi": "Hiệu suất tennis phụ thuộc nhiều vào **tốc độ phục hồi giữa các đợt gắng** hơn là vào công suất ưa khí tối đa, nghĩa là bài tập ngưỡng chuyển giao tốt hơn bài tập interval VO2 max với phần lớn người chơi. Tỷ lệ thực tiễn là khoảng 70% bài ngưỡng và 30% bài interval ưa khí tối đa trong một khối thể lực.",
        "vars": [
            ["Threshold Intensity", "Cường độ ngưỡng", "80-88% of max heart rate"],
            ["VO2 Max Interval Intensity", "Cường độ interval VO2 max", "93-97% of max heart rate"],
            ["Weekly Aerobic Volume", "Khối lượng ưa khí mỗi tuần", "120-180 min"],
        ],
        "subs": [
            ["Why Threshold Work Transfers to Tennis", "Vì Sao Bài Ngưỡng Truyền Được Sang Tennis",
             "Tennis recovery intervals of 20-25 seconds sit close to the intensity at which lactate appearance and clearance are balanced, so improving that balance directly shortens the time to restore phosphocreatine. Maximal aerobic intervals improve the ceiling but are used for a smaller proportion of match time.",
             "Các khoảng phục hồi 20-25 giây trong tennis nằm gần cường độ mà ở đó sự xuất hiện và thải lactate cân bằng nhau, nên cải thiện sự cân bằng đó trực tiếp rút ngắn thời gian phục hồi phosphocreatine. Bài interval ưa khí tối đa cải thiện trần nhưng chỉ được dùng cho một phần nhỏ thời gian trận đấu."],
            ["Structuring the Aerobic Week", "Cấu Trúc Tuần Ưa Khí",
             "A practical week contains two threshold sessions of 20-40 minutes of accumulated work, one maximal aerobic interval session of 4-6 repetitions at 3-4 minutes, and one long continuous session of 45-70 minutes at conversational pace, all placed away from the highest-quality tactical sessions.",
             "Một tuần thực tiễn gồm hai buổi ngưỡng với 20-40 phút công việc tích lũy, một buổi interval ưa khí tối đa với 4-6 lần lặp ở 3-4 phút, và một buổi liên tục dài 45-70 phút ở mức nói chuyện được, tất cả được đặt xa các buổi chiến thuật chất lượng cao nhất."],
        ],
        "steps": [
            ["Measure the Threshold, Do Not Estimate It", "Use a 30-minute time trial or a lactate test to locate the threshold; field estimates from perceived effort are unreliable by 8-12 beats per minute."],
            ["Protect Tactical Quality From Aerobic Load", "Place threshold sessions at least 24 hours away from the highest-quality tactical session in the week."],
            ["Đo Ngưỡng, Không Ước Lượng", "Dùng bài chạy 30 phút hoặc xét nghiệm lactate để xác định ngưỡng; các ước lượng theo cảm nhận sai lệch 8-12 nhịp mỗi phút."],
            ["Bảo Vệ Chất Lượng Chiến Thuật Khỏi Tải Ưa Khí", "Đặt các buổi ngưỡng cách buổi chiến thuật chất lượng cao nhất trong tuần ít nhất 24 giờ."],
        ],
        "errs": [
            ["Training mostly above threshold", "Harder is assumed to be better", "Accumulated fatigue degrades technical sessions while aerobic markers improve", "Hold 70% of aerobic work at threshold intensity and reserve maximal intervals for 30%",
             "Tập phần lớn ở cường độ trên ngưỡng", "Khó hơn được giả định là tốt hơn", "Mệt mỏi tích lũy làm suy giảm các buổi kỹ thuật trong khi chỉ số ưa khí vẫn cải thiện", "Giữ 70% khối lượng ưa khí ở cường độ ngưỡng và dành 30% cho interval tối đa"],
            ["Chasing VO2 max numbers with no tennis transfer", "Laboratory metrics are treated as performance metrics", "Aerobic power rises while recovery between points remains unchanged", "Track repeated-sprint decrement and heart-rate recovery alongside aerobic markers",
             "Đuổi theo chỉ số VO2 max mà không có chuyển giao sang tennis", "Các chỉ số phòng thí nghiệm được coi là chỉ số hiệu suất", "Công suất ưa khí tăng trong khi phục hồi giữa các điểm không đổi", "Theo dõi mức giảm chạy nước rút lặp lại và phục hồi nhịp tim song song với các chỉ số ưa khí"],
        ],
        "drills": [
            ["Threshold Intervals", "4 x 8 min at threshold with 2 min recovery", "Interval Ngưỡng", "4 x 8 phút ở ngưỡng với 2 phút phục hồi"],
            ["Maximal Aerobic Set", "5 x 3 min at 93-97% with equal recovery", "Loạt Ưa Khí Tối Đa", "5 x 3 phút ở 93-97% với phục hồi tương đương"],
        ],
    },
    "188": {
        "topic_en": "kinetic energy deficit audits in injured athletes",
        "topic_vi": "kiểm toán thiếu hụt năng lượng động học ở vận động viên chấn thương",
        "mech_en": "Return to play requires auditing **where kinetic energy is no longer being transferred**, because an injured athlete compensates rather than simply underperforms. The audit measures segment-by-segment transfer and identifies the joint that has become a leak, allowing targeted restoration before full loading resumes.",
        "mech_vi": "Trở lại thi đấu đòi hỏi kiểm toán **nơi năng lượng động học không còn được truyền đi**, vì vận động viên bị chấn thương bù trừ chứ không chỉ đơn thuần hoạt động kém. Việc kiểm toán đo lường truyền lực theo từng phân đoạn và xác định khớp đã trở thành điểm rò rỉ, cho phép phục hồi có mục tiêu trước khi nạp tải đầy đủ trở lại.",
        "vars": [
            ["Segment Transfer Deficit Threshold", "Ngưỡng thiếu hụt truyền lực phân đoạn", "over 12%"],
            ["Affected-Side Strength Symmetry", "Đối xứng sức mạnh bên bị ảnh hưởng", "90-95% of contralateral"],
            ["Return-to-Play Criteria Count", "Số tiêu chí trở lại thi đấu", "6-8 objective criteria"],
        ],
        "subs": [
            ["Compensation Patterns After Injury", "Các Mẫu Bù Trừ Sau Chấn Thương",
             "After a lower-limb injury, athletes routinely reduce hip extensor contribution and increase knee and ankle contribution to protect the injured segment. The compensation restores gross function but reduces transfer efficiency, which reappears as reduced serve velocity or slower direction changes rather than as pain.",
             "Sau chấn thương chi dưới, vận động viên thường giảm đóng góp của cơ duỗi hông và tăng đóng góp của gối và cổ chân để bảo vệ phân đoạn bị chấn thương. Sự bù trừ phục hồi chức năng tổng thể nhưng làm giảm hiệu suất truyền lực, và điều này tái xuất hiện dưới dạng giảm tốc độ giao bóng hoặc đổi hướng chậm hơn thay vì dưới dạng đau."],
            ["Objective Return-to-Play Criteria", "Tiêu Chí Trở Lại Thi Đấu Khách Quan",
             "Six to eight objective criteria should be satisfied before unrestricted play: strength symmetry of 90-95%, single-leg hop distance symmetry, braking quality score of 3 or above, pain-free maximal serve, unrestricted change of direction, and a completed progressive load block.",
             "Sáu tới tám tiêu chí khách quan cần được thỏa mãn trước khi thi đấu không hạn chế: đối xứng sức mạnh 90-95%, đối xứng quãng đường nhảy một chân, điểm chất lượng hãm từ 3 trở lên, giao bóng tối đa không đau, đổi hướng không hạn chế, và một khối nạp tải tiến triển đã hoàn thành."],
        ],
        "steps": [
            ["Test Before Clearing, Not After Relapse", "Complete the full objective battery before clearing the athlete; relapse is the most expensive form of feedback."],
            ["Restore Transfer Before Volume", "Rebuild segmental transfer with low-volume, high-quality patterns before returning to match volume."],
            ["Kiểm Tra Trước Khi Cho Phép, Không Chờ Tái Phát", "Hoàn thành toàn bộ bộ tiêu chí khách quan trước khi cho phép vận động viên trở lại; tái phát là dạng phản hồi đắt đỏ nhất."],
            ["Phục Hồi Truyền Lực Trước Khối Lượng", "Xây lại truyền lực phân đoạn bằng các mẫu khối lượng thấp, chất lượng cao trước khi trở lại khối lượng trận đấu."],
        ],
        "errs": [
            ["Clearing on pain resolution alone", "Absence of pain is treated as readiness", "Compensation patterns persist and the injury recurs at the same or a different site", "Require 6-8 objective criteria including strength symmetry and braking quality before clearance",
             "Cho phép trở lại chỉ dựa trên việc hết đau", "Việc hết đau được coi là sẵn sàng", "Các mẫu bù trừ vẫn tồn tại và chấn thương tái phát ở cùng vị trí hoặc vị trí khác", "Yêu cầu 6-8 tiêu chí khách quan bao gồm đối xứng sức mạnh và chất lượng hãm trước khi cho phép"],
            ["Returning to full match volume immediately", "Motivation and calendar pressure override progression", "Tissue tolerance is exceeded within two to three sessions", "Complete a progressive load block at 50%, 75%, and 90% of match volume before unrestricted play",
             "Trở lại khối lượng trận đấu đầy đủ ngay lập tức", "Động lực và áp lực lịch thi đấu lấn át tiến trình", "Dung nạp của mô bị vượt qua trong hai tới ba buổi", "Hoàn thành khối nạp tải tiến triển ở 50%, 75% và 90% khối lượng trận trước khi thi đấu không hạn chế"],
        ],
        "drills": [
            ["Segmental Transfer Test", "Force-plate or video assessment of hip, knee, and ankle contribution", "Bài Đo Truyền Lực Phân Đoạn", "Đánh giá bằng bàn lực hoặc video về đóng góp của hông, gối và cổ chân"],
            ["Progressive Load Block", "Three sessions at 50%, 75%, 90% of match volume with symptom monitoring", "Khối Nạp Tải Tiến Triển", "Ba buổi ở 50%, 75%, 90% khối lượng trận với theo dõi triệu chứng"],
        ],
    },
    "189": {
        "topic_en": "sensory deprivation float therapy for cognitive reset",
        "topic_vi": "liệu pháp trôi giảm kích thích giác quan để khôi phục nhận thức",
        "mech_en": "Floatation reduces **sensory input to near zero**, which lowers sympathetic tone and permits a cognitive reset that ordinary rest does not produce. The measurable effects are reduced perceived fatigue and improved reaction time in the 24 hours following a session, rather than any direct tissue repair.",
        "mech_vi": "Liệu pháp trôi giảm **đầu vào giác quan xuống gần bằng không**, điều này hạ trương lực giao cảm và cho phép một lần khôi phục nhận thức mà nghỉ ngơi thông thường không tạo ra. Các hiệu ứng đo được là giảm mệt mỏi cảm nhận và cải thiện thời gian phản ứng trong 24 giờ sau buổi, chứ không phải bất kỳ sửa chữa mô trực tiếp nào.",
        "vars": [
            ["Session Duration", "Thời lượng buổi", "45-60 min"],
            ["Water Temperature", "Nhiệt độ nước", "34.5-35.5 degrees Celsius"],
            ["Reaction Time Improvement", "Mức cải thiện thời gian phản ứng", "8-15 ms within 24 h"],
        ],
        "subs": [
            ["Sensory Reduction and Autonomic Shift", "Giảm Kích Thích Giác Quan & Dịch Chuyển Tự Chủ",
             "Removing light, sound, and proprioceptive load from the postural system reduces the brain's processing demand substantially. Salivary cortisol falls measurably after a session, and heart-rate variability rises, which is the physiological basis for the reported cognitive reset.",
             "Việc loại bỏ ánh sáng, âm thanh và tải cảm nhận vị thế khỏi hệ thống tư thế làm giảm đáng kể nhu cầu xử lý của não. Cortisol trong nước bọt giảm đo được sau một buổi, và biến thiên nhịp tim tăng, đây là cơ sở sinh lý cho hiệu ứng khôi phục nhận thức được báo cáo."],
            ["Positioning Within the Training Week", "Định Vị Trong Tuần Huấn Luyện",
             "The modality is most useful 24-48 hours after the highest-load session of the week, or immediately after travel. Used as a substitute for sleep it provides no benefit, because the mechanisms overlap only partially and sleep remains irreplaceable.",
             "Phương thức này hữu ích nhất 24-48 giờ sau buổi tập tải cao nhất trong tuần, hoặc ngay sau khi di chuyển. Dùng nó như thay thế cho giấc ngủ sẽ không mang lại lợi ích, vì các cơ chế chỉ trùng lặp một phần và giấc ngủ vẫn không thể thay thế."],
        ],
        "steps": [
            ["Schedule After Peak Load, Not Before", "Place the session after the week's highest-load day; using it before a key session provides no ergogenic benefit."],
            ["Keep the Session Passive and Unstructured", "Do not combine floatation with problem-solving; the mechanism is sensory reduction, which requires the absence of tasks."],
            ["Sắp Sau Đỉnh Tải, Không Phải Trước", "Đặt buổi sau ngày tải cao nhất trong tuần; dùng nó trước một buổi quan trọng không mang lại lợi ích tăng cường hiệu suất."],
            ["Giữ Buổi Thụ Động Và Không Cấu Trúc", "Không kết hợp trôi với giải quyết vấn đề; cơ chế là giảm kích thích giác quan, và điều đó đòi hỏi không có nhiệm vụ nào."],
        ],
        "errs": [
            ["Using floatation as a substitute for sleep", "Both are treated as general recovery", "Sleep debt persists and cognitive performance remains impaired", "Keep floatation as an adjunct placed after peak load and protect 7-9 h of sleep independently",
             "Dùng trôi như thay thế cho giấc ngủ", "Cả hai được coi là phục hồi tổng quát", "Nợ giấc ngủ vẫn tồn tại và hiệu suất nhận thức vẫn suy giảm", "Giữ trôi như một biện pháp bổ trợ đặt sau đỉnh tải và bảo vệ 7-9 giờ ngủ một cách độc lập"],
            ["Scheduling floatation immediately before competition", "Recovery modalities are assumed to be ergogenic", "No performance benefit is observed and travel time is wasted", "Restrict the modality to the 24-48 h window after peak load or after travel",
             "Sắp buổi trôi ngay trước thi đấu", "Các phương thức phục hồi được giả định là tăng cường hiệu suất", "Không quan sát thấy lợi ích hiệu suất và thời gian di chuyển bị lãng phí", "Giới hạn phương thức trong cửa sổ 24-48 giờ sau đỉnh tải hoặc sau khi di chuyển"],
        ],
        "drills": [
            ["Post-Peak Float", "50 min session 24-48 h after the highest-load day", "Trôi Sau Đỉnh Tải", "Buổi 50 phút 24-48 giờ sau ngày tải cao nhất"],
            ["Reaction Time Check", "Simple reaction test before and 24 h after the session", "Kiểm Tra Thời Gian Phản Ứng", "Bài kiểm tra phản ứng đơn giản trước và 24 giờ sau buổi"],
        ],
    },
    "190": {
        "topic_en": "heat acclimatization protocols for summer tournaments",
        "topic_vi": "phác đồ thích nghi nóng cho các giải đấu mùa hè",
        "mech_en": "Heat acclimatization produces **plasma volume expansion, earlier sweat onset, and lower sweat sodium concentration** within 5-14 days. These adaptations reduce core temperature at any given workload, which is the mechanism by which performance and decision quality are preserved in hot conditions.",
        "mech_vi": "Thích nghi nóng tạo ra **tăng thể tích huyết tương, khởi phát tiết mồ hôi sớm hơn, và giảm nồng độ natri trong mồ hôi** trong vòng 5-14 ngày. Những thích nghi này làm giảm nhiệt độ cốt lõi ở bất kỳ mức tải nào, và đây là cơ chế giúp bảo toàn hiệu suất và chất lượng quyết định trong điều kiện nóng.",
        "vars": [
            ["Acclimatization Duration", "Thời gian thích nghi", "5-14 days"],
            ["Daily Heat Exposure", "Thời gian tiếp xúc nóng mỗi ngày", "60-90 min"],
            ["Plasma Volume Expansion", "Mức tăng thể tích huyết tương", "4-8%"],
        ],
        "subs": [
            ["Physiological Adaptations to Repeated Heat", "Thích Nghi Sinh Lý Với Nhiệt Lặp Lại",
             "The adaptation sequence begins with plasma volume expansion within three to five days, followed by earlier and higher sweat rates, then by reduced sweat sodium concentration. Core temperature at a fixed workload falls by 0.3-0.6 degrees Celsius by day 10-14, which is the practically relevant endpoint.",
             "Trình tự thích nghi bắt đầu bằng tăng thể tích huyết tương trong ba tới năm ngày, tiếp theo là tốc độ tiết mồ hôi sớm hơn và cao hơn, rồi tới giảm nồng độ natri trong mồ hôi. Nhiệt độ cốt lõi ở một mức tải cố định giảm 0,3-0,6 độ C vào ngày 10-14, và đây là điểm kết thúc có ý nghĩa thực tiễn."],
            ["Protocol Design and Decay", "Thiết Kế Phác Đồ & Sự Suy Giảm",
             "Adaptations decay with a half-life of roughly one week, so a block must be scheduled close to competition. The protocol is 60-90 minutes of daily exposure with training intensity maintained at 60-75% to allow sufficient volume without excessive strain.",
             "Các thích nghi suy giảm với thời gian bán hủy khoảng một tuần, nên khối tập phải được sắp gần giải đấu. Phác đồ là 60-90 phút tiếp xúc hằng ngày với cường độ tập duy trì ở 60-75% để cho phép đủ khối lượng mà không quá căng thẳng."],
        ],
        "steps": [
            ["Start 10-14 Days Before Competition", "Begin the block so that the final adaptation day falls three to five days before the first match."],
            ["Monitor Core Temperature and Body Mass", "Track morning body mass and, where available, core temperature; a loss above 2% of body mass requires immediate protocol adjustment."],
            ["Bắt Đầu 10-14 Ngày Trước Giải", "Bắt đầu khối tập sao cho ngày thích nghi cuối rơi vào ba tới năm ngày trước trận đầu tiên."],
            ["Theo Dõi Nhiệt Độ Cốt Lõi Và Khối Lượng Cơ Thể", "Theo dõi khối lượng cơ thể buổi sáng và, khi có thiết bị, nhiệt độ cốt lõi; mức giảm trên 2% khối lượng cơ thể đòi hỏi điều chỉnh phác đồ ngay."],
        ],
        "errs": [
            ["Arriving at a hot tournament without acclimatization", "Heat is treated as a condition to endure rather than to prepare for", "Core temperature reaches impairment thresholds in the second set", "Complete a 5-14 day acclimatization block before travelling to hot conditions",
             "Tới giải đấu nóng mà không thích nghi", "Nóng được coi là điều kiện phải chịu đựng thay vì phải chuẩn bị", "Nhiệt độ cốt lõi chạm ngưỡng suy giảm ở set thứ hai", "Hoàn thành khối thích nghi 5-14 ngày trước khi tới điều kiện nóng"],
            ["Training at full intensity during acclimatization", "The heat stimulus is assumed to replace the need to reduce intensity", "Excessive strain, dehydration, and degraded training quality", "Hold intensity at 60-75% of normal during the acclimatization block and monitor body mass daily",
             "Tập ở cường độ đầy đủ trong khi thích nghi nóng", "Kích thích nhiệt được giả định thay thế nhu cầu giảm cường độ", "Căng thẳng quá mức, mất nước, và chất lượng tập suy giảm", "Giữ cường độ ở 60-75% mức bình thường trong khối thích nghi và theo dõi khối lượng cơ thể hằng ngày"],
        ],
        "drills": [
            ["Daily Heat Exposure", "75 min of on-court work at 60-75% intensity in the heat", "Tiếp Xúc Nóng Hằng Ngày", "75 phút tập trên sân ở 60-75% cường độ trong điều kiện nóng"],
            ["Body Mass Log", "Morning and post-session weighing to track fluid balance", "Nhật Ký Khối Lượng", "Cân buổi sáng và sau buổi tập để theo dõi cân bằng dịch"],
        ],
    },
    "191": {
        "topic_en": "hyperbaric oxygen therapy in tissue repair",
        "topic_vi": "liệu pháp oxy cao áp trong sửa chữa mô",
        "mech_en": "Hyperbaric oxygen raises **dissolved oxygen content in plasma** and stimulates angiogenesis in hypoxic tissue, which is relevant for injuries where perfusion is the limiting factor. It is not a general recovery tool, and its effect on healthy muscle is negligible; it is indicated for specific hypoxic or poorly healing tissue.",
        "mech_vi": "Oxy cao áp làm tăng **hàm lượng oxy hòa tan trong huyết tương** và kích thích tạo mạch ở mô thiếu oxy, điều này có ý nghĩa với những chấn thương mà tưới máu là yếu tố giới hạn. Đây không phải công cụ phục hồi tổng quát, và hiệu ứng của nó trên cơ khỏe mạnh là không đáng kể; nó được chỉ định cho mô thiếu oxy hoặc chậm lành cụ thể.",
        "vars": [
            ["Chamber Pressure", "Áp suất buồng", "2.0-2.5 ATA"],
            ["Session Duration", "Thời lượng buổi", "60-90 min"],
            ["Session Count per Protocol", "Số buổi mỗi phác đồ", "10-20 sessions"],
        ],
        "subs": [
            ["Mechanism and Indications", "Cơ Chế & Chỉ Định",
             "At 2.0-2.5 atmospheres absolute, dissolved oxygen in plasma rises enough to support tissue that is poorly perfused, and repeated exposure stimulates fibroblast activity and capillary growth. The indications in sport are narrow: hypoxic wounds, severe contusions, and delayed healing rather than routine soreness.",
             "Ở 2,0-2,5 lần áp suất khí quyển tuyệt đối, oxy hòa tan trong huyết tương tăng đủ để hỗ trợ mô được tưới máu kém, và việc tiếp xúc lặp lại kích thích hoạt động nguyên bào sợi và phát triển mao mạch. Các chỉ định trong thể thao hẹp: vết thương thiếu oxy, dập nặng, và lành chậm, chứ không phải đau nhức thông thường."],
            ["Evidence Boundaries and Cost", "Ranh Giới Bằng Chứng & Chi Phí",
             "Evidence for enhanced recovery in healthy athletes is weak, and the time cost of 10-20 sessions of 60-90 minutes is substantial. The modality should be considered only when a specific hypoxic tissue problem exists and the schedule permits the time commitment.",
             "Bằng chứng về phục hồi được tăng cường ở vận động viên khỏe mạnh là yếu, và chi phí thời gian của 10-20 buổi 60-90 phút là đáng kể. Phương thức này chỉ nên được xem xét khi tồn tại một vấn đề mô thiếu oxy cụ thể và lịch trình cho phép cam kết thời gian đó."],
        ],
        "steps": [
            ["Confirm a Specific Indication", "Require a documented hypoxic or poorly healing tissue problem; do not use the modality for general soreness."],
            ["Schedule Around Training, Not Through It", "Place sessions so they do not displace sleep or the highest-quality training blocks."],
            ["Xác Nhận Chỉ Định Cụ Thể", "Yêu cầu một vấn đề mô thiếu oxy hoặc lành chậm đã được ghi nhận; không dùng phương thức này cho đau nhức thông thường."],
            ["Sắp Lịch Quanh Buổi Tập, Không Xuyên Qua Nó", "Đặt các buổi sao cho chúng không thay thế giấc ngủ hoặc các khối tập chất lượng cao nhất."],
        ],
        "errs": [
            ["Using hyperbaric oxygen as a routine recovery tool", "The modality is adopted for convenience rather than for indication", "Time cost is high and measurable benefit is absent", "Restrict use to documented hypoxic injury and reassess after ten sessions",
             "Dùng oxy cao áp như công cụ phục hồi thường quy", "Phương thức được dùng vì tiện lợi thay vì vì chỉ định", "Chi phí thời gian cao và lợi ích đo được không có", "Giới hạn sử dụng cho chấn thương thiếu oxy đã ghi nhận và đánh giá lại sau mười buổi"],
            ["Replacing sleep time with chamber sessions", "Recovery modalities are treated as interchangeable", "Sleep debt accumulates and negates any tissue benefit", "Never schedule chamber sessions at the expense of sleep and re-evaluate after each block",
             "Thay thế thời gian ngủ bằng các buổi trong buồng", "Các phương thức phục hồi được coi là có thể thay thế cho nhau", "Nợ giấc ngủ tích lũy và phủ định mọi lợi ích cho mô", "Không bao giờ sắp buổi trong buồng bằng cái giá của giấc ngủ và đánh giá lại sau mỗi khối"],
        ],
        "drills": [
            ["Indication Audit", "Document the specific tissue problem before the first session", "Kiểm Toán Chỉ Định", "Ghi nhận vấn đề mô cụ thể trước buổi đầu tiên"],
            ["Session Log", "Track sessions, symptoms, and training quality across the block", "Nhật Ký Buổi", "Theo dõi số buổi, triệu chứng và chất lượng tập trong suốt khối"],
        ],
    },
    "192": {
        "topic_en": "infrared light therapy for deep joint micro-trauma",
        "topic_vi": "liệu pháp ánh sáng hồng ngoại cho vi chấn thương khớp sâu",
        "mech_en": "Infrared exposure raises **tissue temperature at depth** and is proposed to influence mitochondrial signalling through photobiomodulation. Evidence is strongest for short-term pain reduction and weakest for structural repair, so the modality is best treated as an adjunct within a loading programme.",
        "mech_vi": "Tiếp xúc hồng ngoại làm tăng **nhiệt độ mô ở độ sâu** và được đề xuất là có ảnh hưởng tới tín hiệu ty thể thông qua điều biến quang sinh học. Bằng chứng mạnh nhất ở việc giảm đau ngắn hạn và yếu nhất ở sửa chữa cấu trúc, nên phương thức này tốt nhất được coi là bổ trợ trong một chương trình nạp tải.",
        "vars": [
            ["Wavelength Range", "Dải bước sóng", "600-1,100 nm"],
            ["Treatment Duration", "Thời lượng điều trị", "10-20 min per site"],
            ["Pain Reduction Window", "Cửa sổ giảm đau", "2-6 h"],
        ],
        "subs": [
            ["Photobiomodulation and Thermal Effects", "Điều Biến Quang Sinh Học & Hiệu Ứng Nhiệt",
             "Two mechanisms are proposed: a thermal effect that increases local blood flow and tissue extensibility, and a photochemical effect on mitochondrial cytochrome oxidase. The thermal effect is well established; the photochemical effect remains debated at the doses achievable in practice.",
             "Hai cơ chế được đề xuất: một hiệu ứng nhiệt làm tăng lưu lượng máu cục bộ và độ dãn của mô, và một hiệu ứng quang hóa lên cytochrome oxidase của ty thể. Hiệu ứng nhiệt đã được xác lập rõ; hiệu ứng quang hóa vẫn còn tranh luận ở các liều đạt được trong thực tiễn."],
            ["Placement in a Rehabilitation Programme", "Vị Trí Trong Chương Trình Phục Hồi",
             "The modality is placed immediately before loading so that the transient pain reduction allows higher-quality movement, exactly as isometric analgesia is used. Relying on it as the primary intervention produces temporary comfort without restoring capacity.",
             "Phương thức này được đặt ngay trước khi nạp tải để mức giảm đau tạm thời cho phép vận động chất lượng cao hơn, đúng như cách dùng giảm đau bằng đẳng trường. Dựa vào nó như can thiệp chính sẽ tạo ra sự thoải mái tạm thời mà không phục hồi năng lực."],
        ],
        "steps": [
            ["Apply Before Loading, Not After", "Use the modality before the loading block so the pain reduction improves movement quality rather than merely providing comfort."],
            ["Cap Treatment Time", "Keep exposure at 10-20 minutes per site; longer exposure adds heat without additional benefit."],
            ["Áp Dụng Trước Khi Nạp Tải, Không Phải Sau", "Dùng phương thức trước khối nạp tải để việc giảm đau cải thiện chất lượng vận động thay vì chỉ mang lại sự thoải mái."],
            ["Giới Hạn Thời Gian Điều Trị", "Giữ tiếp xúc ở 10-20 phút mỗi vị trí; tiếp xúc lâu hơn chỉ thêm nhiệt mà không thêm lợi ích."],
        ],
        "errs": [
            ["Treating infrared as a cure rather than an adjunct", "Symptom relief is mistaken for tissue recovery", "The loading programme is skipped and capacity continues to decline", "Require concurrent progressive loading and treat pain reduction as a facilitator, not an outcome",
             "Coi hồng ngoại là phương pháp chữa trị thay vì bổ trợ", "Giảm triệu chứng bị nhầm với phục hồi mô", "Chương trình nạp tải bị bỏ qua và năng lực tiếp tục suy giảm", "Yêu cầu nạp tải tiến triển song song và coi giảm đau là yếu tố hỗ trợ, không phải kết quả"],
            ["Prolonging sessions to increase effect", "Dose is assumed to scale with duration", "Local heating exceeds therapeutic range and tissue is irritated", "Cap each site at 20 minutes and reassess the pain response at 24 hours",
             "Kéo dài buổi để tăng hiệu quả", "Liều được giả định tăng theo thời lượng", "Nhiệt cục bộ vượt dải trị liệu và mô bị kích thích", "Giới hạn mỗi vị trí ở 20 phút và đánh giá lại đáp ứng đau sau 24 giờ"],
        ],
        "drills": [
            ["Pre-Load Application", "15 min per site before the loading block", "Áp Dụng Trước Khi Nạp Tải", "15 phút mỗi vị trí trước khối nạp tải"],
            ["Twenty-Four Hour Response Log", "Record pain at 24 h after each session", "Nhật Ký Đáp Ứng 24 Giờ", "Ghi mức đau sau 24 giờ mỗi buổi"],
        ],
    },
}
