# -*- coding: utf-8 -*-
"""Per-article knowledge data, articles 169-174."""

DATA = {
    "169": {
        "topic_en": "lactate clearance via active aerobic recovery",
        "topic_vi": "thải lactate bằng phục hồi ưa khí chủ động",
        "mech_en": "Lactate is not a waste product awaiting passive elimination; it is a **fuel and a signaling molecule** cleared primarily by oxidation in slow-twitch fibres, the heart, and the liver. Active recovery at 30-45% of maximal aerobic capacity accelerates clearance by 25-40% compared with passive rest.",
        "mech_vi": "Lactate không phải một chất thải đang chờ bị loại bỏ thụ động; nó là một **nguồn nhiên liệu và một phân tử tín hiệu** được thải chủ yếu qua oxy hóa ở các sợi co chậm, ở tim và ở gan. Phục hồi chủ động ở 30-45% năng lực ưa khí tối đa tăng tốc độ thải 25-40% so với nghỉ thụ động.",
        "vars": [
            ["Active Recovery Intensity", "Cường độ phục hồi chủ động", "30-45% of max aerobic capacity"],
            ["Clearance Half-Time Passive", "Thời gian bán thải khi nghỉ thụ động", "25-35 min"],
            ["Clearance Half-Time Active", "Thời gian bán thải khi chủ động", "15-22 min"],
        ],
        "subs": [
            ["Lactate Shuttle and Oxidation", "Con Thoi Lactate & Quá Trình Oxy Hóa",
             "The lactate shuttle describes the transport of lactate from fast-twitch fibres producing it to slow-twitch fibres, cardiac muscle, and the liver where it is oxidized or resynthesized. Maintaining blood flow through those tissues is the mechanism by which active recovery accelerates clearance, and the required intensity is well below any meaningful fatigue threshold.",
             "Con thoi lactate mô tả quá trình vận chuyển lactate từ các sợi co nhanh sản sinh ra nó tới các sợi co chậm, cơ tim và gan, nơi nó được oxy hóa hoặc tái tổng hợp. Duy trì dòng máu qua các mô đó là cơ chế giúp phục hồi chủ động tăng tốc thải lactate, và cường độ cần thiết thấp hơn nhiều so với bất kỳ ngưỡng mệt mỏi có ý nghĩa nào."],
            ["Practical Protocols Between Matches", "Phác Đồ Thực Tiễn Giữa Các Trận",
             "The practical window is 8-15 minutes of continuous low-intensity movement immediately after competition, followed by hydration and carbohydrate intake. Intensity above 60% of maximum reverses the benefit by generating additional lactate and delaying parasympathetic reactivation.",
             "Cửa sổ thực tiễn là 8-15 phút vận động liên tục cường độ thấp ngay sau thi đấu, tiếp theo là bù nước và nạp carbohydrate. Cường độ trên 60% mức tối đa sẽ đảo ngược lợi ích bằng cách sinh thêm lactate và làm chậm tái kích hoạt phó giao cảm."],
        ],
        "steps": [
            ["Begin Movement Within Five Minutes", "Start low-intensity movement within five minutes of the final point; waiting an hour removes most of the clearance advantage."],
            ["Cap the Intensity Deliberately", "Keep the intensity at conversational pace; if breathing prevents speech, the recovery has become training."],
            ["Bắt Đầu Vận Động Trong Vòng Năm Phút", "Bắt đầu vận động cường độ thấp trong vòng năm phút sau điểm cuối; chờ một giờ sẽ làm mất phần lớn lợi thế thải lactate."],
            ["Giới Hạn Cường Độ Một Cách Có Chủ Đích", "Giữ cường độ ở mức có thể nói chuyện; nếu hơi thở không cho phép nói, phục hồi đã trở thành tập luyện."],
        ],
        "errs": [
            ["Passive sitting immediately after a match", "Recovery is treated as the absence of activity", "Lactate clearance is delayed and the following session begins from a deeper deficit", "Perform 8-15 minutes of conversational-pace movement immediately after competition",
             "Ngồi thụ động ngay sau trận", "Phục hồi được coi là sự vắng mặt của hoạt động", "Việc thải lactate bị trì hoãn và buổi tập sau bắt đầu từ mức thiếu hụt sâu hơn", "Thực hiện 8-15 phút vận động ở mức nói chuyện được ngay sau thi đấu"],
            ["Making recovery too intense", "The session is judged by perceived effort rather than by purpose", "Additional lactate is produced and autonomic reactivation is delayed", "Keep recovery below 45% of maximal aerobic capacity and verify with a heart-rate ceiling",
             "Thực hiện phục hồi quá cường độ", "Buổi tập được đánh giá bằng nỗ lực cảm nhận thay vì bằng mục đích", "Lactate được sinh thêm và tái kích hoạt tự chủ bị trì hoãn", "Giữ phục hồi dưới 45% năng lực ưa khí tối đa và kiểm chứng bằng trần nhịp tim"],
        ],
        "drills": [
            ["Post-Match Flush", "10 minutes of cycling or jogging at conversational pace", "Xả Sau Trận", "10 phút đạp xe hoặc chạy bộ ở mức nói chuyện được"],
            ["Lactate Ladder", "Three 60 s efforts with 3 min active recovery between", "Thang Lactate", "Ba lần gắng 60 giây với 3 phút phục hồi chủ động ở giữa"],
        ],
    },
    "170": {
        "topic_en": "hydration, electrolyte ratios and core temperature regulation",
        "topic_vi": "bù nước, tỷ lệ điện giải và điều hòa nhiệt độ cốt lõi",
        "mech_en": "Fluid and electrolyte management is a **volume and concentration problem simultaneously**. Replacing sweat losses with plain water dilutes plasma sodium and can produce hyponatremia, while replacing them with over-concentrated solutions slows gastric emptying. The correct target is a sodium concentration of 500-1,000 mg per litre at a volume matching 80-100% of measured sweat loss.",
        "mech_vi": "Quản lý dịch và điện giải đồng thời là một **bài toán về thể tích và nồng độ**. Bù lượng mồ hôi mất đi bằng nước lọc sẽ pha loãng natri huyết tương và có thể gây hạ natri máu, trong khi bù bằng dung dịch quá đậm đặc sẽ làm chậm tốc độ làm rỗng dạ dày. Mục tiêu đúng là nồng độ natri 500-1.000 mg mỗi lít ở thể tích khớp 80-100% lượng mồ hôi đo được.",
        "vars": [
            ["Sweat Rate Measurement", "Đo tốc độ tiết mồ hôi", "0.8-2.2 L/h"],
            ["Sodium Concentration Target", "Mục tiêu nồng độ natri", "500-1,000 mg/L"],
            ["Core Temperature Ceiling", "Trần nhiệt độ cốt lõi", "39.0 degrees Celsius"],
        ],
        "subs": [
            ["Sweat Rate and Sodium Loss Quantification", "Định Lượng Tốc Độ Mồ Hôi & Mất Natri",
             "Sweat rate is measured by weighing before and after a one-hour session with fluid intake recorded; the difference plus intake gives the hourly loss. Sodium concentration varies fivefold between individuals, so laboratory or patch testing is required before individualising a drink formula.",
             "Tốc độ tiết mồ hôi được đo bằng cách cân trước và sau một buổi tập một giờ với lượng dịch nạp được ghi lại; phần chênh lệch cộng với lượng nạp cho ra mức mất mỗi giờ. Nồng độ natri dao động gấp năm lần giữa các cá nhân, nên cần xét nghiệm hoặc dùng miếng dán đo trước khi cá nhân hóa công thức đồ uống."],
            ["Thermoregulation and Performance Thresholds", "Điều Hòa Nhiệt & Các Ngưỡng Hiệu Suất",
             "Core temperature above 39.0 degrees Celsius reduces power output by 8-15% and impairs decision accuracy before the athlete perceives heat illness. Precooling with 10-15 minutes of cold exposure before play lowers starting core temperature by 0.3-0.5 degrees and extends the time before that threshold is reached.",
             "Nhiệt độ cốt lõi trên 39,0 độ C làm giảm công suất đầu ra 8-15% và suy giảm độ chính xác quyết định trước khi vận động viên cảm nhận được bệnh do nhiệt. Làm mát trước bằng 10-15 phút tiếp xúc lạnh trước khi thi đấu hạ nhiệt độ cốt lõi ban đầu 0,3-0,5 độ và kéo dài thời gian trước khi chạm ngưỡng đó."],
        ],
        "steps": [
            ["Measure Sweat Rate Before Prescribing Fluid", "Complete a one-hour weighed session before setting any fluid plan; population averages are unreliable at the individual level."],
            ["Drink to Thirst With Electrolytes, Not to a Fixed Volume", "Use thirst plus a measured hourly target rather than a fixed schedule; over-drinking is a real risk in cool conditions."],
            ["Đo Tốc Độ Mồ Hôi Trước Khi Chỉ Định Dịch", "Hoàn thành một buổi tập một giờ có cân đo trước khi thiết lập bất kỳ kế hoạch dịch nào; các giá trị trung bình quần thể không đáng tin ở cấp cá nhân."],
            ["Uống Theo Khát Kèm Điện Giải, Không Uống Theo Thể Tích Cố Định", "Dùng cảm giác khát cộng với mục tiêu mỗi giờ đã đo thay vì một lịch cố định; uống quá nhiều là rủi ro thực sự trong điều kiện mát."],
        ],
        "errs": [
            ["Drinking plain water only during long matches", "Electrolyte losses are not considered separately from fluid losses", "Plasma sodium falls and performance degrades with headache and nausea", "Include 500-1,000 mg of sodium per litre in all fluids consumed beyond one hour",
             "Chỉ uống nước lọc trong các trận dài", "Mất điện giải không được xem xét tách biệt khỏi mất dịch", "Natri huyết tương giảm và hiệu suất suy giảm kèm đau đầu và buồn nôn", "Bổ sung 500-1.000 mg natri mỗi lít cho mọi loại dịch uống sau một giờ"],
            ["Ignoring precooling in hot conditions", "Cooling is treated as comfort rather than as performance strategy", "Core temperature reaches the impairment threshold before the third set", "Precool 10-15 minutes before play and monitor core temperature or body-mass change",
             "Bỏ qua việc làm mát trước trong điều kiện nóng", "Làm mát được coi là sự thoải mái thay vì chiến lược hiệu suất", "Nhiệt độ cốt lõi chạm ngưỡng suy giảm trước set thứ ba", "Làm mát trước 10-15 phút trước khi thi đấu và theo dõi nhiệt độ cốt lõi hoặc mức thay đổi khối lượng cơ thể"],
        ],
        "drills": [
            ["Sweat Rate Test", "Weigh in and out of a one-hour session with fluid logged", "Bài Đo Mồ Hôi", "Cân trước và sau buổi tập một giờ với lượng dịch được ghi lại"],
            ["Precool Protocol", "10-15 minutes of cooling before a hot-weather session", "Phác Đồ Làm Mát Trước", "10-15 phút làm mát trước buổi tập trong thời tiết nóng"],
        ],
    },
    "171": {
        "topic_en": "eccentric deceleration strength for multi-directional footwork",
        "topic_vi": "sức mạnh hãm lệch tâm cho bộ pháp đa hướng",
        "mech_en": "Deceleration is the **rate-limiting skill of tennis movement**: the ability to absorb 3-4 times body mass at the plant foot determines how quickly the next acceleration can begin. Eccentric strength is therefore not a supplementary quality but the direct determinant of change-of-direction time.",
        "mech_vi": "Giảm tốc là **kỹ năng giới hạn của di chuyển tennis**: khả năng hấp thụ 3-4 lần khối lượng cơ thể ở bàn chân trụ quyết định tốc độ bắt đầu lần tăng tốc kế tiếp. Do đó sức mạnh lệch tâm không phải một phẩm chất bổ trợ mà là yếu tố quyết định trực tiếp thời gian đổi hướng.",
        "vars": [
            ["Braking Force at Plant", "Lực hãm tại bàn chân trụ", "3-4 x body mass"],
            ["Penultimate Step Length", "Độ dài bước áp chót", "60-75% of maximal stride"],
            ["Change-of-Direction Time", "Thời gian đổi hướng", "2.30-2.55 s for 5-10-5"],
        ],
        "subs": [
            ["Mechanics of the Braking Phase", "Cơ Học Của Pha Hãm",
             "Braking begins with the penultimate step, which must shorten to lower the centre of mass and place the foot ahead of the hips. A long final step converts braking into a slow, energy-expensive stop and delays the subsequent push-off by 120-200 ms.",
             "Việc hãm bắt đầu từ bước áp chót, bước này phải ngắn lại để hạ khối tâm và đặt bàn chân trước hông. Một bước cuối dài biến việc hãm thành một điểm dừng chậm và tốn năng lượng, đồng thời trì hoãn pha đẩy tiếp theo 120-200 mili giây."],
            ["Progression of Eccentric Loading", "Tiến Triển Tải Lệch Tâm",
             "Eccentric capacity is built with controlled landings, then lateral plant-and-hold patterns, then reactive drills with an external cue. Progressing directly to reactive work without the controlled phase produces compensation and knee valgus under fatigue, which is the mechanism behind a large share of patellar tendon cases.",
             "Năng lực lệch tâm được xây bằng các bài tiếp đất có kiểm soát, rồi các mẫu đặt chân ngang và giữ vững, rồi các bài phản ứng với tín hiệu bên ngoài. Tiến trực tiếp tới bài phản ứng mà không qua pha kiểm soát sẽ tạo ra bù trừ và đầu gối sụp vào trong khi mệt, và đây là cơ chế đằng sau phần lớn các trường hợp gân bánh chè."],
        ],
        "steps": [
            ["Master Controlled Landings First", "Two weeks of controlled landings before any reactive deceleration drill; the sequence is not optional."],
            ["Cue the Penultimate Step Explicitly", "Use the external cue of shortening the step before the plant; internal cues about muscle activation degrade movement quality."],
            ["Thành Thạo Tiếp Đất Có Kiểm Soát Trước", "Hai tuần tiếp đất có kiểm soát trước bất kỳ bài hãm phản ứng nào; trình tự này không được bỏ qua."],
            ["Ra Tín Hiệu Rõ Cho Bước Áp Chót", "Dùng tín hiệu bên ngoài là rút ngắn bước trước khi đặt chân; các tín hiệu bên trong về kích hoạt cơ làm suy giảm chất lượng vận động."],
        ],
        "errs": [
            ["Progressing straight to reactive drills", "The controlled phase is skipped as too easy", "Compensatory landing patterns appear and knee valgus increases under fatigue", "Complete two weeks of controlled landings before adding any reactive cue",
             "Tiến thẳng tới các bài phản ứng", "Pha kiểm soát bị bỏ qua vì cho là quá dễ", "Các mẫu tiếp đất bù trừ xuất hiện và đầu gối sụp vào trong tăng khi mệt", "Hoàn thành hai tuần tiếp đất có kiểm soát trước khi thêm bất kỳ tín hiệu phản ứng nào"],
            ["Training deceleration only in a straight line", "Deceleration is assumed to be direction-independent", "Lateral braking capacity stays untrained despite good linear test results", "Include lateral and diagonal plant-and-hold patterns in every deceleration session",
             "Chỉ tập giảm tốc theo đường thẳng", "Giảm tốc được giả định là không phụ thuộc hướng", "Năng lực hãm ngang vẫn không được huấn luyện dù kết quả kiểm tra đường thẳng tốt", "Đưa các mẫu đặt chân ngang và chéo và giữ vững vào mọi buổi tập giảm tốc"],
        ],
        "drills": [
            ["Lateral Plant and Hold", "Approach, plant, hold 2 s, then re-accelerate; 5 positions", "Đặt Chân Ngang Và Giữ", "Tiếp cận, đặt chân, giữ 2 giây, rồi tăng tốc lại; 5 vị trí"],
            ["Single-Leg Drop Landing", "Drop from 30-40 cm and stick the landing, 4 x 6 per leg", "Tiếp Đất Một Chân Từ Độ Cao", "Rơi từ 30-40 cm và giữ vững khi tiếp đất, 4 x 6 mỗi chân"],
        ],
    },
    "172": {
        "topic_en": "rotator cuff thermal warm-up and scapular protocols",
        "topic_vi": "phác đồ làm ấm rotator cuff và bài tập vai",
        "mech_en": "The shoulder requires **thermal and neuromuscular preparation** before serving because the serve places the glenohumeral joint through its largest range of motion at the highest angular velocity in the sport. A structured warm-up raises muscle temperature, increases scapular control, and reduces the risk of impingement during the internal rotation phase.",
        "mech_vi": "Vai cần **chuẩn bị nhiệt và thần kinh - cơ** trước khi giao bóng vì động tác giao bóng đưa khớp vai qua biên độ vận động lớn nhất ở vận tốc góc cao nhất trong môn này. Một quy trình khởi động có cấu trúc làm tăng nhiệt độ cơ, tăng kiểm soát xương bả vai, và giảm nguy cơ chèn ép trong pha xoay trong.",
        "vars": [
            ["Warm-Up Duration", "Thời lượng khởi động", "12-18 min"],
            ["Shoulder External Rotation Range", "Biên độ xoay ngoài vai", "90-100 degrees"],
            ["Scapular Upward Rotation", "Xoay lên của xương bả vai", "50-60 degrees at full elevation"],
        ],
        "subs": [
            ["Thermal Effects on Muscle and Tendon", "Hiệu Ứng Nhiệt Lên Cơ & Gân",
             "Raising muscle temperature by 2-3 degrees Celsius increases nerve conduction velocity, reduces viscous resistance in the tendon, and improves the muscle's capacity to absorb eccentric load. The practical threshold is 10-15 minutes of progressive activity, which is why abbreviated warm-ups precede a substantial share of shoulder injuries.",
             "Tăng nhiệt độ cơ lên 2-3 độ C làm tăng tốc độ dẫn truyền thần kinh, giảm sức cản nhớt ở gân, và cải thiện khả năng hấp thụ tải lệch tâm của cơ. Ngưỡng thực tiễn là 10-15 phút hoạt động tiến triển, đó là lý do các quy trình khởi động rút ngắn đi trước một phần đáng kể các chấn thương vai."],
            ["Scapular Control and the Y-T-W Pattern", "Kiểm Soát Xương Bả Vai & Mẫu Y-T-W",
             "Scapular upward rotation and posterior tilt create the subacromial space through which the rotator cuff tendon passes. The Y-T-W series loads the lower trapezius and serratus anterior in the positions where that space is smallest, which is why it is performed before serving rather than after.",
             "Xoay lên và nghiêng sau của xương bả vai tạo ra khoang dưới mỏm cùng vai nơi gân rotator cuff đi qua. Chuỗi Y-T-W nạp cơ thang dưới và cơ răng trước ở đúng những tư thế mà khoang đó hẹp nhất, đó là lý do chuỗi này được thực hiện trước khi giao bóng thay vì sau."],
        ],
        "steps": [
            ["Elevate Temperature Before Loading", "Complete 5-8 minutes of general elevation before any shoulder-specific resistance work."],
            ["Perform Y-T-W Before Serving, Not After", "The series is a preparation protocol; performed after serving it delivers no protective benefit to the session."],
            ["Nâng Nhiệt Độ Trước Khi Nạp Tải", "Hoàn thành 5-8 phút nâng nhiệt tổng quát trước mọi bài kháng lực riêng cho vai."],
            ["Thực Hiện Y-T-W Trước Khi Giao Bóng, Không Phải Sau", "Chuỗi này là phác đồ chuẩn bị; thực hiện sau khi giao bóng sẽ không mang lại lợi ích bảo vệ nào cho buổi tập."],
        ],
        "errs": [
            ["Serving with a cold shoulder", "The warm-up is shortened to save time before a match", "Impingement risk rises in the first four service games", "Never serve before completing 10-15 minutes of progressive shoulder preparation",
             "Giao bóng với vai chưa được làm ấm", "Khởi động bị rút ngắn để tiết kiệm thời gian trước trận", "Nguy cơ chèn ép tăng trong bốn game giao bóng đầu tiên", "Không bao giờ giao bóng trước khi hoàn thành 10-15 phút chuẩn bị vai tiến triển"],
            ["Doing Y-T-W after the session only", "The protocol is treated as rehabilitation rather than preparation", "Scapular control is not available when serving load is applied", "Move the Y-T-W series to the pre-serve phase and keep the post-session version only as reinforcement",
             "Chỉ tập Y-T-W sau buổi tập", "Phác đồ được coi là phục hồi chức năng thay vì chuẩn bị", "Kiểm soát xương bả vai không khả dụng khi tải giao bóng được áp dụng", "Chuyển chuỗi Y-T-W sang pha trước giao bóng và chỉ giữ phiên bản sau buổi như biện pháp củng cố"],
        ],
        "drills": [
            ["Y-T-W Series", "Bodyweight or 1 kg, 3 x 10 each position, controlled tempo", "Chuỗi Y-T-W", "Trọng lượng cơ thể hoặc 1 kg, 3 x 10 mỗi tư thế, nhịp có kiểm soát"],
            ["Band External Rotation", "3 x 15 at 90 degrees abduction, slow return", "Xoay Ngoài Với Dây Kháng Lực", "3 x 15 ở 90 độ dạng vai, pha về chậm"],
        ],
    },
    "173": {
        "topic_en": "core anti-rotation strength for stroke stability",
        "topic_vi": "sức mạnh chống xoay cốt lõi cho ổn định cú đánh",
        "mech_en": "Tennis generates rotation and simultaneously requires the trunk to **resist unwanted rotation** so that the hips and shoulders can transfer rather than dissipate force. Anti-rotation strength is therefore the quality that converts rotational power into ball speed instead of into postural drift.",
        "mech_vi": "Tennis tạo ra xoay và đồng thời đòi hỏi thân người **chống lại xoay không mong muốn** để hông và vai có thể truyền lực thay vì tiêu tán nó. Do đó sức mạnh chống xoay là phẩm chất chuyển công suất xoay thành tốc độ bóng thay vì thành sự trôi vị thế.",
        "vars": [
            ["Pallof Press Load", "Tải bài ép chống xoay", "20-35% body mass"],
            ["Trunk Rotation Loss Under Load", "Mức mất xoay thân dưới tải", "under 8 degrees"],
            ["Hip-Shoulder Separation Retention", "Duy trì tách hông - vai", "45-55 degrees at contact"],
        ],
        "subs": [
            ["Force Transfer Versus Force Dissipation", "Truyền Lực So Với Tiêu Tán Lực",
             "In a forehand the pelvis rotates ahead of the thorax, creating a separation angle of 45-55 degrees that stores elastic energy. If the anti-rotation musculature cannot hold the thorax while the pelvis rotates, the separation collapses and 15-25% of available rotational energy is dissipated as postural movement rather than delivered to the racket.",
             "Trong cú forehand, khung chậu xoay trước lồng ngực, tạo ra góc tách 45-55 độ tích trữ năng lượng đàn hồi. Nếu hệ cơ chống xoay không giữ được lồng ngực trong khi khung chậu xoay, góc tách sụp và 15-25% năng lượng xoay khả dụng bị tiêu tán thành chuyển động vị thế thay vì được truyền tới vợt."],
            ["Programming Anti-Rotation Without Stiffening", "Lập Trình Chống Xoay Mà Không Làm Cứng",
             "The programming constraint is that anti-rotation strength must not reduce mobility. Loads of 20-35% of body mass in press-out patterns build the capacity, while heavier loading and breath-holding patterns tend to reduce the thoracic mobility required for the serve.",
             "Ràng buộc lập trình là sức mạnh chống xoay không được làm giảm tính di động. Tải 20-35% khối lượng cơ thể trong các mẫu ép ra sẽ xây năng lực, trong khi tải nặng hơn và các mẫu nín thở có xu hướng làm giảm tính di động của lồng ngực cần cho động tác giao bóng."],
        ],
        "steps": [
            ["Test Separation Before Loading", "Measure hip-shoulder separation on video before adding anti-rotation load; a low baseline indicates a mobility issue rather than a strength issue."],
            ["Exhale Through the Press", "Maintain continuous breathing through every anti-rotation press to preserve intra-abdominal pressure regulation without breath-holding."],
            ["Kiểm Tra Góc Tách Trước Khi Nạp Tải", "Đo góc tách hông - vai trên video trước khi thêm tải chống xoay; nền thấp cho thấy vấn đề di động hơn là vấn đề sức mạnh."],
            ["Thở Ra Xuyên Suốt Pha Ép", "Duy trì thở liên tục qua mọi lần ép chống xoay để giữ điều hòa áp lực trong ổ bụng mà không cần nín thở."],
        ],
        "errs": [
            ["Using heavy bilateral rotation instead of anti-rotation", "Rotational power is assumed to be the limiting quality", "Thoracic mobility decreases while separation under fatigue remains poor", "Emphasise anti-rotation press patterns at 20-35% body mass and verify thoracic mobility each mesocycle",
             "Dùng xoay hai bên nặng thay vì chống xoay", "Công suất xoay được giả định là phẩm chất giới hạn", "Tính di động lồng ngực giảm trong khi góc tách khi mệt vẫn kém", "Nhấn mạnh các mẫu ép chống xoay ở 20-35% khối lượng cơ thể và kiểm chứng tính di động lồng ngực mỗi trung chu kỳ"],
            ["Breath-holding during presses", "Intra-abdominal pressure is maximised for load rather than for transfer", "Thoracic mobility is restricted and serve rhythm degrades", "Maintain continuous exhalation through the press and cap loads at 35% body mass",
             "Nín thở khi thực hiện bài ép", "Áp lực trong ổ bụng được tối đa hóa cho tải thay vì cho việc truyền lực", "Tính di động lồng ngực bị hạn chế và nhịp giao bóng suy giảm", "Duy trì thở ra liên tục qua pha ép và giới hạn tải ở 35% khối lượng cơ thể"],
        ],
        "drills": [
            ["Pallof Press", "3 x 12 per side at 20-35% body mass with continuous breathing", "Ép Chống Xoay", "3 x 12 mỗi bên ở 20-35% khối lượng cơ thể với thở liên tục"],
            ["Half-Kneeling Chop", "3 x 10 per side with controlled return", "Chặt Nửa Quỳ", "3 x 10 mỗi bên với pha về có kiểm soát"],
        ],
    },
    "174": {
        "topic_en": "fascial release and self-myofascial sheathing",
        "topic_vi": "giải phóng mô sợi và tự giải phóng mô sợi",
        "mech_en": "Self-myofascial techniques do not permanently lengthen tissue; they **modulate afferent input** and transiently reduce perceived stiffness, which can restore range of motion for 10-30 minutes. Used as a preparation tool within that window it is useful; used as a substitute for loading it produces no structural change.",
        "mech_vi": "Các kỹ thuật tự giải phóng mô sợi không làm dài mô vĩnh viễn; chúng **điều biến đầu vào hướng tâm** và tạm thời giảm cảm giác cứng, có thể phục hồi biên độ vận động trong 10-30 phút. Dùng như một công cụ chuẩn bị trong cửa sổ đó thì hữu ích; dùng như thay thế cho việc nạp tải thì không tạo ra thay đổi cấu trúc nào.",
        "vars": [
            ["Pressure Duration per Site", "Thời gian ép mỗi vị trí", "60-120 s"],
            ["Range Gain Window", "Cửa sổ lợi ích biên độ", "10-30 min"],
            ["Pressure Intensity", "Cường độ ép", "5-7 of 10 discomfort"],
        ],
        "subs": [
            ["Neurophysiological Mechanism", "Cơ Chế Thần Kinh Sinh Lý",
             "Pressure applied to fascia and muscle alters afferent signalling from mechanoreceptors, which reduces protective tone and raises stretch tolerance. The change is neural and temporary, which explains both the immediate range-of-motion gain and the absence of any lasting structural change.",
             "Áp lực tác dụng lên mô sợi và cơ làm thay đổi tín hiệu hướng tâm từ các thụ thể cơ học, điều này làm giảm trương lực bảo vệ và nâng ngưỡng chịu căng. Sự thay đổi mang tính thần kinh và tạm thời, điều này giải thích cả lợi ích biên độ tức thời lẫn sự vắng mặt của bất kỳ thay đổi cấu trúc lâu dài nào."],
            ["Timing Within the Session", "Định Thời Trong Buổi Tập",
             "The technique is most useful 10-20 minutes before activity, when the transient range gain can be used immediately, and least useful as a standalone recovery modality. Combining it with active movement in the same window produces a larger functional gain than either alone.",
             "Kỹ thuật này hữu ích nhất 10-20 phút trước khi vận động, khi lợi ích biên độ tạm thời có thể được dùng ngay, và ít hữu ích nhất khi dùng như một phương thức phục hồi độc lập. Kết hợp nó với vận động chủ động trong cùng cửa sổ tạo ra lợi ích chức năng lớn hơn so với từng biện pháp riêng lẻ."],
        ],
        "steps": [
            ["Apply Pressure Before, Move After", "Follow every release with active movement in the new range; without movement the transient gain is lost within minutes."],
            ["Avoid Aggressive Pressure on Acute Tissue", "Never apply high pressure over acutely painful or recently injured tissue; the technique is a modulator, not a treatment."],
            ["Ép Trước, Vận Động Sau", "Theo mỗi lần giải phóng bằng vận động chủ động trong biên độ mới; không có vận động, lợi ích tạm thời sẽ mất trong vài phút."],
            ["Tránh Ép Mạnh Lên Mô Đang Cấp", "Không bao giờ ép mạnh lên mô đang đau cấp hoặc vừa chấn thương; kỹ thuật này là một biện pháp điều biến, không phải một phương pháp điều trị."],
        ],
        "errs": [
            ["Using release as a substitute for strength work", "The transient range gain is mistaken for a structural adaptation", "Range of motion returns to baseline within 30 minutes and the underlying limitation persists", "Pair every release with loaded movement in the new range to consolidate the gain",
             "Dùng giải phóng mô sợi thay cho bài tập sức mạnh", "Lợi ích biên độ tạm thời bị nhầm với thích nghi cấu trúc", "Biên độ vận động trở về nền trong 30 phút và hạn chế nền vẫn tồn tại", "Ghép mỗi lần giải phóng với vận động có tải trong biên độ mới để củng cố lợi ích"],
            ["Applying excessive pressure to painful areas", "Discomfort is treated as evidence of effectiveness", "Acute tissue is irritated and symptoms worsen over the following 24 h", "Cap pressure at 5-7 of 10 discomfort and avoid acutely painful or recently injured areas entirely",
             "Ép quá mạnh lên vùng đau", "Sự khó chịu được coi là bằng chứng của hiệu quả", "Mô cấp bị kích thích và triệu chứng nặng hơn trong 24 giờ sau", "Giới hạn áp lực ở 5-7 trên 10 mức khó chịu và tránh hoàn toàn các vùng đau cấp hoặc vừa chấn thương"],
        ],
        "drills": [
            ["Targeted Release Plus Movement", "90 s release followed immediately by 10 active reps in the new range", "Giải Phóng Kèm Vận Động", "90 giây giải phóng, tiếp ngay bằng 10 lần vận động chủ động trong biên độ mới"],
            ["Pre-Session Sheathing", "A 6-8 minute sequence covering hip, thoracic, and calf sites", "Bọc Mô Trước Buổi Tập", "Trình tự 6-8 phút bao gồm hông, lồng ngực và cẳng chân"],
        ],
    },
}
