# -*- coding: utf-8 -*-
"""Per-article knowledge data, articles 163-168."""

DATA = {
    "163": {
        "topic_en": "metabolic work-to-rest ratio optimization",
        "topic_vi": "tối ưu tỷ lệ làm việc trên nghỉ chuyển hóa",
        "mech_en": "The work-to-rest ratio determines which energy system is trained, not the work duration alone. A 1:3 ratio restores roughly 70-80% of phosphocreatine and trains alactic power, while a 1:5 ratio restores 90%+ and trains the recovery process itself. Choosing between them is a decision about **which half of the point the athlete needs to improve**.",
        "mech_vi": "Tỷ lệ làm việc trên nghỉ quyết định hệ năng lượng nào được huấn luyện, chứ không chỉ thời lượng làm việc. Tỷ lệ 1:3 phục hồi khoảng 70-80% phosphocreatine và huấn luyện công suất yếm khí alactic, trong khi tỷ lệ 1:5 phục hồi trên 90% và huấn luyện chính quá trình phục hồi. Chọn giữa hai tỷ lệ là quyết định về **nửa nào của điểm bóng mà vận động viên cần cải thiện**.",
        "vars": [
            ["Phosphocreatine Restored at 1:3", "Phosphocreatine phục hồi ở tỷ lệ 1:3", "70-80%"],
            ["Phosphocreatine Restored at 1:5", "Phosphocreatine phục hồi ở tỷ lệ 1:5", "90-96%"],
            ["Heart Rate at End of Work Interval", "Nhịp tim cuối khoảng làm việc", "85-92% maximum"],
        ],
        "subs": [
            ["Phosphagen Kinetics and Ratio Selection", "Động Học Hệ Phosphagen & Việc Chọn Tỷ Lệ",
             "Phosphocreatine resynthesis follows a bi-exponential curve with a fast component restoring roughly 70% within 30 s and a slow component requiring 3-5 minutes for near-complete restoration. A 1:3 ratio therefore trains repeated power output from a partially depleted state, which matches the fifth and sixth points of a long game.",
             "Tái tổng hợp phosphocreatine tuân theo một đường cong hai thành phần mũ với thành phần nhanh phục hồi khoảng 70% trong 30 giây và thành phần chậm cần 3-5 phút để phục hồi gần hoàn toàn. Do đó tỷ lệ 1:3 huấn luyện đầu ra công suất lặp lại từ trạng thái thiếu hụt một phần, khớp với điểm thứ năm và thứ sáu của một game dài."],
            ["Aerobic Contribution at Each Ratio", "Đóng Góp Ưa Khí Ở Mỗi Tỷ Lệ",
             "At 1:3 the aerobic system contributes 25-35% of the work output; at 1:5 that share rises to 40-50%. Programming both ratios within a week trains the power ceiling and the recovery floor, which is why ratio variety outperforms a single fixed ratio across a mesocycle.",
             "Ở tỷ lệ 1:3, hệ ưa khí đóng góp 25-35% đầu ra công việc; ở tỷ lệ 1:5 tỷ lệ đó tăng lên 40-50%. Lập trình cả hai tỷ lệ trong một tuần sẽ huấn luyện cả trần công suất lẫn sàn phục hồi, đó là lý do đa dạng tỷ lệ vượt trội hơn một tỷ lệ cố định trong một trung chu kỳ."],
        ],
        "steps": [
            ["Match the Ratio to the Adaptation Target", "Declare the target before the session: alactic power uses 1:3, recovery capacity uses 1:5; sessions without a declared ratio drift toward comfort."],
            ["Cap Work Interval Quality Decay", "Terminate any set when output falls more than 8-10% below the first interval; beyond that the session trains fatigue tolerance rather than the target quality."],
            ["Khớp Tỷ Lệ Với Mục Tiêu Thích Nghi", "Tuyên bố mục tiêu trước buổi tập: công suất alactic dùng 1:3, năng lực phục hồi dùng 1:5; buổi tập không có tỷ lệ tuyên bố sẽ trôi về phía thoải mái."],
            ["Giới Hạn Mức Suy Giảm Chất Lượng Khoảng Làm Việc", "Kết thúc bất kỳ loạt nào khi đầu ra giảm hơn 8-10% so với khoảng đầu tiên; vượt ngưỡng đó buổi tập huấn luyện khả năng chịu mệt thay vì phẩm chất mục tiêu."],
        ],
        "errs": [
            ["Using one ratio for every conditioning session", "The ratio is chosen by habit rather than by adaptation target", "One energy system is overdeveloped and the other remains limiting", "Alternate 1:3 and 1:5 across the week and record which ratio matches which competitive demand",
             "Dùng một tỷ lệ cho mọi buổi thể lực", "Tỷ lệ được chọn theo thói quen thay vì theo mục tiêu thích nghi", "Một hệ năng lượng bị phát triển quá mức và hệ kia vẫn là yếu tố giới hạn", "Luân phiên 1:3 và 1:5 trong tuần và ghi lại tỷ lệ nào khớp với yêu cầu thi đấu nào"],
            ["Extending work intervals to fatigue", "Fatigue is treated as evidence of a valuable session", "Power output quality degrades and the trained quality shifts away from the target", "Terminate the set at 8-10% output decay and record the number of quality intervals achieved",
             "Kéo dài khoảng làm việc tới mức kiệt sức", "Mệt mỏi được coi là bằng chứng của một buổi tập giá trị", "Chất lượng đầu ra công suất suy giảm và phẩm chất được huấn luyện lệch khỏi mục tiêu", "Kết thúc loạt khi đầu ra giảm 8-10% và ghi lại số khoảng đạt chất lượng"],
        ],
        "drills": [
            ["1:3 Alactic Set", "6 x 20 s court sprints with 60 s recovery, tracked for output decay", "Loạt Alactic 1:3", "6 x 20 giây chạy nước rút trên sân với 60 giây phục hồi, theo dõi mức suy giảm đầu ra"],
            ["1:5 Recovery Set", "6 x 20 s with 100 s recovery, tracked for heart-rate return", "Loạt Phục Hồi 1:5", "6 x 20 giây với 100 giây phục hồi, theo dõi mức hồi nhịp tim"],
        ],
    },
    "164": {
        "topic_en": "posterior chain loading and force transfer",
        "topic_vi": "tải hậu chuỗi và truyền lực",
        "mech_en": "The posterior chain - gluteals, hamstrings, spinal erectors, and calf complex - is the **force transfer hub** between ground reaction and racket head. Weakness there does not present as weakness; it presents as a leak, where force generated at the ground is absorbed as unwanted segment motion instead of being delivered to the ball.",
        "mech_vi": "Hậu chuỗi - cơ mông, gân kheo, cơ dựng cột sống và phức hợp cẳng chân - là **trung tâm truyền lực** giữa phản lực mặt sân và đầu vợt. Sự yếu ở đó không biểu hiện như sự yếu; nó biểu hiện như một rò rỉ, nơi lực sinh ra ở mặt sân bị hấp thụ thành chuyển động phân đoạn không mong muốn thay vì được truyền tới bóng.",
        "vars": [
            ["Hip Hinge Load Capacity", "Năng lực chịu tải gập hông", "1.5-2.0 x body mass"],
            ["Hamstring Eccentric Strength", "Sức mạnh lệch tâm gân kheo", "0.8-1.1 x body mass"],
            ["Force Transfer Efficiency", "Hiệu suất truyền lực", "0.72-0.86"],
        ],
        "subs": [
            ["Anatomy of the Transfer Hub", "Giải Phẫu Trung Tâm Truyền Lực",
             "Ground reaction force passes through the foot, ankle, knee, and hip before reaching the trunk. Each joint can dissipate or transmit that force, and the hip is the largest single decision point: hip extensor weakness converts 20-30% of available force into anterior pelvic tilt and lumbar compensation.",
             "Phản lực mặt sân đi qua bàn chân, cổ chân, đầu gối và hông trước khi tới thân người. Mỗi khớp có thể tiêu tán hoặc truyền lực đó, và hông là điểm quyết định lớn nhất: sự yếu của cơ duỗi hông chuyển 20-30% lực khả dụng thành nghiêng trước khung chậu và bù trừ vùng thắt lưng."],
            ["Loading Patterns That Transfer to Tennis", "Các Mẫu Tải Truyền Được Sang Tennis",
             "Transfer is highest for single-leg hinge patterns at moderate load and moderate velocity, because tennis force production is unilateral and time-constrained. Bilateral maximal lifts improve capacity but transfer less directly; the practical mix is roughly 60% unilateral hinge and 40% bilateral strength work.",
             "Khả năng truyền cao nhất thuộc về các mẫu gập hông một chân ở tải vừa và vận tốc vừa, vì việc sinh lực trong tennis là đơn bên và bị giới hạn thời gian. Các bài nâng tối đa hai bên cải thiện năng lực nhưng truyền ít trực tiếp hơn; tỷ lệ thực tiễn là khoảng 60% gập hông một chân và 40% bài sức mạnh hai bên."],
        ],
        "steps": [
            ["Screen the Hinge Before Loading It", "Assess hip hinge quality with a bodyweight pattern first; loading a dysfunctional hinge reinforces the compensation instead of correcting it."],
            ["Load Unilaterally for Transfer", "At least six of every ten posterior-chain sets are single-leg; bilateral work is reserved for maximal strength maintenance."],
            ["Sàng Lọc Động Tác Gập Hông Trước Khi Nạp Tải", "Đánh giá chất lượng gập hông bằng mẫu trọng lượng cơ thể trước; nạp tải lên một động tác gập hông rối loạn sẽ củng cố sự bù trừ thay vì sửa nó."],
            ["Nạp Tải Đơn Bên Để Truyền Lực", "Ít nhất sáu trong mười loạt bài hậu chuỗi là một chân; bài hai bên được dành cho việc duy trì sức mạnh tối đa."],
        ],
        "errs": [
            ["Loading only bilateral barbell lifts", "Gym programming follows general strength templates", "Force transfer to unilateral tennis positions stays poor despite good test numbers", "Shift 60% of posterior-chain volume to single-leg hinge patterns at moderate load",
             "Chỉ nạp tải các bài tạ hai bên", "Lập trình phòng tập theo các mẫu sức mạnh tổng quát", "Truyền lực sang các tư thế tennis một bên vẫn kém dù chỉ số kiểm tra tốt", "Chuyển 60% khối lượng hậu chuỗi sang các mẫu gập hông một chân ở tải vừa"],
            ["Ignoring hip hinge quality", "Load is progressed by weight rather than by pattern quality", "Lumbar compensation increases and low-back symptoms appear during serving", "Screen the hinge at bodyweight before every loading progression and hold load until the pattern is clean",
             "Bỏ qua chất lượng động tác gập hông", "Tải được tăng theo mức tạ thay vì theo chất lượng động tác", "Bù trừ vùng thắt lưng tăng và triệu chứng đau lưng dưới xuất hiện khi giao bóng", "Sàng lọc động tác gập hông ở mức trọng lượng cơ thể trước mọi lần tăng tải và giữ nguyên tải cho tới khi động tác sạch"],
        ],
        "drills": [
            ["Single-Leg Romanian Deadlift", "3 s eccentric, moderate load, 4 x 8 per leg", "Gập Hông Một Chân Với Tạ", "Pha lệch tâm 3 giây, tải vừa, 4 x 8 mỗi chân"],
            ["Hip Hinge Patterning", "Bodyweight hinge against a dowel, 3 x 10 with contact maintained", "Tạo Mẫu Gập Hông", "Gập hông với trọng lượng cơ thể và một thanh gậy, 3 x 10 giữ điểm tiếp xúc"],
        ],
    },
    "165": {
        "topic_en": "neuromuscular reset protocols between sets",
        "topic_vi": "phác đồ khôi phục thần kinh - cơ giữa các set",
        "mech_en": "The 90-120 second changeover is a **neuromuscular reset window**, not merely a rest period. Its purpose is to lower autonomic arousal enough to restore movement quality while preserving the activation level required for the next set's first game, which is the most error-prone game of any set.",
        "mech_vi": "Khoảng đổi sân 90-120 giây là một **cửa sổ khôi phục thần kinh - cơ**, không chỉ là một khoảng nghỉ. Mục đích của nó là hạ mức kích thích tự chủ đủ để phục hồi chất lượng vận động trong khi vẫn giữ mức hoạt hóa cần thiết cho game đầu tiên của set kế tiếp, vốn là game dễ mắc lỗi nhất trong mọi set.",
        "vars": [
            ["Heart Rate Reduction Target", "Mục tiêu giảm nhịp tim", "25-40 bpm"],
            ["Breathing Rate at Reset", "Nhịp thở khi khôi phục", "6 breaths per minute"],
            ["Movement Quality Score After Reset", "Điểm chất lượng vận động sau khôi phục", "4-5 of 5"],
        ],
        "subs": [
            ["Autonomic State and Movement Quality", "Trạng Thái Tự Chủ & Chất Lượng Vận Động",
             "Elevated sympathetic tone narrows attention and reduces fine motor control, which is measurable as increased variability in ball placement. A structured reset that lowers heart rate 25-40 bpm within 90 seconds restores placement consistency by 12-20% in the first game of the following set.",
             "Trương lực giao cảm tăng cao làm thu hẹp sự chú ý và giảm kiểm soát vận động tinh, đo được dưới dạng tăng độ biến thiên trong vị trí đặt bóng. Một quy trình khôi phục có cấu trúc hạ nhịp tim 25-40 nhịp mỗi phút trong 90 giây phục hồi 12-20% tính nhất quán của vị trí bóng ở game đầu tiên của set kế tiếp."],
            ["The Four-Phase Reset Sequence", "Trình Tự Khôi Phục Bốn Pha",
             "The sequence is fixed: hydrate, breathe, mobilise, prime. Hydration restores plasma volume, breathing shifts autonomic balance, mobilisation restores joint range, and priming re-activates the specific pattern used in the next game. Skipping the priming phase is the most common error and produces a slow first game.",
             "Trình tự được cố định: bù nước, thở, di động, mồi hoạt hóa. Bù nước phục hồi thể tích huyết tương, thở dịch chuyển cân bằng tự chủ, di động phục hồi biên độ khớp, và mồi hoạt hóa tái kích hoạt mẫu cụ thể dùng trong game kế tiếp. Bỏ qua pha mồi hoạt hóa là lỗi phổ biến nhất và tạo ra một game đầu chậm."],
        ],
        "steps": [
            ["Fix the Sequence Order", "Execute the four phases in the same order at every changeover; a fixed sequence removes decision cost from a window where decisions are expensive."],
            ["Prime the Specific Pattern", "In the final 15 seconds, rehearse the exact first pattern of the next game with a shadow swing or a racket-handling drill."],
            ["Cố Định Thứ Tự Trình Tự", "Thực hiện bốn pha theo cùng một thứ tự ở mọi lần đổi sân; một trình tự cố định loại bỏ chi phí quyết định khỏi một cửa sổ mà ở đó quyết định rất đắt."],
            ["Mồi Hoạt Hóa Mẫu Cụ Thể", "Trong 15 giây cuối, tập lại đúng mẫu đầu tiên của game kế tiếp bằng động tác vung bóng hoặc bài xử lý vợt."],
        ],
        "errs": [
            ["Sitting passively through the changeover", "The break is treated as rest rather than as preparation", "Heart rate stays elevated and the first game of the set is the weakest", "Use the four-phase sequence at every changeover and verify heart-rate reduction of 25-40 bpm",
             "Ngồi thụ động suốt khoảng đổi sân", "Khoảng nghỉ được coi là để nghỉ ngơi thay vì để chuẩn bị", "Nhịp tim vẫn cao và game đầu của set là game yếu nhất", "Dùng trình tự bốn pha ở mọi lần đổi sân và kiểm chứng mức giảm nhịp tim 25-40 nhịp mỗi phút"],
            ["Skipping the priming phase", "Time pressure at the end of the changeover", "The first game begins with unactivated patterns and elevated error rate", "Reserve the final 15 seconds exclusively for priming and shorten hydration instead if time is short",
             "Bỏ qua pha mồi hoạt hóa", "Áp lực thời gian ở cuối khoảng đổi sân", "Game đầu bắt đầu với các mẫu chưa được hoạt hóa và tỷ lệ lỗi cao", "Dành riêng 15 giây cuối cho việc mồi hoạt hóa và rút ngắn bù nước nếu thiếu thời gian"],
        ],
        "drills": [
            ["Four-Phase Changeover", "Rehearse the full sequence in a 90 s simulated changeover", "Đổi Sân Bốn Pha", "Tập lại toàn bộ trình tự trong 90 giây đổi sân mô phỏng"],
            ["Priming Shadow Reps", "Five shadow reps of the declared first pattern in the final 15 s", "Hiệp Vung Bóng Mồi", "Năm lần vung bóng mô phỏng mẫu đầu tiên đã tuyên bố trong 15 giây cuối"],
        ],
    },
    "166": {
        "topic_en": "sleep architecture and growth hormone peak tuning",
        "topic_vi": "kiến trúc giấc ngủ và điều chỉnh đỉnh hormone tăng trưởng",
        "mech_en": "Growth hormone release is concentrated in **slow-wave sleep during the first two sleep cycles**, so both total duration and the timing of sleep onset determine the anabolic window. Delaying sleep onset by two hours removes a disproportionate share of that window, which is why late-night screen exposure after evening matches measurably impairs recovery.",
        "mech_vi": "Việc giải phóng hormone tăng trưởng tập trung vào **giấc ngủ sóng chậm trong hai chu kỳ ngủ đầu tiên**, nên cả tổng thời lượng lẫn thời điểm bắt đầu ngủ đều quyết định cửa sổ đồng hóa. Trì hoãn thời điểm ngủ hai giờ sẽ lấy đi một phần lớn bất tương xứng của cửa sổ đó, và đây là lý do việc tiếp xúc màn hình đêm muộn sau các trận đấu buổi tối làm suy giảm phục hồi một cách đo được.",
        "vars": [
            ["Slow-Wave Sleep Target", "Mục tiêu giấc ngủ sóng chậm", "90-120 min"],
            ["Sleep Onset Window", "Cửa sổ bắt đầu ngủ", "22:00-23:00"],
            ["Growth Hormone Peak Timing", "Thời điểm đỉnh hormone tăng trưởng", "first 90 min of sleep"],
        ],
        "subs": [
            ["Sleep Architecture and Anabolic Windows", "Kiến Trúc Giấc Ngủ & Các Cửa Sổ Đồng Hóa",
             "A normal night contains four to six cycles of 90 minutes, with slow-wave sleep concentrated in the first two. Roughly 70% of daily growth hormone secretion occurs during that period, so a night shortened from eight hours to six removes mostly rapid-eye-movement sleep and light sleep, while a delayed onset removes slow-wave sleep directly.",
             "Một đêm bình thường gồm bốn tới sáu chu kỳ 90 phút, với giấc ngủ sóng chậm tập trung ở hai chu kỳ đầu. Khoảng 70% lượng hormone tăng trưởng tiết ra hằng ngày diễn ra trong giai đoạn đó, nên một đêm bị rút từ tám giờ xuống sáu giờ chủ yếu lấy đi giấc ngủ chuyển động mắt nhanh và giấc ngủ nông, trong khi một đêm bắt đầu muộn lấy đi trực tiếp giấc ngủ sóng chậm."],
            ["Temperature, Light, and Caffeine Constraints", "Ràng Buộc Về Nhiệt Độ, Ánh Sáng & Caffeine",
             "Three controllable variables dominate sleep quality: core temperature must fall 0.5-1.0 degrees Celsius before sleep onset, light exposure above 10 lux in the hour before bed suppresses melatonin, and caffeine has a half-life of 5-6 hours, so an intake after 14:00 still exerts measurable effects at 22:00.",
             "Ba biến kiểm soát được chi phối chất lượng giấc ngủ: nhiệt độ cốt lõi phải giảm 0,5-1,0 độ C trước khi bắt đầu ngủ, tiếp xúc ánh sáng trên 10 lux trong giờ trước khi ngủ ức chế melatonin, và caffeine có thời gian bán thải 5-6 giờ, nên lượng nạp sau 14:00 vẫn gây hiệu ứng đo được ở 22:00."],
        ],
        "steps": [
            ["Fix the Wake Time, Not the Bedtime", "Anchor the wake time within a 30-minute window every day; the circadian system entrains to wake time, and bedtime then falls into place."],
            ["Cool and Dim Before Onset", "Lower core temperature with a cool shower and reduce light exposure below 10 lux in the final hour before sleep."],
            ["Cố Định Giờ Thức, Không Cố Định Giờ Ngủ", "Neo giờ thức trong cửa sổ 30 phút mỗi ngày; hệ nhịp sinh học cuốn theo giờ thức, và giờ ngủ sẽ tự ổn định theo đó."],
            ["Làm Mát Và Giảm Sáng Trước Khi Ngủ", "Hạ nhiệt độ cốt lõi bằng tắm nước mát và giảm tiếp xúc ánh sáng xuống dưới 10 lux trong giờ cuối trước khi ngủ."],
        ],
        "errs": [
            ["Chasing a fixed eight hours with an irregular schedule", "Duration is prioritized over timing consistency", "Sleep onset drifts later and slow-wave sleep is progressively truncated", "Anchor wake time first and hold it for 14 days before adjusting total duration",
             "Đuổi theo tám giờ cố định với lịch không đều", "Thời lượng được ưu tiên hơn tính nhất quán của thời điểm", "Thời điểm ngủ trôi muộn dần và giấc ngủ sóng chậm bị cắt ngắn dần", "Neo giờ thức trước và giữ nó trong 14 ngày trước khi điều chỉnh tổng thời lượng"],
            ["Late caffeine after evening competition", "Stimulant use is treated as performance support rather than as a sleep cost", "Sleep latency extends by 30-60 min and slow-wave sleep drops measurably", "Set a 14:00 caffeine cutoff and track sleep latency for two weeks",
             "Dùng caffeine muộn sau thi đấu buổi tối", "Chất kích thích được coi là hỗ trợ hiệu suất thay vì là chi phí giấc ngủ", "Độ trễ vào giấc kéo dài 30-60 phút và giấc ngủ sóng chậm giảm đo được", "Đặt mốc cắt caffeine lúc 14:00 và theo dõi độ trễ vào giấc trong hai tuần"],
        ],
        "drills": [
            ["Wake-Time Anchor", "Record wake time and sleep latency daily for 14 days", "Neo Giờ Thức", "Ghi giờ thức và độ trễ vào giấc hằng ngày trong 14 ngày"],
            ["Wind-Down Protocol", "60 min of sub-10-lux light with a cool shower before sleep", "Phác Đồ Thư Giãn", "60 phút với ánh sáng dưới 10 lux kèm tắm nước mát trước khi ngủ"],
        ],
    },
    "167": {
        "topic_en": "heart rate recovery trajectory tracking",
        "topic_vi": "theo dõi quỹ đạo phục hồi nhịp tim",
        "mech_en": "Heart rate recovery is the **slope of parasympathetic reactivation**, and its trajectory carries more information than any single resting value. A 30-40 bpm drop in the first 60 seconds reflects vagal tone; a flattened trajectory over consecutive sessions indicates accumulated strain before performance declines.",
        "mech_vi": "Phục hồi nhịp tim là **độ dốc của quá trình tái kích hoạt phó giao cảm**, và quỹ đạo của nó mang nhiều thông tin hơn bất kỳ giá trị nghỉ đơn lẻ nào. Mức giảm 30-40 nhịp mỗi phút trong 60 giây đầu phản ánh trương lực phế vị; một quỹ đạo bị làm phẳng qua nhiều buổi liên tiếp cho thấy căng thẳng tích lũy trước khi hiệu suất suy giảm.",
        "vars": [
            ["HRR at 60 Seconds", "Phục hồi nhịp tim ở 60 giây", "30-40 bpm drop"],
            ["HRR at 120 Seconds", "Phục hồi nhịp tim ở 120 giây", "50-60 bpm drop"],
            ["Flattening Threshold", "Ngưỡng làm phẳng", "over 8 bpm reduction in trend"],
        ],
        "subs": [
            ["Physiology of Post-Exercise Heart Rate Decay", "Sinh Lý Suy Giảm Nhịp Tim Sau Vận Động",
             "Heart rate decay after exercise has a fast vagal component in the first 60 seconds and a slower sympathetic withdrawal component over the following minutes. The fast component is the more sensitive marker of training status and autonomic strain, and it can be measured with nothing more than a stopwatch and a chest strap.",
             "Sự suy giảm nhịp tim sau vận động có một thành phần phế vị nhanh trong 60 giây đầu và một thành phần rút lui giao cảm chậm hơn trong những phút tiếp theo. Thành phần nhanh là dấu hiệu nhạy hơn về trạng thái tập luyện và căng thẳng tự chủ, và có thể đo chỉ bằng đồng hồ bấm giây và đai ngực."],
            ["Interpreting the Trajectory, Not the Value", "Diễn Giải Quỹ Đạo, Không Diễn Giải Giá Trị",
             "A single HRR value varies by 5-10 bpm with hydration, temperature, and sleep. The clinically useful signal is the 7-day rolling mean: a reduction of more than 8 bpm in that mean indicates that the current load exceeds recovery, independent of how the athlete feels.",
             "Một giá trị phục hồi nhịp tim đơn lẻ dao động 5-10 nhịp mỗi phút theo mức nước, nhiệt độ và giấc ngủ. Tín hiệu hữu ích là trung bình trượt 7 ngày: mức giảm hơn 8 nhịp mỗi phút ở trung bình đó cho thấy tải hiện tại vượt quá phục hồi, bất kể vận động viên cảm thấy thế nào."],
        ],
        "steps": [
            ["Standardise the Measurement", "Measure HRR exactly 60 and 120 seconds after a fixed standard effort; changing the effort invalidates the trend."],
            ["Review the Rolling Mean Weekly", "Act on the 7-day mean, not on single sessions; a single flattened value after a hard match is noise."],
            ["Chuẩn Hóa Phép Đo", "Đo phục hồi nhịp tim đúng ở 60 và 120 giây sau một mức gắng chuẩn cố định; thay đổi mức gắng sẽ vô hiệu hóa xu hướng."],
            ["Xem Lại Trung Bình Trượt Mỗi Tuần", "Hành động dựa trên trung bình 7 ngày, không dựa trên từng buổi; một giá trị bị làm phẳng đơn lẻ sau một trận nặng chỉ là nhiễu."],
        ],
        "errs": [
            ["Measuring HRR after inconsistent efforts", "The measurement is taken whenever convenient", "The trend reflects effort variation rather than recovery status", "Use a fixed standard effort and identical timing; discard any measurement that deviates from the protocol",
             "Đo phục hồi nhịp tim sau những mức gắng không nhất quán", "Phép đo được thực hiện bất cứ khi nào thuận tiện", "Xu hướng phản ánh sự biến thiên mức gắng thay vì trạng thái phục hồi", "Dùng một mức gắng chuẩn cố định và thời điểm giống hệt; loại bỏ mọi phép đo lệch khỏi phác đồ"],
            ["Reacting to single-session values", "Daily fluctuations are treated as signal", "The training plan oscillates and loses progression structure", "Act only on 7-day rolling means and adjust volume rather than cancel the stimulus",
             "Phản ứng với giá trị của một buổi đơn lẻ", "Dao động hằng ngày được coi là tín hiệu", "Kế hoạch tập dao động và mất cấu trúc tiến triển", "Chỉ hành động theo trung bình trượt 7 ngày và điều chỉnh khối lượng thay vì hủy kích thích"],
        ],
        "drills": [
            ["Standard HRR Test", "Fixed 3-minute court effort, then measure at 60 s and 120 s", "Bài Đo Phục Hồi Chuẩn", "Gắng sức 3 phút trên sân cố định, rồi đo ở 60 giây và 120 giây"],
            ["Seven-Day Trend Log", "Record daily HRR and plot the rolling mean", "Nhật Ký Xu Hướng Bảy Ngày", "Ghi phục hồi nhịp tim hằng ngày và vẽ trung bình trượt"],
        ],
    },
    "168": {
        "topic_en": "continuous glucose monitoring for match fueling",
        "topic_vi": "theo dõi đường huyết liên tục cho năng lượng thi đấu",
        "mech_en": "Continuous glucose monitoring converts match fueling from a scheduled habit into a **feedback-controlled process**. The relevant signals are the rate of change rather than the absolute value, and the practical target is stability within 5.0-8.0 mmol/L, because rapid excursions in either direction precede both energy crashes and gastrointestinal distress.",
        "mech_vi": "Theo dõi đường huyết liên tục chuyển việc nạp năng lượng thi đấu từ một thói quen theo lịch thành một **quá trình được điều khiển bằng phản hồi**. Các tín hiệu liên quan là tốc độ thay đổi chứ không phải giá trị tuyệt đối, và mục tiêu thực tiễn là ổn định trong khoảng 5,0-8,0 mmol/L, vì những dao động nhanh theo cả hai hướng đều đi trước cả sự sụp năng lượng lẫn rối loạn tiêu hóa.",
        "vars": [
            ["Target Glucose Band", "Dải đường huyết mục tiêu", "5.0-8.0 mmol/L"],
            ["Rate-of-Change Ceiling", "Trần tốc độ thay đổi", "2.0 mmol/L per 15 min"],
            ["Carbohydrate Dose per Hour", "Liều carbohydrate mỗi giờ", "30-60 g/h"],
        ],
        "subs": [
            ["Rate of Change as the Primary Signal", "Tốc độ thay đổi là tín hiệu chính",
             "A glucose value of 6.5 mmol/L rising at 2.5 mmol/L per 15 minutes produces a different physiological situation from the same value falling at the same rate. Interpretation therefore requires the trend arrow, and fueling decisions are made on the rate rather than on the number.",
             "Một giá trị đường huyết 6,5 mmol/L đang tăng 2,5 mmol/L mỗi 15 phút tạo ra tình huống sinh lý khác với cùng giá trị đó đang giảm ở cùng tốc độ. Do đó việc diễn giải cần mũi tên xu hướng, và các quyết định nạp năng lượng được đưa ra dựa trên tốc độ thay vì dựa trên con số."],
            ["Fuelling Strategy for a Three-Set Match", "Chiến Lược Nạp Năng Lượng Cho Trận Ba Set",
             "A three-set match lasting 150-180 minutes requires 75-180 g of carbohydrate delivered in small, frequent doses beginning before the first game. Bolus intake of more than 60 g within 20 minutes raises the risk of gastrointestinal distress by shifting blood flow away from the gut during play.",
             "Một trận ba set kéo dài 150-180 phút cần 75-180 g carbohydrate được cung cấp thành những liều nhỏ, thường xuyên, bắt đầu trước game đầu tiên. Nạp một lần hơn 60 g trong 20 phút làm tăng nguy cơ rối loạn tiêu hóa bằng cách chuyển dòng máu ra khỏi đường tiêu hóa trong khi thi đấu."],
        ],
        "steps": [
            ["Establish a Baseline Curve", "Wear the sensor for five days before using it competitively; the individual response to specific foods must be known before any in-match decision."],
            ["Fuel Before the First Drop", "Begin carbohydrate intake when the trend turns downward, not after the value falls below the band; correcting a deficit during play is slower than preventing it."],
            ["Thiết Lập Đường Cong Nền", "Đeo cảm biến năm ngày trước khi dùng trong thi đấu; đáp ứng cá nhân với từng loại thực phẩm phải được biết trước mọi quyết định trong trận."],
            ["Nạp Trước Khi Có Mức Giảm Đầu Tiên", "Bắt đầu nạp carbohydrate khi xu hướng chuyển xuống, không phải sau khi giá trị rơi dưới dải; sửa mức thiếu hụt trong khi thi đấu chậm hơn ngăn nó xảy ra."],
        ],
        "errs": [
            ["Chasing a target number instead of a stable rate", "The absolute value is treated as the control variable", "Large bolus corrections create oscillations and gastrointestinal symptoms", "Control the rate of change and cap bolus doses at 30 g per 20 minutes",
             "Đuổi theo một con số mục tiêu thay vì một tốc độ ổn định", "Giá trị tuyệt đối được coi là biến kiểm soát", "Những lần sửa bằng liều lớn tạo ra dao động và triệu chứng tiêu hóa", "Kiểm soát tốc độ thay đổi và giới hạn liều nạp ở 30 g mỗi 20 phút"],
            ["Using the sensor competitively without a baseline", "The device is adopted as a real-time coach without individual calibration", "Decisions are made from population norms that do not match the athlete", "Complete a five-day baseline before any in-match fueling decision",
             "Dùng cảm biến trong thi đấu mà không có nền", "Thiết bị được dùng như huấn luyện viên thời gian thực mà không hiệu chuẩn cá nhân", "Quyết định được đưa ra từ chuẩn quần thể không khớp với vận động viên", "Hoàn thành nền năm ngày trước mọi quyết định nạp năng lượng trong trận"],
        ],
        "drills": [
            ["Five-Day Baseline", "Log glucose response to standard pre-match meals for five days", "Nền Năm Ngày", "Ghi đáp ứng đường huyết với các bữa ăn chuẩn trước trận trong năm ngày"],
            ["Timed Fueling Set", "Practise 30 g per 20 min intake during a simulated three-set session", "Set Nạp Năng Lượng Theo Thời Gian", "Tập nạp 30 g mỗi 20 phút trong buổi mô phỏng ba set"],
        ],
    },
}
